// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: api/services/portfolio_service.proto

package services

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculatePortfolioValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PortfolioId   string                 `protobuf:"bytes,1,opt,name=portfolio_id,json=portfolioId,proto3" json:"portfolio_id,omitempty"`
	QuoteAssetId  string                 `protobuf:"bytes,2,opt,name=quote_asset_id,json=quoteAssetId,proto3" json:"quote_asset_id,omitempty"` // e.g., "USD", "BTC" - the currency to calculate value in
	AtTime        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=at_time,json=atTime,proto3" json:"at_time,omitempty"`                     // Optional: Calculate value at a specific point in time (requires price history)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculatePortfolioValueRequest) Reset() {
	*x = CalculatePortfolioValueRequest{}
	mi := &file_api_services_portfolio_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatePortfolioValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePortfolioValueRequest) ProtoMessage() {}

func (x *CalculatePortfolioValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_portfolio_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePortfolioValueRequest.ProtoReflect.Descriptor instead.
func (*CalculatePortfolioValueRequest) Descriptor() ([]byte, []int) {
	return file_api_services_portfolio_service_proto_rawDescGZIP(), []int{0}
}

func (x *CalculatePortfolioValueRequest) GetPortfolioId() string {
	if x != nil {
		return x.PortfolioId
	}
	return ""
}

func (x *CalculatePortfolioValueRequest) GetQuoteAssetId() string {
	if x != nil {
		return x.QuoteAssetId
	}
	return ""
}

func (x *CalculatePortfolioValueRequest) GetAtTime() *timestamppb.Timestamp {
	if x != nil {
		return x.AtTime
	}
	return nil
}

type PortfolioValueResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PortfolioId  string                 `protobuf:"bytes,1,opt,name=portfolio_id,json=portfolioId,proto3" json:"portfolio_id,omitempty"`
	QuoteAssetId string                 `protobuf:"bytes,2,opt,name=quote_asset_id,json=quoteAssetId,proto3" json:"quote_asset_id,omitempty"`
	// Monetary value represented by amount and decimals. real_value = amount / (10^decimals)
	TotalValueAmount int64                  `protobuf:"varint,3,opt,name=total_value_amount,json=totalValueAmount,proto3" json:"total_value_amount,omitempty"`
	Decimals         uint32                 `protobuf:"varint,4,opt,name=decimals,proto3" json:"decimals,omitempty"`
	CalculationTime  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=calculation_time,json=calculationTime,proto3" json:"calculation_time,omitempty"` // Could also include breakdown by asset
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PortfolioValueResponse) Reset() {
	*x = PortfolioValueResponse{}
	mi := &file_api_services_portfolio_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioValueResponse) ProtoMessage() {}

func (x *PortfolioValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_portfolio_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioValueResponse.ProtoReflect.Descriptor instead.
func (*PortfolioValueResponse) Descriptor() ([]byte, []int) {
	return file_api_services_portfolio_service_proto_rawDescGZIP(), []int{1}
}

func (x *PortfolioValueResponse) GetPortfolioId() string {
	if x != nil {
		return x.PortfolioId
	}
	return ""
}

func (x *PortfolioValueResponse) GetQuoteAssetId() string {
	if x != nil {
		return x.QuoteAssetId
	}
	return ""
}

func (x *PortfolioValueResponse) GetTotalValueAmount() int64 {
	if x != nil {
		return x.TotalValueAmount
	}
	return 0
}

func (x *PortfolioValueResponse) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *PortfolioValueResponse) GetCalculationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CalculationTime
	}
	return nil
}

type GetPortfolioPerformanceRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PortfolioId      string                 `protobuf:"bytes,1,opt,name=portfolio_id,json=portfolioId,proto3" json:"portfolio_id,omitempty"`
	From             *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To               *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	BenchmarkAssetId string                 `protobuf:"bytes,4,opt,name=benchmark_asset_id,json=benchmarkAssetId,proto3" json:"benchmark_asset_id,omitempty"` // Optional: Asset to compare performance against (e.g., BTC, SPY)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetPortfolioPerformanceRequest) Reset() {
	*x = GetPortfolioPerformanceRequest{}
	mi := &file_api_services_portfolio_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioPerformanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioPerformanceRequest) ProtoMessage() {}

func (x *GetPortfolioPerformanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_portfolio_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioPerformanceRequest.ProtoReflect.Descriptor instead.
func (*GetPortfolioPerformanceRequest) Descriptor() ([]byte, []int) {
	return file_api_services_portfolio_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetPortfolioPerformanceRequest) GetPortfolioId() string {
	if x != nil {
		return x.PortfolioId
	}
	return ""
}

func (x *GetPortfolioPerformanceRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetPortfolioPerformanceRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *GetPortfolioPerformanceRequest) GetBenchmarkAssetId() string {
	if x != nil {
		return x.BenchmarkAssetId
	}
	return ""
}

type PortfolioPerformanceResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	PortfolioId string                 `protobuf:"bytes,1,opt,name=portfolio_id,json=portfolioId,proto3" json:"portfolio_id,omitempty"`
	// Various performance metrics:
	ReturnPercentage float64 `protobuf:"fixed64,2,opt,name=return_percentage,json=returnPercentage,proto3" json:"return_percentage,omitempty"`
	Volatility       float64 `protobuf:"fixed64,3,opt,name=volatility,proto3" json:"volatility,omitempty"`
	SharpeRatio      float64 `protobuf:"fixed64,4,opt,name=sharpe_ratio,json=sharpeRatio,proto3" json:"sharpe_ratio,omitempty"` // Example metric
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PortfolioPerformanceResponse) Reset() {
	*x = PortfolioPerformanceResponse{}
	mi := &file_api_services_portfolio_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioPerformanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioPerformanceResponse) ProtoMessage() {}

func (x *PortfolioPerformanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_portfolio_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioPerformanceResponse.ProtoReflect.Descriptor instead.
func (*PortfolioPerformanceResponse) Descriptor() ([]byte, []int) {
	return file_api_services_portfolio_service_proto_rawDescGZIP(), []int{3}
}

func (x *PortfolioPerformanceResponse) GetPortfolioId() string {
	if x != nil {
		return x.PortfolioId
	}
	return ""
}

func (x *PortfolioPerformanceResponse) GetReturnPercentage() float64 {
	if x != nil {
		return x.ReturnPercentage
	}
	return 0
}

func (x *PortfolioPerformanceResponse) GetVolatility() float64 {
	if x != nil {
		return x.Volatility
	}
	return 0
}

func (x *PortfolioPerformanceResponse) GetSharpeRatio() float64 {
	if x != nil {
		return x.SharpeRatio
	}
	return 0
}

var File_api_services_portfolio_service_proto protoreflect.FileDescriptor

const file_api_services_portfolio_service_proto_rawDesc = "" +
	"\n" +
	"$api/services/portfolio_service.proto\x12\bservices\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\x9e\x01\n" +
	"\x1eCalculatePortfolioValueRequest\x12!\n" +
	"\fportfolio_id\x18\x01 \x01(\tR\vportfolioId\x12$\n" +
	"\x0equote_asset_id\x18\x02 \x01(\tR\fquoteAssetId\x123\n" +
	"\aat_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06atTime\"\xf2\x01\n" +
	"\x16PortfolioValueResponse\x12!\n" +
	"\fportfolio_id\x18\x01 \x01(\tR\vportfolioId\x12$\n" +
	"\x0equote_asset_id\x18\x02 \x01(\tR\fquoteAssetId\x12,\n" +
	"\x12total_value_amount\x18\x03 \x01(\x03R\x10totalValueAmount\x12\x1a\n" +
	"\bdecimals\x18\x04 \x01(\rR\bdecimals\x12E\n" +
	"\x10calculation_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0fcalculationTime\"\xcd\x01\n" +
	"\x1eGetPortfolioPerformanceRequest\x12!\n" +
	"\fportfolio_id\x18\x01 \x01(\tR\vportfolioId\x12.\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12,\n" +
	"\x12benchmark_asset_id\x18\x04 \x01(\tR\x10benchmarkAssetId\"\xb1\x01\n" +
	"\x1cPortfolioPerformanceResponse\x12!\n" +
	"\fportfolio_id\x18\x01 \x01(\tR\vportfolioId\x12+\n" +
	"\x11return_percentage\x18\x02 \x01(\x01R\x10returnPercentage\x12\x1e\n" +
	"\n" +
	"volatility\x18\x03 \x01(\x01R\n" +
	"volatility\x12!\n" +
	"\fsharpe_ratio\x18\x04 \x01(\x01R\vsharpeRatio2\xe0\x02\n" +
	"\x10PortfolioService\x12\xa3\x01\n" +
	"\x17CalculatePortfolioValue\x12(.services.CalculatePortfolioValueRequest\x1a .services.PortfolioValueResponse\"<\x82\xd3\xe4\x93\x026:\x01*\"1/api/v1/portfolios/{portfolio_id}/calculate-value\x12\xa5\x01\n" +
	"\x17GetPortfolioPerformance\x12(.services.GetPortfolioPerformanceRequest\x1a&.services.PortfolioPerformanceResponse\"8\x82\xd3\xe4\x93\x022:\x01*\"-/api/v1/portfolios/{portfolio_id}/performanceB\x9a\x01\n" +
	"\fcom.servicesB\x15PortfolioServiceProtoP\x01Z3github.com/foxcool/greedy-eye/internal/api/services\xa2\x02\x03SXX\xaa\x02\bServices\xca\x02\bServices\xe2\x02\x14Services\\GPBMetadata\xea\x02\bServicesb\x06proto3"

var (
	file_api_services_portfolio_service_proto_rawDescOnce sync.Once
	file_api_services_portfolio_service_proto_rawDescData []byte
)

func file_api_services_portfolio_service_proto_rawDescGZIP() []byte {
	file_api_services_portfolio_service_proto_rawDescOnce.Do(func() {
		file_api_services_portfolio_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_services_portfolio_service_proto_rawDesc), len(file_api_services_portfolio_service_proto_rawDesc)))
	})
	return file_api_services_portfolio_service_proto_rawDescData
}

var file_api_services_portfolio_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_services_portfolio_service_proto_goTypes = []any{
	(*CalculatePortfolioValueRequest)(nil), // 0: services.CalculatePortfolioValueRequest
	(*PortfolioValueResponse)(nil),         // 1: services.PortfolioValueResponse
	(*GetPortfolioPerformanceRequest)(nil), // 2: services.GetPortfolioPerformanceRequest
	(*PortfolioPerformanceResponse)(nil),   // 3: services.PortfolioPerformanceResponse
	(*timestamppb.Timestamp)(nil),          // 4: google.protobuf.Timestamp
}
var file_api_services_portfolio_service_proto_depIdxs = []int32{
	4, // 0: services.CalculatePortfolioValueRequest.at_time:type_name -> google.protobuf.Timestamp
	4, // 1: services.PortfolioValueResponse.calculation_time:type_name -> google.protobuf.Timestamp
	4, // 2: services.GetPortfolioPerformanceRequest.from:type_name -> google.protobuf.Timestamp
	4, // 3: services.GetPortfolioPerformanceRequest.to:type_name -> google.protobuf.Timestamp
	0, // 4: services.PortfolioService.CalculatePortfolioValue:input_type -> services.CalculatePortfolioValueRequest
	2, // 5: services.PortfolioService.GetPortfolioPerformance:input_type -> services.GetPortfolioPerformanceRequest
	1, // 6: services.PortfolioService.CalculatePortfolioValue:output_type -> services.PortfolioValueResponse
	3, // 7: services.PortfolioService.GetPortfolioPerformance:output_type -> services.PortfolioPerformanceResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_services_portfolio_service_proto_init() }
func file_api_services_portfolio_service_proto_init() {
	if File_api_services_portfolio_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_services_portfolio_service_proto_rawDesc), len(file_api_services_portfolio_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_services_portfolio_service_proto_goTypes,
		DependencyIndexes: file_api_services_portfolio_service_proto_depIdxs,
		MessageInfos:      file_api_services_portfolio_service_proto_msgTypes,
	}.Build()
	File_api_services_portfolio_service_proto = out.File
	file_api_services_portfolio_service_proto_goTypes = nil
	file_api_services_portfolio_service_proto_depIdxs = nil
}
