// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/marketdata.proto

package apiv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetType int32

const (
	AssetType_ASSET_TYPE_UNSPECIFIED    AssetType = 0
	AssetType_ASSET_TYPE_CRYPTOCURRENCY AssetType = 1
	AssetType_ASSET_TYPE_STOCK          AssetType = 2
	AssetType_ASSET_TYPE_BOND           AssetType = 3
	AssetType_ASSET_TYPE_COMMODITY      AssetType = 4
	AssetType_ASSET_TYPE_FOREX          AssetType = 5
	AssetType_ASSET_TYPE_FUND           AssetType = 6
)

// Enum value maps for AssetType.
var (
	AssetType_name = map[int32]string{
		0: "ASSET_TYPE_UNSPECIFIED",
		1: "ASSET_TYPE_CRYPTOCURRENCY",
		2: "ASSET_TYPE_STOCK",
		3: "ASSET_TYPE_BOND",
		4: "ASSET_TYPE_COMMODITY",
		5: "ASSET_TYPE_FOREX",
		6: "ASSET_TYPE_FUND",
	}
	AssetType_value = map[string]int32{
		"ASSET_TYPE_UNSPECIFIED":    0,
		"ASSET_TYPE_CRYPTOCURRENCY": 1,
		"ASSET_TYPE_STOCK":          2,
		"ASSET_TYPE_BOND":           3,
		"ASSET_TYPE_COMMODITY":      4,
		"ASSET_TYPE_FOREX":          5,
		"ASSET_TYPE_FUND":           6,
	}
)

func (x AssetType) Enum() *AssetType {
	p := new(AssetType)
	*p = x
	return p
}

func (x AssetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_marketdata_proto_enumTypes[0].Descriptor()
}

func (AssetType) Type() protoreflect.EnumType {
	return &file_v1_marketdata_proto_enumTypes[0]
}

func (x AssetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetType.Descriptor instead.
func (AssetType) EnumDescriptor() ([]byte, []int) {
	return file_v1_marketdata_proto_rawDescGZIP(), []int{0}
}

// Asset represents financial instrument (crypto, stock, etc.).
type Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          AssetType              `protobuf:"varint,3,opt,name=type,proto3,enum=greedy_eye.v1.AssetType" json:"type,omitempty"`
	Symbol        *string                `protobuf:"bytes,4,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_v1_marketdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marketdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_v1_marketdata_proto_rawDescGZIP(), []int{0}
}

func (x *Asset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Asset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Asset) GetType() AssetType {
	if x != nil {
		return x.Type
	}
	return AssetType_ASSET_TYPE_UNSPECIFIED
}

func (x *Asset) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *Asset) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Asset) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Asset) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Price represents the price action of an Asset against a base Asset
// over a specific interval (candle/OHLCV) or as a latest snapshot.
type Price struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceId    string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`            // Identifier for the source (e.g., "coingecko", "binance")
	AssetId     string                 `protobuf:"bytes,3,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`               // ID of the Asset whose price is represented
	BaseAssetId string                 `protobuf:"bytes,4,opt,name=base_asset_id,json=baseAssetId,proto3" json:"base_asset_id,omitempty"` // ID of the Asset against which the price is quoted
	// Interval defines the time period this price data represents.
	// Examples: "1m", "5m", "1h", "4h", "1d", "tick", "latest".
	Interval string `protobuf:"bytes,5,opt,name=interval,proto3" json:"interval,omitempty"`
	Decimals uint32 `protobuf:"varint,6,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Last     int64  `protobuf:"varint,7,opt,name=last,proto3" json:"last,omitempty"`
	// OHLCV data - applicable when 'interval' represents a standard candle type.
	Open          *int64                 `protobuf:"varint,8,opt,name=open,proto3,oneof" json:"open,omitempty"`
	High          *int64                 `protobuf:"varint,9,opt,name=high,proto3,oneof" json:"high,omitempty"`
	Low           *int64                 `protobuf:"varint,10,opt,name=low,proto3,oneof" json:"low,omitempty"`
	Close         *int64                 `protobuf:"varint,11,opt,name=close,proto3,oneof" json:"close,omitempty"`
	Volume        *int64                 `protobuf:"varint,12,opt,name=volume,proto3,oneof" json:"volume,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Price) Reset() {
	*x = Price{}
	mi := &file_v1_marketdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Price) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Price) ProtoMessage() {}

func (x *Price) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marketdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Price.ProtoReflect.Descriptor instead.
func (*Price) Descriptor() ([]byte, []int) {
	return file_v1_marketdata_proto_rawDescGZIP(), []int{1}
}

func (x *Price) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Price) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Price) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *Price) GetBaseAssetId() string {
	if x != nil {
		return x.BaseAssetId
	}
	return ""
}

func (x *Price) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *Price) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *Price) GetLast() int64 {
	if x != nil {
		return x.Last
	}
	return 0
}

func (x *Price) GetOpen() int64 {
	if x != nil && x.Open != nil {
		return *x.Open
	}
	return 0
}

func (x *Price) GetHigh() int64 {
	if x != nil && x.High != nil {
		return *x.High
	}
	return 0
}

func (x *Price) GetLow() int64 {
	if x != nil && x.Low != nil {
		return *x.Low
	}
	return 0
}

func (x *Price) GetClose() int64 {
	if x != nil && x.Close != nil {
		return *x.Close
	}
	return 0
}

func (x *Price) GetVolume() int64 {
	if x != nil && x.Volume != nil {
		return *x.Volume
	}
	return 0
}

func (x *Price) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type CreateAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssetRequest) Reset() {
	*x = CreateAssetRequest{}
	mi := &file_v1_marketdata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssetRequest) ProtoMessage() {}

func (x *CreateAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marketdata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssetRequest.ProtoReflect.Descriptor instead.
func (*CreateAssetRequest) Descriptor() ([]byte, []int) {
	return file_v1_marketdata_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAssetRequest) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

type GetAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetRequest) Reset() {
	*x = GetAssetRequest{}
	mi := &file_v1_marketdata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetRequest) ProtoMessage() {}

func (x *GetAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marketdata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetRequest.ProtoReflect.Descriptor instead.
func (*GetAssetRequest) Descriptor() ([]byte, []int) {
	return file_v1_marketdata_proto_rawDescGZIP(), []int{3}
}

func (x *GetAssetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAssetRequest) Reset() {
	*x = UpdateAssetRequest{}
	mi := &file_v1_marketdata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssetRequest) ProtoMessage() {}

func (x *UpdateAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marketdata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssetRequest.ProtoReflect.Descriptor instead.
func (*UpdateAssetRequest) Descriptor() ([]byte, []int) {
	return file_v1_marketdata_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAssetRequest) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *UpdateAssetRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssetRequest) Reset() {
	*x = DeleteAssetRequest{}
	mi := &file_v1_marketdata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssetRequest) ProtoMessage() {}

func (x *DeleteAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marketdata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssetRequest.ProtoReflect.Descriptor instead.
func (*DeleteAssetRequest) Descriptor() ([]byte, []int) {
	return file_v1_marketdata_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteAssetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      *int32                 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	PageToken     *string                `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsRequest) Reset() {
	*x = ListAssetsRequest{}
	mi := &file_v1_marketdata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsRequest) ProtoMessage() {}

func (x *ListAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marketdata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsRequest.ProtoReflect.Descriptor instead.
func (*ListAssetsRequest) Descriptor() ([]byte, []int) {
	return file_v1_marketdata_proto_rawDescGZIP(), []int{6}
}

func (x *ListAssetsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListAssetsRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

func (x *ListAssetsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ListAssetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*Asset               `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsResponse) Reset() {
	*x = ListAssetsResponse{}
	mi := &file_v1_marketdata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsResponse) ProtoMessage() {}

func (x *ListAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marketdata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsResponse.ProtoReflect.Descriptor instead.
func (*ListAssetsResponse) Descriptor() ([]byte, []int) {
	return file_v1_marketdata_proto_rawDescGZIP(), []int{7}
}

func (x *ListAssetsResponse) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *ListAssetsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type EnrichAssetDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Sources       []string               `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichAssetDataRequest) Reset() {
	*x = EnrichAssetDataRequest{}
	mi := &file_v1_marketdata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichAssetDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichAssetDataRequest) ProtoMessage() {}

func (x *EnrichAssetDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marketdata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichAssetDataRequest.ProtoReflect.Descriptor instead.
func (*EnrichAssetDataRequest) Descriptor() ([]byte, []int) {
	return file_v1_marketdata_proto_rawDescGZIP(), []int{8}
}

func (x *EnrichAssetDataRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *EnrichAssetDataRequest) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

type FindSimilarAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSimilarAssetsRequest) Reset() {
	*x = FindSimilarAssetsRequest{}
	mi := &file_v1_marketdata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSimilarAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSimilarAssetsRequest) ProtoMessage() {}

func (x *FindSimilarAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marketdata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSimilarAssetsRequest.ProtoReflect.Descriptor instead.
func (*FindSimilarAssetsRequest) Descriptor() ([]byte, []int) {
	return file_v1_marketdata_proto_rawDescGZIP(), []int{9}
}

func (x *FindSimilarAssetsRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *FindSimilarAssetsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CreatePriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         *Price                 `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePriceRequest) Reset() {
	*x = CreatePriceRequest{}
	mi := &file_v1_marketdata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePriceRequest) ProtoMessage() {}

func (x *CreatePriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marketdata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePriceRequest.ProtoReflect.Descriptor instead.
func (*CreatePriceRequest) Descriptor() ([]byte, []int) {
	return file_v1_marketdata_proto_rawDescGZIP(), []int{10}
}

func (x *CreatePriceRequest) GetPrice() *Price {
	if x != nil {
		return x.Price
	}
	return nil
}

type CreatePricesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prices        []*Price               `protobuf:"bytes,1,rep,name=prices,proto3" json:"prices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePricesRequest) Reset() {
	*x = CreatePricesRequest{}
	mi := &file_v1_marketdata_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePricesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePricesRequest) ProtoMessage() {}

func (x *CreatePricesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marketdata_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePricesRequest.ProtoReflect.Descriptor instead.
func (*CreatePricesRequest) Descriptor() ([]byte, []int) {
	return file_v1_marketdata_proto_rawDescGZIP(), []int{11}
}

func (x *CreatePricesRequest) GetPrices() []*Price {
	if x != nil {
		return x.Prices
	}
	return nil
}

type CreatePricesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedCount  int32                  `protobuf:"varint,1,opt,name=created_count,json=createdCount,proto3" json:"created_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePricesResponse) Reset() {
	*x = CreatePricesResponse{}
	mi := &file_v1_marketdata_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePricesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePricesResponse) ProtoMessage() {}

func (x *CreatePricesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marketdata_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePricesResponse.ProtoReflect.Descriptor instead.
func (*CreatePricesResponse) Descriptor() ([]byte, []int) {
	return file_v1_marketdata_proto_rawDescGZIP(), []int{12}
}

func (x *CreatePricesResponse) GetCreatedCount() int32 {
	if x != nil {
		return x.CreatedCount
	}
	return 0
}

type GetLatestPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	BaseAssetId   string                 `protobuf:"bytes,2,opt,name=base_asset_id,json=baseAssetId,proto3" json:"base_asset_id,omitempty"`
	SourceId      *string                `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3,oneof" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestPriceRequest) Reset() {
	*x = GetLatestPriceRequest{}
	mi := &file_v1_marketdata_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestPriceRequest) ProtoMessage() {}

func (x *GetLatestPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marketdata_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestPriceRequest.ProtoReflect.Descriptor instead.
func (*GetLatestPriceRequest) Descriptor() ([]byte, []int) {
	return file_v1_marketdata_proto_rawDescGZIP(), []int{13}
}

func (x *GetLatestPriceRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *GetLatestPriceRequest) GetBaseAssetId() string {
	if x != nil {
		return x.BaseAssetId
	}
	return ""
}

func (x *GetLatestPriceRequest) GetSourceId() string {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return ""
}

type ListPriceHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	BaseAssetId   string                 `protobuf:"bytes,2,opt,name=base_asset_id,json=baseAssetId,proto3" json:"base_asset_id,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=from,proto3,oneof" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=to,proto3,oneof" json:"to,omitempty"`
	SourceId      *string                `protobuf:"bytes,5,opt,name=source_id,json=sourceId,proto3,oneof" json:"source_id,omitempty"`
	PageSize      *int32                 `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	PageToken     *string                `protobuf:"bytes,7,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPriceHistoryRequest) Reset() {
	*x = ListPriceHistoryRequest{}
	mi := &file_v1_marketdata_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPriceHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPriceHistoryRequest) ProtoMessage() {}

func (x *ListPriceHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marketdata_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPriceHistoryRequest.ProtoReflect.Descriptor instead.
func (*ListPriceHistoryRequest) Descriptor() ([]byte, []int) {
	return file_v1_marketdata_proto_rawDescGZIP(), []int{14}
}

func (x *ListPriceHistoryRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *ListPriceHistoryRequest) GetBaseAssetId() string {
	if x != nil {
		return x.BaseAssetId
	}
	return ""
}

func (x *ListPriceHistoryRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ListPriceHistoryRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ListPriceHistoryRequest) GetSourceId() string {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return ""
}

func (x *ListPriceHistoryRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListPriceHistoryRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type ListPriceHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prices        []*Price               `protobuf:"bytes,1,rep,name=prices,proto3" json:"prices,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPriceHistoryResponse) Reset() {
	*x = ListPriceHistoryResponse{}
	mi := &file_v1_marketdata_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPriceHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPriceHistoryResponse) ProtoMessage() {}

func (x *ListPriceHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marketdata_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPriceHistoryResponse.ProtoReflect.Descriptor instead.
func (*ListPriceHistoryResponse) Descriptor() ([]byte, []int) {
	return file_v1_marketdata_proto_rawDescGZIP(), []int{15}
}

func (x *ListPriceHistoryResponse) GetPrices() []*Price {
	if x != nil {
		return x.Prices
	}
	return nil
}

func (x *ListPriceHistoryResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListPricesByIntervalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	BaseAssetId   string                 `protobuf:"bytes,2,opt,name=base_asset_id,json=baseAssetId,proto3" json:"base_asset_id,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=from,proto3,oneof" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=to,proto3,oneof" json:"to,omitempty"`
	Interval      string                 `protobuf:"bytes,5,opt,name=interval,proto3" json:"interval,omitempty"`
	SourceId      *string                `protobuf:"bytes,6,opt,name=source_id,json=sourceId,proto3,oneof" json:"source_id,omitempty"`
	PageSize      *int32                 `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	PageToken     *string                `protobuf:"bytes,8,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPricesByIntervalRequest) Reset() {
	*x = ListPricesByIntervalRequest{}
	mi := &file_v1_marketdata_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPricesByIntervalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPricesByIntervalRequest) ProtoMessage() {}

func (x *ListPricesByIntervalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marketdata_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPricesByIntervalRequest.ProtoReflect.Descriptor instead.
func (*ListPricesByIntervalRequest) Descriptor() ([]byte, []int) {
	return file_v1_marketdata_proto_rawDescGZIP(), []int{16}
}

func (x *ListPricesByIntervalRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *ListPricesByIntervalRequest) GetBaseAssetId() string {
	if x != nil {
		return x.BaseAssetId
	}
	return ""
}

func (x *ListPricesByIntervalRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ListPricesByIntervalRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ListPricesByIntervalRequest) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *ListPricesByIntervalRequest) GetSourceId() string {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return ""
}

func (x *ListPricesByIntervalRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListPricesByIntervalRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type DeletePriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePriceRequest) Reset() {
	*x = DeletePriceRequest{}
	mi := &file_v1_marketdata_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePriceRequest) ProtoMessage() {}

func (x *DeletePriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marketdata_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePriceRequest.ProtoReflect.Descriptor instead.
func (*DeletePriceRequest) Descriptor() ([]byte, []int) {
	return file_v1_marketdata_proto_rawDescGZIP(), []int{17}
}

func (x *DeletePriceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePricesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       *string                `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3,oneof" json:"asset_id,omitempty"`
	BaseAssetId   *string                `protobuf:"bytes,2,opt,name=base_asset_id,json=baseAssetId,proto3,oneof" json:"base_asset_id,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=from,proto3,oneof" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=to,proto3,oneof" json:"to,omitempty"`
	SourceId      *string                `protobuf:"bytes,5,opt,name=source_id,json=sourceId,proto3,oneof" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePricesRequest) Reset() {
	*x = DeletePricesRequest{}
	mi := &file_v1_marketdata_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePricesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePricesRequest) ProtoMessage() {}

func (x *DeletePricesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marketdata_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePricesRequest.ProtoReflect.Descriptor instead.
func (*DeletePricesRequest) Descriptor() ([]byte, []int) {
	return file_v1_marketdata_proto_rawDescGZIP(), []int{18}
}

func (x *DeletePricesRequest) GetAssetId() string {
	if x != nil && x.AssetId != nil {
		return *x.AssetId
	}
	return ""
}

func (x *DeletePricesRequest) GetBaseAssetId() string {
	if x != nil && x.BaseAssetId != nil {
		return *x.BaseAssetId
	}
	return ""
}

func (x *DeletePricesRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *DeletePricesRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *DeletePricesRequest) GetSourceId() string {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return ""
}

type FetchExternalPricesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceIds     []string               `protobuf:"bytes,1,rep,name=source_ids,json=sourceIds,proto3" json:"source_ids,omitempty"`
	AssetIds      []string               `protobuf:"bytes,2,rep,name=asset_ids,json=assetIds,proto3" json:"asset_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchExternalPricesRequest) Reset() {
	*x = FetchExternalPricesRequest{}
	mi := &file_v1_marketdata_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchExternalPricesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchExternalPricesRequest) ProtoMessage() {}

func (x *FetchExternalPricesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marketdata_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchExternalPricesRequest.ProtoReflect.Descriptor instead.
func (*FetchExternalPricesRequest) Descriptor() ([]byte, []int) {
	return file_v1_marketdata_proto_rawDescGZIP(), []int{19}
}

func (x *FetchExternalPricesRequest) GetSourceIds() []string {
	if x != nil {
		return x.SourceIds
	}
	return nil
}

func (x *FetchExternalPricesRequest) GetAssetIds() []string {
	if x != nil {
		return x.AssetIds
	}
	return nil
}

type FetchExternalPricesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PricesFetched int32                  `protobuf:"varint,1,opt,name=prices_fetched,json=pricesFetched,proto3" json:"prices_fetched,omitempty"`
	PricesStored  int32                  `protobuf:"varint,2,opt,name=prices_stored,json=pricesStored,proto3" json:"prices_stored,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchExternalPricesResponse) Reset() {
	*x = FetchExternalPricesResponse{}
	mi := &file_v1_marketdata_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchExternalPricesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchExternalPricesResponse) ProtoMessage() {}

func (x *FetchExternalPricesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_marketdata_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchExternalPricesResponse.ProtoReflect.Descriptor instead.
func (*FetchExternalPricesResponse) Descriptor() ([]byte, []int) {
	return file_v1_marketdata_proto_rawDescGZIP(), []int{20}
}

func (x *FetchExternalPricesResponse) GetPricesFetched() int32 {
	if x != nil {
		return x.PricesFetched
	}
	return 0
}

func (x *FetchExternalPricesResponse) GetPricesStored() int32 {
	if x != nil {
		return x.PricesStored
	}
	return 0
}

func (x *FetchExternalPricesResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_v1_marketdata_proto protoreflect.FileDescriptor

const file_v1_marketdata_proto_rawDesc = "" +
	"\n" +
	"\x13v1/marketdata.proto\x12\rgreedy_eye.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/api/annotations.proto\"\x8b\x02\n" +
	"\x05Asset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x18.greedy_eye.v1.AssetTypeR\x04type\x12\x1b\n" +
	"\x06symbol\x18\x04 \x01(\tH\x00R\x06symbol\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\t\n" +
	"\a_symbol\"\xa9\x03\n" +
	"\x05Price\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x19\n" +
	"\basset_id\x18\x03 \x01(\tR\aassetId\x12\"\n" +
	"\rbase_asset_id\x18\x04 \x01(\tR\vbaseAssetId\x12\x1a\n" +
	"\binterval\x18\x05 \x01(\tR\binterval\x12\x1a\n" +
	"\bdecimals\x18\x06 \x01(\rR\bdecimals\x12\x12\n" +
	"\x04last\x18\a \x01(\x03R\x04last\x12\x17\n" +
	"\x04open\x18\b \x01(\x03H\x00R\x04open\x88\x01\x01\x12\x17\n" +
	"\x04high\x18\t \x01(\x03H\x01R\x04high\x88\x01\x01\x12\x15\n" +
	"\x03low\x18\n" +
	" \x01(\x03H\x02R\x03low\x88\x01\x01\x12\x19\n" +
	"\x05close\x18\v \x01(\x03H\x03R\x05close\x88\x01\x01\x12\x1b\n" +
	"\x06volume\x18\f \x01(\x03H\x04R\x06volume\x88\x01\x01\x128\n" +
	"\ttimestamp\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB\a\n" +
	"\x05_openB\a\n" +
	"\x05_highB\x06\n" +
	"\x04_lowB\b\n" +
	"\x06_closeB\t\n" +
	"\a_volume\"@\n" +
	"\x12CreateAssetRequest\x12*\n" +
	"\x05asset\x18\x01 \x01(\v2\x14.greedy_eye.v1.AssetR\x05asset\"!\n" +
	"\x0fGetAssetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"}\n" +
	"\x12UpdateAssetRequest\x12*\n" +
	"\x05asset\x18\x01 \x01(\v2\x14.greedy_eye.v1.AssetR\x05asset\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"$\n" +
	"\x12DeleteAssetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8a\x01\n" +
	"\x11ListAssetsRequest\x12 \n" +
	"\tpage_size\x18\x01 \x01(\x05H\x00R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tH\x01R\tpageToken\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tagsB\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"j\n" +
	"\x12ListAssetsResponse\x12,\n" +
	"\x06assets\x18\x01 \x03(\v2\x14.greedy_eye.v1.AssetR\x06assets\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"M\n" +
	"\x16EnrichAssetDataRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x18\n" +
	"\asources\x18\x02 \x03(\tR\asources\"K\n" +
	"\x18FindSimilarAssetsRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"@\n" +
	"\x12CreatePriceRequest\x12*\n" +
	"\x05price\x18\x01 \x01(\v2\x14.greedy_eye.v1.PriceR\x05price\"C\n" +
	"\x13CreatePricesRequest\x12,\n" +
	"\x06prices\x18\x01 \x03(\v2\x14.greedy_eye.v1.PriceR\x06prices\";\n" +
	"\x14CreatePricesResponse\x12#\n" +
	"\rcreated_count\x18\x01 \x01(\x05R\fcreatedCount\"\x86\x01\n" +
	"\x15GetLatestPriceRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\"\n" +
	"\rbase_asset_id\x18\x02 \x01(\tR\vbaseAssetId\x12 \n" +
	"\tsource_id\x18\x03 \x01(\tH\x00R\bsourceId\x88\x01\x01B\f\n" +
	"\n" +
	"_source_id\"\xe1\x02\n" +
	"\x17ListPriceHistoryRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\"\n" +
	"\rbase_asset_id\x18\x02 \x01(\tR\vbaseAssetId\x123\n" +
	"\x04from\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x04from\x88\x01\x01\x12/\n" +
	"\x02to\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x02to\x88\x01\x01\x12 \n" +
	"\tsource_id\x18\x05 \x01(\tH\x02R\bsourceId\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x06 \x01(\x05H\x03R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\a \x01(\tH\x04R\tpageToken\x88\x01\x01B\a\n" +
	"\x05_fromB\x05\n" +
	"\x03_toB\f\n" +
	"\n" +
	"_source_idB\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"p\n" +
	"\x18ListPriceHistoryResponse\x12,\n" +
	"\x06prices\x18\x01 \x03(\v2\x14.greedy_eye.v1.PriceR\x06prices\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x81\x03\n" +
	"\x1bListPricesByIntervalRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\"\n" +
	"\rbase_asset_id\x18\x02 \x01(\tR\vbaseAssetId\x123\n" +
	"\x04from\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x04from\x88\x01\x01\x12/\n" +
	"\x02to\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x02to\x88\x01\x01\x12\x1a\n" +
	"\binterval\x18\x05 \x01(\tR\binterval\x12 \n" +
	"\tsource_id\x18\x06 \x01(\tH\x02R\bsourceId\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\a \x01(\x05H\x03R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\b \x01(\tH\x04R\tpageToken\x88\x01\x01B\a\n" +
	"\x05_fromB\x05\n" +
	"\x03_toB\f\n" +
	"\n" +
	"_source_idB\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"$\n" +
	"\x12DeletePriceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa3\x02\n" +
	"\x13DeletePricesRequest\x12\x1e\n" +
	"\basset_id\x18\x01 \x01(\tH\x00R\aassetId\x88\x01\x01\x12'\n" +
	"\rbase_asset_id\x18\x02 \x01(\tH\x01R\vbaseAssetId\x88\x01\x01\x123\n" +
	"\x04from\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x04from\x88\x01\x01\x12/\n" +
	"\x02to\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\x02to\x88\x01\x01\x12 \n" +
	"\tsource_id\x18\x05 \x01(\tH\x04R\bsourceId\x88\x01\x01B\v\n" +
	"\t_asset_idB\x10\n" +
	"\x0e_base_asset_idB\a\n" +
	"\x05_fromB\x05\n" +
	"\x03_toB\f\n" +
	"\n" +
	"_source_id\"X\n" +
	"\x1aFetchExternalPricesRequest\x12\x1d\n" +
	"\n" +
	"source_ids\x18\x01 \x03(\tR\tsourceIds\x12\x1b\n" +
	"\tasset_ids\x18\x02 \x03(\tR\bassetIds\"\x81\x01\n" +
	"\x1bFetchExternalPricesResponse\x12%\n" +
	"\x0eprices_fetched\x18\x01 \x01(\x05R\rpricesFetched\x12#\n" +
	"\rprices_stored\x18\x02 \x01(\x05R\fpricesStored\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors*\xb6\x01\n" +
	"\tAssetType\x12\x1a\n" +
	"\x16ASSET_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19ASSET_TYPE_CRYPTOCURRENCY\x10\x01\x12\x14\n" +
	"\x10ASSET_TYPE_STOCK\x10\x02\x12\x13\n" +
	"\x0fASSET_TYPE_BOND\x10\x03\x12\x18\n" +
	"\x14ASSET_TYPE_COMMODITY\x10\x04\x12\x14\n" +
	"\x10ASSET_TYPE_FOREX\x10\x05\x12\x13\n" +
	"\x0fASSET_TYPE_FUND\x10\x062\xc5\x0e\n" +
	"\x11MarketDataService\x12e\n" +
	"\vCreateAsset\x12!.greedy_eye.v1.CreateAssetRequest\x1a\x14.greedy_eye.v1.Asset\"\x1d\x82\xd3\xe4\x93\x02\x17:\x05asset\"\x0e/api/v1/assets\x12]\n" +
	"\bGetAsset\x12\x1e.greedy_eye.v1.GetAssetRequest\x1a\x14.greedy_eye.v1.Asset\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/assets/{id}\x12p\n" +
	"\vUpdateAsset\x12!.greedy_eye.v1.UpdateAssetRequest\x1a\x14.greedy_eye.v1.Asset\"(\x82\xd3\xe4\x93\x02\":\x05asset\x1a\x19/api/v1/assets/{asset.id}\x12e\n" +
	"\vDeleteAsset\x12!.greedy_eye.v1.DeleteAssetRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/api/v1/assets/{id}\x12i\n" +
	"\n" +
	"ListAssets\x12 .greedy_eye.v1.ListAssetsRequest\x1a!.greedy_eye.v1.ListAssetsResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/assets\x12{\n" +
	"\x0fEnrichAssetData\x12%.greedy_eye.v1.EnrichAssetDataRequest\x1a\x14.greedy_eye.v1.Asset\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/v1/assets/{asset_id}/enrich\x12\x8a\x01\n" +
	"\x11FindSimilarAssets\x12'.greedy_eye.v1.FindSimilarAssetsRequest\x1a!.greedy_eye.v1.ListAssetsResponse\")\x82\xd3\xe4\x93\x02#\x12!/api/v1/assets/{asset_id}/similar\x12e\n" +
	"\vCreatePrice\x12!.greedy_eye.v1.CreatePriceRequest\x1a\x14.greedy_eye.v1.Price\"\x1d\x82\xd3\xe4\x93\x02\x17:\x05price\"\x0e/api/v1/prices\x12|\n" +
	"\fCreatePrices\x12\".greedy_eye.v1.CreatePricesRequest\x1a#.greedy_eye.v1.CreatePricesResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x06prices\"\x13/api/v1/prices/bulk\x12\x86\x01\n" +
	"\x0eGetLatestPrice\x12$.greedy_eye.v1.GetLatestPriceRequest\x1a\x14.greedy_eye.v1.Price\"8\x82\xd3\xe4\x93\x022\x120/api/v1/prices/{asset_id}/{base_asset_id}/latest\x12\x9e\x01\n" +
	"\x10ListPriceHistory\x12&.greedy_eye.v1.ListPriceHistoryRequest\x1a'.greedy_eye.v1.ListPriceHistoryResponse\"9\x82\xd3\xe4\x93\x023\x121/api/v1/prices/{asset_id}/{base_asset_id}/history\x12\xa8\x01\n" +
	"\x14ListPricesByInterval\x12*.greedy_eye.v1.ListPricesByIntervalRequest\x1a'.greedy_eye.v1.ListPriceHistoryResponse\";\x82\xd3\xe4\x93\x025\x123/api/v1/prices/{asset_id}/{base_asset_id}/intervals\x12e\n" +
	"\vDeletePrice\x12!.greedy_eye.v1.DeletePriceRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/api/v1/prices/{id}\x12b\n" +
	"\fDeletePrices\x12\".greedy_eye.v1.DeletePricesRequest\x1a\x16.google.protobuf.Empty\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/api/v1/prices\x12\x96\x01\n" +
	"\x13FetchExternalPrices\x12).greedy_eye.v1.FetchExternalPricesRequest\x1a*.greedy_eye.v1.FetchExternalPricesResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/prices/fetch-externalB\xaa\x01\n" +
	"\x11com.greedy_eye.v1B\x0fMarketdataProtoP\x01Z3github.com/foxcool/greedy-eye/internal/api/v1;apiv1\xa2\x02\x03GXX\xaa\x02\fGreedyEye.V1\xca\x02\fGreedyEye\\V1\xe2\x02\x18GreedyEye\\V1\\GPBMetadata\xea\x02\rGreedyEye::V1b\x06proto3"

var (
	file_v1_marketdata_proto_rawDescOnce sync.Once
	file_v1_marketdata_proto_rawDescData []byte
)

func file_v1_marketdata_proto_rawDescGZIP() []byte {
	file_v1_marketdata_proto_rawDescOnce.Do(func() {
		file_v1_marketdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_marketdata_proto_rawDesc), len(file_v1_marketdata_proto_rawDesc)))
	})
	return file_v1_marketdata_proto_rawDescData
}

var file_v1_marketdata_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_marketdata_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_v1_marketdata_proto_goTypes = []any{
	(AssetType)(0),                      // 0: greedy_eye.v1.AssetType
	(*Asset)(nil),                       // 1: greedy_eye.v1.Asset
	(*Price)(nil),                       // 2: greedy_eye.v1.Price
	(*CreateAssetRequest)(nil),          // 3: greedy_eye.v1.CreateAssetRequest
	(*GetAssetRequest)(nil),             // 4: greedy_eye.v1.GetAssetRequest
	(*UpdateAssetRequest)(nil),          // 5: greedy_eye.v1.UpdateAssetRequest
	(*DeleteAssetRequest)(nil),          // 6: greedy_eye.v1.DeleteAssetRequest
	(*ListAssetsRequest)(nil),           // 7: greedy_eye.v1.ListAssetsRequest
	(*ListAssetsResponse)(nil),          // 8: greedy_eye.v1.ListAssetsResponse
	(*EnrichAssetDataRequest)(nil),      // 9: greedy_eye.v1.EnrichAssetDataRequest
	(*FindSimilarAssetsRequest)(nil),    // 10: greedy_eye.v1.FindSimilarAssetsRequest
	(*CreatePriceRequest)(nil),          // 11: greedy_eye.v1.CreatePriceRequest
	(*CreatePricesRequest)(nil),         // 12: greedy_eye.v1.CreatePricesRequest
	(*CreatePricesResponse)(nil),        // 13: greedy_eye.v1.CreatePricesResponse
	(*GetLatestPriceRequest)(nil),       // 14: greedy_eye.v1.GetLatestPriceRequest
	(*ListPriceHistoryRequest)(nil),     // 15: greedy_eye.v1.ListPriceHistoryRequest
	(*ListPriceHistoryResponse)(nil),    // 16: greedy_eye.v1.ListPriceHistoryResponse
	(*ListPricesByIntervalRequest)(nil), // 17: greedy_eye.v1.ListPricesByIntervalRequest
	(*DeletePriceRequest)(nil),          // 18: greedy_eye.v1.DeletePriceRequest
	(*DeletePricesRequest)(nil),         // 19: greedy_eye.v1.DeletePricesRequest
	(*FetchExternalPricesRequest)(nil),  // 20: greedy_eye.v1.FetchExternalPricesRequest
	(*FetchExternalPricesResponse)(nil), // 21: greedy_eye.v1.FetchExternalPricesResponse
	(*timestamppb.Timestamp)(nil),       // 22: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),       // 23: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),               // 24: google.protobuf.Empty
}
var file_v1_marketdata_proto_depIdxs = []int32{
	0,  // 0: greedy_eye.v1.Asset.type:type_name -> greedy_eye.v1.AssetType
	22, // 1: greedy_eye.v1.Asset.created_at:type_name -> google.protobuf.Timestamp
	22, // 2: greedy_eye.v1.Asset.updated_at:type_name -> google.protobuf.Timestamp
	22, // 3: greedy_eye.v1.Price.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 4: greedy_eye.v1.CreateAssetRequest.asset:type_name -> greedy_eye.v1.Asset
	1,  // 5: greedy_eye.v1.UpdateAssetRequest.asset:type_name -> greedy_eye.v1.Asset
	23, // 6: greedy_eye.v1.UpdateAssetRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 7: greedy_eye.v1.ListAssetsResponse.assets:type_name -> greedy_eye.v1.Asset
	2,  // 8: greedy_eye.v1.CreatePriceRequest.price:type_name -> greedy_eye.v1.Price
	2,  // 9: greedy_eye.v1.CreatePricesRequest.prices:type_name -> greedy_eye.v1.Price
	22, // 10: greedy_eye.v1.ListPriceHistoryRequest.from:type_name -> google.protobuf.Timestamp
	22, // 11: greedy_eye.v1.ListPriceHistoryRequest.to:type_name -> google.protobuf.Timestamp
	2,  // 12: greedy_eye.v1.ListPriceHistoryResponse.prices:type_name -> greedy_eye.v1.Price
	22, // 13: greedy_eye.v1.ListPricesByIntervalRequest.from:type_name -> google.protobuf.Timestamp
	22, // 14: greedy_eye.v1.ListPricesByIntervalRequest.to:type_name -> google.protobuf.Timestamp
	22, // 15: greedy_eye.v1.DeletePricesRequest.from:type_name -> google.protobuf.Timestamp
	22, // 16: greedy_eye.v1.DeletePricesRequest.to:type_name -> google.protobuf.Timestamp
	3,  // 17: greedy_eye.v1.MarketDataService.CreateAsset:input_type -> greedy_eye.v1.CreateAssetRequest
	4,  // 18: greedy_eye.v1.MarketDataService.GetAsset:input_type -> greedy_eye.v1.GetAssetRequest
	5,  // 19: greedy_eye.v1.MarketDataService.UpdateAsset:input_type -> greedy_eye.v1.UpdateAssetRequest
	6,  // 20: greedy_eye.v1.MarketDataService.DeleteAsset:input_type -> greedy_eye.v1.DeleteAssetRequest
	7,  // 21: greedy_eye.v1.MarketDataService.ListAssets:input_type -> greedy_eye.v1.ListAssetsRequest
	9,  // 22: greedy_eye.v1.MarketDataService.EnrichAssetData:input_type -> greedy_eye.v1.EnrichAssetDataRequest
	10, // 23: greedy_eye.v1.MarketDataService.FindSimilarAssets:input_type -> greedy_eye.v1.FindSimilarAssetsRequest
	11, // 24: greedy_eye.v1.MarketDataService.CreatePrice:input_type -> greedy_eye.v1.CreatePriceRequest
	12, // 25: greedy_eye.v1.MarketDataService.CreatePrices:input_type -> greedy_eye.v1.CreatePricesRequest
	14, // 26: greedy_eye.v1.MarketDataService.GetLatestPrice:input_type -> greedy_eye.v1.GetLatestPriceRequest
	15, // 27: greedy_eye.v1.MarketDataService.ListPriceHistory:input_type -> greedy_eye.v1.ListPriceHistoryRequest
	17, // 28: greedy_eye.v1.MarketDataService.ListPricesByInterval:input_type -> greedy_eye.v1.ListPricesByIntervalRequest
	18, // 29: greedy_eye.v1.MarketDataService.DeletePrice:input_type -> greedy_eye.v1.DeletePriceRequest
	19, // 30: greedy_eye.v1.MarketDataService.DeletePrices:input_type -> greedy_eye.v1.DeletePricesRequest
	20, // 31: greedy_eye.v1.MarketDataService.FetchExternalPrices:input_type -> greedy_eye.v1.FetchExternalPricesRequest
	1,  // 32: greedy_eye.v1.MarketDataService.CreateAsset:output_type -> greedy_eye.v1.Asset
	1,  // 33: greedy_eye.v1.MarketDataService.GetAsset:output_type -> greedy_eye.v1.Asset
	1,  // 34: greedy_eye.v1.MarketDataService.UpdateAsset:output_type -> greedy_eye.v1.Asset
	24, // 35: greedy_eye.v1.MarketDataService.DeleteAsset:output_type -> google.protobuf.Empty
	8,  // 36: greedy_eye.v1.MarketDataService.ListAssets:output_type -> greedy_eye.v1.ListAssetsResponse
	1,  // 37: greedy_eye.v1.MarketDataService.EnrichAssetData:output_type -> greedy_eye.v1.Asset
	8,  // 38: greedy_eye.v1.MarketDataService.FindSimilarAssets:output_type -> greedy_eye.v1.ListAssetsResponse
	2,  // 39: greedy_eye.v1.MarketDataService.CreatePrice:output_type -> greedy_eye.v1.Price
	13, // 40: greedy_eye.v1.MarketDataService.CreatePrices:output_type -> greedy_eye.v1.CreatePricesResponse
	2,  // 41: greedy_eye.v1.MarketDataService.GetLatestPrice:output_type -> greedy_eye.v1.Price
	16, // 42: greedy_eye.v1.MarketDataService.ListPriceHistory:output_type -> greedy_eye.v1.ListPriceHistoryResponse
	16, // 43: greedy_eye.v1.MarketDataService.ListPricesByInterval:output_type -> greedy_eye.v1.ListPriceHistoryResponse
	24, // 44: greedy_eye.v1.MarketDataService.DeletePrice:output_type -> google.protobuf.Empty
	24, // 45: greedy_eye.v1.MarketDataService.DeletePrices:output_type -> google.protobuf.Empty
	21, // 46: greedy_eye.v1.MarketDataService.FetchExternalPrices:output_type -> greedy_eye.v1.FetchExternalPricesResponse
	32, // [32:47] is the sub-list for method output_type
	17, // [17:32] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_v1_marketdata_proto_init() }
func file_v1_marketdata_proto_init() {
	if File_v1_marketdata_proto != nil {
		return
	}
	file_v1_marketdata_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_marketdata_proto_msgTypes[1].OneofWrappers = []any{}
	file_v1_marketdata_proto_msgTypes[6].OneofWrappers = []any{}
	file_v1_marketdata_proto_msgTypes[13].OneofWrappers = []any{}
	file_v1_marketdata_proto_msgTypes[14].OneofWrappers = []any{}
	file_v1_marketdata_proto_msgTypes[16].OneofWrappers = []any{}
	file_v1_marketdata_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_marketdata_proto_rawDesc), len(file_v1_marketdata_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_marketdata_proto_goTypes,
		DependencyIndexes: file_v1_marketdata_proto_depIdxs,
		EnumInfos:         file_v1_marketdata_proto_enumTypes,
		MessageInfos:      file_v1_marketdata_proto_msgTypes,
	}.Build()
	File_v1_marketdata_proto = out.File
	file_v1_marketdata_proto_goTypes = nil
	file_v1_marketdata_proto_depIdxs = nil
}
