// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/foxcool/greedy-eye/pkg/ent/account"
	"github.com/foxcool/greedy-eye/pkg/ent/asset"
	"github.com/foxcool/greedy-eye/pkg/ent/holding"
	"github.com/foxcool/greedy-eye/pkg/ent/portfolio"
	"github.com/shopspring/decimal"
)

// HoldingCreate is the builder for creating a Holding entity.
type HoldingCreate struct {
	config
	mutation *HoldingMutation
	hooks    []Hook
}

// SetAmount sets the "amount" field.
func (hc *HoldingCreate) SetAmount(d decimal.Decimal) *HoldingCreate {
	hc.mutation.SetAmount(d)
	return hc
}

// SetAssetID sets the "asset" edge to the Asset entity by ID.
func (hc *HoldingCreate) SetAssetID(id int) *HoldingCreate {
	hc.mutation.SetAssetID(id)
	return hc
}

// SetNillableAssetID sets the "asset" edge to the Asset entity by ID if the given value is not nil.
func (hc *HoldingCreate) SetNillableAssetID(id *int) *HoldingCreate {
	if id != nil {
		hc = hc.SetAssetID(*id)
	}
	return hc
}

// SetAsset sets the "asset" edge to the Asset entity.
func (hc *HoldingCreate) SetAsset(a *Asset) *HoldingCreate {
	return hc.SetAssetID(a.ID)
}

// SetPortfolioID sets the "portfolio" edge to the Portfolio entity by ID.
func (hc *HoldingCreate) SetPortfolioID(id int) *HoldingCreate {
	hc.mutation.SetPortfolioID(id)
	return hc
}

// SetNillablePortfolioID sets the "portfolio" edge to the Portfolio entity by ID if the given value is not nil.
func (hc *HoldingCreate) SetNillablePortfolioID(id *int) *HoldingCreate {
	if id != nil {
		hc = hc.SetPortfolioID(*id)
	}
	return hc
}

// SetPortfolio sets the "portfolio" edge to the Portfolio entity.
func (hc *HoldingCreate) SetPortfolio(p *Portfolio) *HoldingCreate {
	return hc.SetPortfolioID(p.ID)
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (hc *HoldingCreate) SetAccountID(id int) *HoldingCreate {
	hc.mutation.SetAccountID(id)
	return hc
}

// SetNillableAccountID sets the "account" edge to the Account entity by ID if the given value is not nil.
func (hc *HoldingCreate) SetNillableAccountID(id *int) *HoldingCreate {
	if id != nil {
		hc = hc.SetAccountID(*id)
	}
	return hc
}

// SetAccount sets the "account" edge to the Account entity.
func (hc *HoldingCreate) SetAccount(a *Account) *HoldingCreate {
	return hc.SetAccountID(a.ID)
}

// Mutation returns the HoldingMutation object of the builder.
func (hc *HoldingCreate) Mutation() *HoldingMutation {
	return hc.mutation
}

// Save creates the Holding in the database.
func (hc *HoldingCreate) Save(ctx context.Context) (*Holding, error) {
	return withHooks(ctx, hc.sqlSave, hc.mutation, hc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (hc *HoldingCreate) SaveX(ctx context.Context) *Holding {
	v, err := hc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hc *HoldingCreate) Exec(ctx context.Context) error {
	_, err := hc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hc *HoldingCreate) ExecX(ctx context.Context) {
	if err := hc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hc *HoldingCreate) check() error {
	if _, ok := hc.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Holding.amount"`)}
	}
	return nil
}

func (hc *HoldingCreate) sqlSave(ctx context.Context) (*Holding, error) {
	if err := hc.check(); err != nil {
		return nil, err
	}
	_node, _spec := hc.createSpec()
	if err := sqlgraph.CreateNode(ctx, hc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	hc.mutation.id = &_node.ID
	hc.mutation.done = true
	return _node, nil
}

func (hc *HoldingCreate) createSpec() (*Holding, *sqlgraph.CreateSpec) {
	var (
		_node = &Holding{config: hc.config}
		_spec = sqlgraph.NewCreateSpec(holding.Table, sqlgraph.NewFieldSpec(holding.FieldID, field.TypeInt))
	)
	if value, ok := hc.mutation.Amount(); ok {
		_spec.SetField(holding.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if nodes := hc.mutation.AssetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   holding.AssetTable,
			Columns: []string{holding.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.holding_asset = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := hc.mutation.PortfolioIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   holding.PortfolioTable,
			Columns: []string{holding.PortfolioColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(portfolio.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.portfolio_holdings = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := hc.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   holding.AccountTable,
			Columns: []string{holding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.account_holdings = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// HoldingCreateBulk is the builder for creating many Holding entities in bulk.
type HoldingCreateBulk struct {
	config
	err      error
	builders []*HoldingCreate
}

// Save creates the Holding entities in the database.
func (hcb *HoldingCreateBulk) Save(ctx context.Context) ([]*Holding, error) {
	if hcb.err != nil {
		return nil, hcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(hcb.builders))
	nodes := make([]*Holding, len(hcb.builders))
	mutators := make([]Mutator, len(hcb.builders))
	for i := range hcb.builders {
		func(i int, root context.Context) {
			builder := hcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HoldingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, hcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, hcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, hcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (hcb *HoldingCreateBulk) SaveX(ctx context.Context) []*Holding {
	v, err := hcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hcb *HoldingCreateBulk) Exec(ctx context.Context) error {
	_, err := hcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hcb *HoldingCreateBulk) ExecX(ctx context.Context) {
	if err := hcb.Exec(ctx); err != nil {
		panic(err)
	}
}
