// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: api/models/api_key.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// APIKey represents an API key for authentication
type APIKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Scopes        []string               `protobuf:"bytes,5,rep,name=scopes,proto3" json:"scopes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Enabled       bool                   `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	KeyPrefix     string                 `protobuf:"bytes,10,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"` // First 8 characters for display
	UsageCount    int32                  `protobuf:"varint,11,opt,name=usage_count,json=usageCount,proto3" json:"usage_count,omitempty"`
	RateLimit     *RateLimitConfig       `protobuf:"bytes,12,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKey) Reset() {
	*x = APIKey{}
	mi := &file_api_models_api_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKey) ProtoMessage() {}

func (x *APIKey) ProtoReflect() protoreflect.Message {
	mi := &file_api_models_api_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKey.ProtoReflect.Descriptor instead.
func (*APIKey) Descriptor() ([]byte, []int) {
	return file_api_models_api_key_proto_rawDescGZIP(), []int{0}
}

func (x *APIKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *APIKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *APIKey) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *APIKey) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *APIKey) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *APIKey) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *APIKey) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *APIKey) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *APIKey) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *APIKey) GetKeyPrefix() string {
	if x != nil {
		return x.KeyPrefix
	}
	return ""
}

func (x *APIKey) GetUsageCount() int32 {
	if x != nil {
		return x.UsageCount
	}
	return 0
}

func (x *APIKey) GetRateLimit() *RateLimitConfig {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

// RateLimitConfig defines rate limiting for API keys
type RateLimitConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestsPerMinute int32                  `protobuf:"varint,1,opt,name=requests_per_minute,json=requestsPerMinute,proto3" json:"requests_per_minute,omitempty"`
	RequestsPerHour   int32                  `protobuf:"varint,2,opt,name=requests_per_hour,json=requestsPerHour,proto3" json:"requests_per_hour,omitempty"`
	RequestsPerDay    int32                  `protobuf:"varint,3,opt,name=requests_per_day,json=requestsPerDay,proto3" json:"requests_per_day,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RateLimitConfig) Reset() {
	*x = RateLimitConfig{}
	mi := &file_api_models_api_key_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitConfig) ProtoMessage() {}

func (x *RateLimitConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_models_api_key_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitConfig.ProtoReflect.Descriptor instead.
func (*RateLimitConfig) Descriptor() ([]byte, []int) {
	return file_api_models_api_key_proto_rawDescGZIP(), []int{1}
}

func (x *RateLimitConfig) GetRequestsPerMinute() int32 {
	if x != nil {
		return x.RequestsPerMinute
	}
	return 0
}

func (x *RateLimitConfig) GetRequestsPerHour() int32 {
	if x != nil {
		return x.RequestsPerHour
	}
	return 0
}

func (x *RateLimitConfig) GetRequestsPerDay() int32 {
	if x != nil {
		return x.RequestsPerDay
	}
	return 0
}

// ExternalAPIKey stores encrypted external API credentials
type ExternalAPIKey struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId              string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Provider            string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"` // e.g., "binance", "gate.io", "coingecko"
	EncryptedApiKey     string                 `protobuf:"bytes,4,opt,name=encrypted_api_key,json=encryptedApiKey,proto3" json:"encrypted_api_key,omitempty"`
	EncryptedApiSecret  string                 `protobuf:"bytes,5,opt,name=encrypted_api_secret,json=encryptedApiSecret,proto3" json:"encrypted_api_secret,omitempty"`
	EncryptedPassphrase *string                `protobuf:"bytes,6,opt,name=encrypted_passphrase,json=encryptedPassphrase,proto3,oneof" json:"encrypted_passphrase,omitempty"` // For some exchanges
	Sandbox             bool                   `protobuf:"varint,7,opt,name=sandbox,proto3" json:"sandbox,omitempty"`                                                         // Whether this is a sandbox/test key
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExternalAPIKey) Reset() {
	*x = ExternalAPIKey{}
	mi := &file_api_models_api_key_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalAPIKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalAPIKey) ProtoMessage() {}

func (x *ExternalAPIKey) ProtoReflect() protoreflect.Message {
	mi := &file_api_models_api_key_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalAPIKey.ProtoReflect.Descriptor instead.
func (*ExternalAPIKey) Descriptor() ([]byte, []int) {
	return file_api_models_api_key_proto_rawDescGZIP(), []int{2}
}

func (x *ExternalAPIKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExternalAPIKey) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExternalAPIKey) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ExternalAPIKey) GetEncryptedApiKey() string {
	if x != nil {
		return x.EncryptedApiKey
	}
	return ""
}

func (x *ExternalAPIKey) GetEncryptedApiSecret() string {
	if x != nil {
		return x.EncryptedApiSecret
	}
	return ""
}

func (x *ExternalAPIKey) GetEncryptedPassphrase() string {
	if x != nil && x.EncryptedPassphrase != nil {
		return *x.EncryptedPassphrase
	}
	return ""
}

func (x *ExternalAPIKey) GetSandbox() bool {
	if x != nil {
		return x.Sandbox
	}
	return false
}

func (x *ExternalAPIKey) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ExternalAPIKey) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_models_api_key_proto protoreflect.FileDescriptor

const file_api_models_api_key_proto_rawDesc = "" +
	"\n" +
	"\x18api/models/api_key.proto\x12\x06models\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc5\x03\n" +
	"\x06APIKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x16\n" +
	"\x06scopes\x18\x05 \x03(\tR\x06scopes\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x18\n" +
	"\aenabled\x18\t \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"key_prefix\x18\n" +
	" \x01(\tR\tkeyPrefix\x12\x1f\n" +
	"\vusage_count\x18\v \x01(\x05R\n" +
	"usageCount\x126\n" +
	"\n" +
	"rate_limit\x18\f \x01(\v2\x17.models.RateLimitConfigR\trateLimit\"\x97\x01\n" +
	"\x0fRateLimitConfig\x12.\n" +
	"\x13requests_per_minute\x18\x01 \x01(\x05R\x11requestsPerMinute\x12*\n" +
	"\x11requests_per_hour\x18\x02 \x01(\x05R\x0frequestsPerHour\x12(\n" +
	"\x10requests_per_day\x18\x03 \x01(\x05R\x0erequestsPerDay\"\x94\x03\n" +
	"\x0eExternalAPIKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12*\n" +
	"\x11encrypted_api_key\x18\x04 \x01(\tR\x0fencryptedApiKey\x120\n" +
	"\x14encrypted_api_secret\x18\x05 \x01(\tR\x12encryptedApiSecret\x126\n" +
	"\x14encrypted_passphrase\x18\x06 \x01(\tH\x00R\x13encryptedPassphrase\x88\x01\x01\x12\x18\n" +
	"\asandbox\x18\a \x01(\bR\asandbox\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x17\n" +
	"\x15_encrypted_passphraseB\x84\x01\n" +
	"\n" +
	"com.modelsB\vApiKeyProtoP\x01Z1github.com/foxcool/greedy-eye/internal/api/models\xa2\x02\x03MXX\xaa\x02\x06Models\xca\x02\x06Models\xe2\x02\x12Models\\GPBMetadata\xea\x02\x06Modelsb\x06proto3"

var (
	file_api_models_api_key_proto_rawDescOnce sync.Once
	file_api_models_api_key_proto_rawDescData []byte
)

func file_api_models_api_key_proto_rawDescGZIP() []byte {
	file_api_models_api_key_proto_rawDescOnce.Do(func() {
		file_api_models_api_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_models_api_key_proto_rawDesc), len(file_api_models_api_key_proto_rawDesc)))
	})
	return file_api_models_api_key_proto_rawDescData
}

var file_api_models_api_key_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_models_api_key_proto_goTypes = []any{
	(*APIKey)(nil),                // 0: models.APIKey
	(*RateLimitConfig)(nil),       // 1: models.RateLimitConfig
	(*ExternalAPIKey)(nil),        // 2: models.ExternalAPIKey
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_api_models_api_key_proto_depIdxs = []int32{
	3, // 0: models.APIKey.created_at:type_name -> google.protobuf.Timestamp
	3, // 1: models.APIKey.last_used_at:type_name -> google.protobuf.Timestamp
	3, // 2: models.APIKey.expires_at:type_name -> google.protobuf.Timestamp
	1, // 3: models.APIKey.rate_limit:type_name -> models.RateLimitConfig
	3, // 4: models.ExternalAPIKey.created_at:type_name -> google.protobuf.Timestamp
	3, // 5: models.ExternalAPIKey.updated_at:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_models_api_key_proto_init() }
func file_api_models_api_key_proto_init() {
	if File_api_models_api_key_proto != nil {
		return
	}
	file_api_models_api_key_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_models_api_key_proto_rawDesc), len(file_api_models_api_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_models_api_key_proto_goTypes,
		DependencyIndexes: file_api_models_api_key_proto_depIdxs,
		MessageInfos:      file_api_models_api_key_proto_msgTypes,
	}.Build()
	File_api_models_api_key_proto = out.File
	file_api_models_api_key_proto_goTypes = nil
	file_api_models_api_key_proto_depIdxs = nil
}
