// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/models/telegram.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_MESSAGE_TYPE_TEXT        MessageType = 1
	MessageType_MESSAGE_TYPE_VOICE       MessageType = 2
	MessageType_MESSAGE_TYPE_COMMAND     MessageType = 3
	MessageType_MESSAGE_TYPE_CALLBACK    MessageType = 4
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_TEXT",
		2: "MESSAGE_TYPE_VOICE",
		3: "MESSAGE_TYPE_COMMAND",
		4: "MESSAGE_TYPE_CALLBACK",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"MESSAGE_TYPE_TEXT":        1,
		"MESSAGE_TYPE_VOICE":       2,
		"MESSAGE_TYPE_COMMAND":     3,
		"MESSAGE_TYPE_CALLBACK":    4,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_models_telegram_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_api_models_telegram_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_api_models_telegram_proto_rawDescGZIP(), []int{0}
}

type ResponseType int32

const (
	ResponseType_RESPONSE_TYPE_UNSPECIFIED ResponseType = 0
	ResponseType_RESPONSE_TYPE_TEXT        ResponseType = 1
	ResponseType_RESPONSE_TYPE_VOICE       ResponseType = 2
	ResponseType_RESPONSE_TYPE_PHOTO       ResponseType = 3
	ResponseType_RESPONSE_TYPE_DOCUMENT    ResponseType = 4
)

// Enum value maps for ResponseType.
var (
	ResponseType_name = map[int32]string{
		0: "RESPONSE_TYPE_UNSPECIFIED",
		1: "RESPONSE_TYPE_TEXT",
		2: "RESPONSE_TYPE_VOICE",
		3: "RESPONSE_TYPE_PHOTO",
		4: "RESPONSE_TYPE_DOCUMENT",
	}
	ResponseType_value = map[string]int32{
		"RESPONSE_TYPE_UNSPECIFIED": 0,
		"RESPONSE_TYPE_TEXT":        1,
		"RESPONSE_TYPE_VOICE":       2,
		"RESPONSE_TYPE_PHOTO":       3,
		"RESPONSE_TYPE_DOCUMENT":    4,
	}
)

func (x ResponseType) Enum() *ResponseType {
	p := new(ResponseType)
	*p = x
	return p
}

func (x ResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_models_telegram_proto_enumTypes[1].Descriptor()
}

func (ResponseType) Type() protoreflect.EnumType {
	return &file_api_models_telegram_proto_enumTypes[1]
}

func (x ResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseType.Descriptor instead.
func (ResponseType) EnumDescriptor() ([]byte, []int) {
	return file_api_models_telegram_proto_rawDescGZIP(), []int{1}
}

type ResponseFormat int32

const (
	ResponseFormat_RESPONSE_FORMAT_UNSPECIFIED ResponseFormat = 0
	ResponseFormat_RESPONSE_FORMAT_PLAIN       ResponseFormat = 1
	ResponseFormat_RESPONSE_FORMAT_MARKDOWN    ResponseFormat = 2
	ResponseFormat_RESPONSE_FORMAT_HTML        ResponseFormat = 3
)

// Enum value maps for ResponseFormat.
var (
	ResponseFormat_name = map[int32]string{
		0: "RESPONSE_FORMAT_UNSPECIFIED",
		1: "RESPONSE_FORMAT_PLAIN",
		2: "RESPONSE_FORMAT_MARKDOWN",
		3: "RESPONSE_FORMAT_HTML",
	}
	ResponseFormat_value = map[string]int32{
		"RESPONSE_FORMAT_UNSPECIFIED": 0,
		"RESPONSE_FORMAT_PLAIN":       1,
		"RESPONSE_FORMAT_MARKDOWN":    2,
		"RESPONSE_FORMAT_HTML":        3,
	}
)

func (x ResponseFormat) Enum() *ResponseFormat {
	p := new(ResponseFormat)
	*p = x
	return p
}

func (x ResponseFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_api_models_telegram_proto_enumTypes[2].Descriptor()
}

func (ResponseFormat) Type() protoreflect.EnumType {
	return &file_api_models_telegram_proto_enumTypes[2]
}

func (x ResponseFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseFormat.Descriptor instead.
func (ResponseFormat) EnumDescriptor() ([]byte, []int) {
	return file_api_models_telegram_proto_rawDescGZIP(), []int{2}
}

type NotificationType int32

const (
	NotificationType_NOTIFICATION_TYPE_UNSPECIFIED      NotificationType = 0
	NotificationType_NOTIFICATION_TYPE_PRICE_ALERT      NotificationType = 1
	NotificationType_NOTIFICATION_TYPE_PORTFOLIO_CHANGE NotificationType = 2
	NotificationType_NOTIFICATION_TYPE_TRADE_EXECUTED   NotificationType = 3
	NotificationType_NOTIFICATION_TYPE_SYNC_COMPLETED   NotificationType = 4
	NotificationType_NOTIFICATION_TYPE_SYSTEM_ALERT     NotificationType = 5
	NotificationType_NOTIFICATION_TYPE_WEEKLY_REPORT    NotificationType = 6
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "NOTIFICATION_TYPE_UNSPECIFIED",
		1: "NOTIFICATION_TYPE_PRICE_ALERT",
		2: "NOTIFICATION_TYPE_PORTFOLIO_CHANGE",
		3: "NOTIFICATION_TYPE_TRADE_EXECUTED",
		4: "NOTIFICATION_TYPE_SYNC_COMPLETED",
		5: "NOTIFICATION_TYPE_SYSTEM_ALERT",
		6: "NOTIFICATION_TYPE_WEEKLY_REPORT",
	}
	NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_UNSPECIFIED":      0,
		"NOTIFICATION_TYPE_PRICE_ALERT":      1,
		"NOTIFICATION_TYPE_PORTFOLIO_CHANGE": 2,
		"NOTIFICATION_TYPE_TRADE_EXECUTED":   3,
		"NOTIFICATION_TYPE_SYNC_COMPLETED":   4,
		"NOTIFICATION_TYPE_SYSTEM_ALERT":     5,
		"NOTIFICATION_TYPE_WEEKLY_REPORT":    6,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_models_telegram_proto_enumTypes[3].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_api_models_telegram_proto_enumTypes[3]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_api_models_telegram_proto_rawDescGZIP(), []int{3}
}

type AlertType int32

const (
	AlertType_ALERT_TYPE_UNSPECIFIED      AlertType = 0
	AlertType_ALERT_TYPE_PRICE_ABOVE      AlertType = 1
	AlertType_ALERT_TYPE_PRICE_BELOW      AlertType = 2
	AlertType_ALERT_TYPE_PRICE_CHANGE     AlertType = 3
	AlertType_ALERT_TYPE_PORTFOLIO_VALUE  AlertType = 4
	AlertType_ALERT_TYPE_PORTFOLIO_CHANGE AlertType = 5
	AlertType_ALERT_TYPE_BALANCE_LOW      AlertType = 6
)

// Enum value maps for AlertType.
var (
	AlertType_name = map[int32]string{
		0: "ALERT_TYPE_UNSPECIFIED",
		1: "ALERT_TYPE_PRICE_ABOVE",
		2: "ALERT_TYPE_PRICE_BELOW",
		3: "ALERT_TYPE_PRICE_CHANGE",
		4: "ALERT_TYPE_PORTFOLIO_VALUE",
		5: "ALERT_TYPE_PORTFOLIO_CHANGE",
		6: "ALERT_TYPE_BALANCE_LOW",
	}
	AlertType_value = map[string]int32{
		"ALERT_TYPE_UNSPECIFIED":      0,
		"ALERT_TYPE_PRICE_ABOVE":      1,
		"ALERT_TYPE_PRICE_BELOW":      2,
		"ALERT_TYPE_PRICE_CHANGE":     3,
		"ALERT_TYPE_PORTFOLIO_VALUE":  4,
		"ALERT_TYPE_PORTFOLIO_CHANGE": 5,
		"ALERT_TYPE_BALANCE_LOW":      6,
	}
)

func (x AlertType) Enum() *AlertType {
	p := new(AlertType)
	*p = x
	return p
}

func (x AlertType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_models_telegram_proto_enumTypes[4].Descriptor()
}

func (AlertType) Type() protoreflect.EnumType {
	return &file_api_models_telegram_proto_enumTypes[4]
}

func (x AlertType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertType.Descriptor instead.
func (AlertType) EnumDescriptor() ([]byte, []int) {
	return file_api_models_telegram_proto_rawDescGZIP(), []int{4}
}

type AlertCondition int32

const (
	AlertCondition_ALERT_CONDITION_UNSPECIFIED     AlertCondition = 0
	AlertCondition_ALERT_CONDITION_GREATER_THAN    AlertCondition = 1
	AlertCondition_ALERT_CONDITION_LESS_THAN       AlertCondition = 2
	AlertCondition_ALERT_CONDITION_EQUAL           AlertCondition = 3
	AlertCondition_ALERT_CONDITION_CHANGE_PERCENT  AlertCondition = 4
	AlertCondition_ALERT_CONDITION_CHANGE_ABSOLUTE AlertCondition = 5
)

// Enum value maps for AlertCondition.
var (
	AlertCondition_name = map[int32]string{
		0: "ALERT_CONDITION_UNSPECIFIED",
		1: "ALERT_CONDITION_GREATER_THAN",
		2: "ALERT_CONDITION_LESS_THAN",
		3: "ALERT_CONDITION_EQUAL",
		4: "ALERT_CONDITION_CHANGE_PERCENT",
		5: "ALERT_CONDITION_CHANGE_ABSOLUTE",
	}
	AlertCondition_value = map[string]int32{
		"ALERT_CONDITION_UNSPECIFIED":     0,
		"ALERT_CONDITION_GREATER_THAN":    1,
		"ALERT_CONDITION_LESS_THAN":       2,
		"ALERT_CONDITION_EQUAL":           3,
		"ALERT_CONDITION_CHANGE_PERCENT":  4,
		"ALERT_CONDITION_CHANGE_ABSOLUTE": 5,
	}
)

func (x AlertCondition) Enum() *AlertCondition {
	p := new(AlertCondition)
	*p = x
	return p
}

func (x AlertCondition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertCondition) Descriptor() protoreflect.EnumDescriptor {
	return file_api_models_telegram_proto_enumTypes[5].Descriptor()
}

func (AlertCondition) Type() protoreflect.EnumType {
	return &file_api_models_telegram_proto_enumTypes[5]
}

func (x AlertCondition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertCondition.Descriptor instead.
func (AlertCondition) EnumDescriptor() ([]byte, []int) {
	return file_api_models_telegram_proto_rawDescGZIP(), []int{5}
}

// TelegramUser represents a user linked between Telegram and the system
type TelegramUser struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TelegramId           string                 `protobuf:"bytes,1,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`                                // Telegram user ID
	UserId               string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                            // System User ID (link to User model)
	Username             string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`                                                      // Telegram username (@username)
	FirstName            string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`                                   // User's first name in Telegram
	LastName             string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`                                      // User's last name in Telegram
	LanguageCode         string                 `protobuf:"bytes,6,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`                          // User's language preference (ru, en)
	NotificationsEnabled bool                   `protobuf:"varint,7,opt,name=notifications_enabled,json=notificationsEnabled,proto3" json:"notifications_enabled,omitempty"` // Whether notifications are enabled
	SubscribedAlerts     []string               `protobuf:"bytes,8,rep,name=subscribed_alerts,json=subscribedAlerts,proto3" json:"subscribed_alerts,omitempty"`              // List of alert types user subscribed to
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastActive           *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TelegramUser) Reset() {
	*x = TelegramUser{}
	mi := &file_api_models_telegram_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramUser) ProtoMessage() {}

func (x *TelegramUser) ProtoReflect() protoreflect.Message {
	mi := &file_api_models_telegram_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramUser.ProtoReflect.Descriptor instead.
func (*TelegramUser) Descriptor() ([]byte, []int) {
	return file_api_models_telegram_proto_rawDescGZIP(), []int{0}
}

func (x *TelegramUser) GetTelegramId() string {
	if x != nil {
		return x.TelegramId
	}
	return ""
}

func (x *TelegramUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TelegramUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TelegramUser) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *TelegramUser) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *TelegramUser) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *TelegramUser) GetNotificationsEnabled() bool {
	if x != nil {
		return x.NotificationsEnabled
	}
	return false
}

func (x *TelegramUser) GetSubscribedAlerts() []string {
	if x != nil {
		return x.SubscribedAlerts
	}
	return nil
}

func (x *TelegramUser) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TelegramUser) GetLastActive() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActive
	}
	return nil
}

// SessionContext represents user conversation state
type SessionContext struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TelegramId          string                 `protobuf:"bytes,1,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`                                                                              // Telegram user ID
	CurrentOperation    string                 `protobuf:"bytes,2,opt,name=current_operation,json=currentOperation,proto3" json:"current_operation,omitempty"`                                                            // Current operation: "trade", "portfolio_view", etc.
	ContextData         map[string]string      `protobuf:"bytes,3,rep,name=context_data,json=contextData,proto3" json:"context_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Key-value context data
	ExpiresAt           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`                                                                                 // Session expiration time
	ConversationHistory []string               `protobuf:"bytes,5,rep,name=conversation_history,json=conversationHistory,proto3" json:"conversation_history,omitempty"`                                                   // Recent conversation history
	State               string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`                                                                                                          // Current conversation state
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SessionContext) Reset() {
	*x = SessionContext{}
	mi := &file_api_models_telegram_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionContext) ProtoMessage() {}

func (x *SessionContext) ProtoReflect() protoreflect.Message {
	mi := &file_api_models_telegram_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionContext.ProtoReflect.Descriptor instead.
func (*SessionContext) Descriptor() ([]byte, []int) {
	return file_api_models_telegram_proto_rawDescGZIP(), []int{1}
}

func (x *SessionContext) GetTelegramId() string {
	if x != nil {
		return x.TelegramId
	}
	return ""
}

func (x *SessionContext) GetCurrentOperation() string {
	if x != nil {
		return x.CurrentOperation
	}
	return ""
}

func (x *SessionContext) GetContextData() map[string]string {
	if x != nil {
		return x.ContextData
	}
	return nil
}

func (x *SessionContext) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *SessionContext) GetConversationHistory() []string {
	if x != nil {
		return x.ConversationHistory
	}
	return nil
}

func (x *SessionContext) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// TelegramMessage represents incoming message from Telegram
type TelegramMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`    // Telegram message ID
	TelegramId    string                 `protobuf:"bytes,2,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"` // Sender's Telegram ID
	Type          MessageType            `protobuf:"varint,3,opt,name=type,proto3,enum=models.MessageType" json:"type,omitempty"`      // Message type
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                         // Message content (text or file path)
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`                       // Detected language
	ReceivedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata (file size, duration, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelegramMessage) Reset() {
	*x = TelegramMessage{}
	mi := &file_api_models_telegram_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramMessage) ProtoMessage() {}

func (x *TelegramMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_models_telegram_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramMessage.ProtoReflect.Descriptor instead.
func (*TelegramMessage) Descriptor() ([]byte, []int) {
	return file_api_models_telegram_proto_rawDescGZIP(), []int{2}
}

func (x *TelegramMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *TelegramMessage) GetTelegramId() string {
	if x != nil {
		return x.TelegramId
	}
	return ""
}

func (x *TelegramMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *TelegramMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TelegramMessage) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TelegramMessage) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *TelegramMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// TelegramResponse represents outgoing response to Telegram
type TelegramResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TelegramId          string                 `protobuf:"bytes,1,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`                               // Target Telegram user ID
	Type                ResponseType           `protobuf:"varint,2,opt,name=type,proto3,enum=models.ResponseType" json:"type,omitempty"`                                   // Response type
	Content             string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                                                       // Response content
	Format              ResponseFormat         `protobuf:"varint,4,opt,name=format,proto3,enum=models.ResponseFormat" json:"format,omitempty"`                             // Response format
	Buttons             []*InlineButton        `protobuf:"bytes,5,rep,name=buttons,proto3" json:"buttons,omitempty"`                                                       // Inline keyboard buttons
	EnableVoiceResponse bool                   `protobuf:"varint,6,opt,name=enable_voice_response,json=enableVoiceResponse,proto3" json:"enable_voice_response,omitempty"` // Whether to also send voice response
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TelegramResponse) Reset() {
	*x = TelegramResponse{}
	mi := &file_api_models_telegram_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramResponse) ProtoMessage() {}

func (x *TelegramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_models_telegram_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramResponse.ProtoReflect.Descriptor instead.
func (*TelegramResponse) Descriptor() ([]byte, []int) {
	return file_api_models_telegram_proto_rawDescGZIP(), []int{3}
}

func (x *TelegramResponse) GetTelegramId() string {
	if x != nil {
		return x.TelegramId
	}
	return ""
}

func (x *TelegramResponse) GetType() ResponseType {
	if x != nil {
		return x.Type
	}
	return ResponseType_RESPONSE_TYPE_UNSPECIFIED
}

func (x *TelegramResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TelegramResponse) GetFormat() ResponseFormat {
	if x != nil {
		return x.Format
	}
	return ResponseFormat_RESPONSE_FORMAT_UNSPECIFIED
}

func (x *TelegramResponse) GetButtons() []*InlineButton {
	if x != nil {
		return x.Buttons
	}
	return nil
}

func (x *TelegramResponse) GetEnableVoiceResponse() bool {
	if x != nil {
		return x.EnableVoiceResponse
	}
	return false
}

// InlineButton represents Telegram inline keyboard button
type InlineButton struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`                                     // Button text
	CallbackData  string                 `protobuf:"bytes,2,opt,name=callback_data,json=callbackData,proto3" json:"callback_data,omitempty"` // Callback data when pressed
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`                                       // URL to open (mutually exclusive with callback_data)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InlineButton) Reset() {
	*x = InlineButton{}
	mi := &file_api_models_telegram_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InlineButton) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InlineButton) ProtoMessage() {}

func (x *InlineButton) ProtoReflect() protoreflect.Message {
	mi := &file_api_models_telegram_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InlineButton.ProtoReflect.Descriptor instead.
func (*InlineButton) Descriptor() ([]byte, []int) {
	return file_api_models_telegram_proto_rawDescGZIP(), []int{4}
}

func (x *InlineButton) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *InlineButton) GetCallbackData() string {
	if x != nil {
		return x.CallbackData
	}
	return ""
}

func (x *InlineButton) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Notification represents push notification to user
type TelegramNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TelegramId    string                 `protobuf:"bytes,1,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`    // Target user Telegram ID
	Type          NotificationType       `protobuf:"varint,2,opt,name=type,proto3,enum=models.NotificationType" json:"type,omitempty"`    // Notification type
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                                // Notification title
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                            // Notification message
	AssetSymbol   string                 `protobuf:"bytes,5,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"` // Related asset (if applicable)
	PortfolioId   string                 `protobuf:"bytes,6,opt,name=portfolio_id,json=portfolioId,proto3" json:"portfolio_id,omitempty"` // Related portfolio (if applicable)
	Value         float64                `protobuf:"fixed64,7,opt,name=value,proto3" json:"value,omitempty"`                              // Related value (price, change, etc.)
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Sent          bool                   `protobuf:"varint,9,opt,name=sent,proto3" json:"sent,omitempty"` // Whether notification was sent successfully
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelegramNotification) Reset() {
	*x = TelegramNotification{}
	mi := &file_api_models_telegram_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramNotification) ProtoMessage() {}

func (x *TelegramNotification) ProtoReflect() protoreflect.Message {
	mi := &file_api_models_telegram_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramNotification.ProtoReflect.Descriptor instead.
func (*TelegramNotification) Descriptor() ([]byte, []int) {
	return file_api_models_telegram_proto_rawDescGZIP(), []int{5}
}

func (x *TelegramNotification) GetTelegramId() string {
	if x != nil {
		return x.TelegramId
	}
	return ""
}

func (x *TelegramNotification) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *TelegramNotification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TelegramNotification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TelegramNotification) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

func (x *TelegramNotification) GetPortfolioId() string {
	if x != nil {
		return x.PortfolioId
	}
	return ""
}

func (x *TelegramNotification) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TelegramNotification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TelegramNotification) GetSent() bool {
	if x != nil {
		return x.Sent
	}
	return false
}

// Alert represents user-configured alert
type TelegramAlert struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                       // Alert ID
	TelegramId     string                 `protobuf:"bytes,2,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`                     // Owner Telegram ID
	AlertType      AlertType              `protobuf:"varint,3,opt,name=alert_type,json=alertType,proto3,enum=models.AlertType" json:"alert_type,omitempty"` // Type of alert
	AssetSymbol    string                 `protobuf:"bytes,4,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"`                  // Asset symbol (if applicable)
	PortfolioId    string                 `protobuf:"bytes,5,opt,name=portfolio_id,json=portfolioId,proto3" json:"portfolio_id,omitempty"`                  // Portfolio ID (if applicable)
	Condition      AlertCondition         `protobuf:"varint,6,opt,name=condition,proto3,enum=models.AlertCondition" json:"condition,omitempty"`             // Alert condition
	ThresholdValue float64                `protobuf:"fixed64,7,opt,name=threshold_value,json=thresholdValue,proto3" json:"threshold_value,omitempty"`       // Threshold value for alert
	CustomMessage  string                 `protobuf:"bytes,8,opt,name=custom_message,json=customMessage,proto3" json:"custom_message,omitempty"`            // Custom alert message
	Enabled        bool                   `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`                                            // Whether alert is active
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastTriggered  *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_triggered,json=lastTriggered,proto3" json:"last_triggered,omitempty"`
	TriggerCount   int32                  `protobuf:"varint,12,opt,name=trigger_count,json=triggerCount,proto3" json:"trigger_count,omitempty"` // How many times this alert was triggered
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TelegramAlert) Reset() {
	*x = TelegramAlert{}
	mi := &file_api_models_telegram_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramAlert) ProtoMessage() {}

func (x *TelegramAlert) ProtoReflect() protoreflect.Message {
	mi := &file_api_models_telegram_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramAlert.ProtoReflect.Descriptor instead.
func (*TelegramAlert) Descriptor() ([]byte, []int) {
	return file_api_models_telegram_proto_rawDescGZIP(), []int{6}
}

func (x *TelegramAlert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TelegramAlert) GetTelegramId() string {
	if x != nil {
		return x.TelegramId
	}
	return ""
}

func (x *TelegramAlert) GetAlertType() AlertType {
	if x != nil {
		return x.AlertType
	}
	return AlertType_ALERT_TYPE_UNSPECIFIED
}

func (x *TelegramAlert) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

func (x *TelegramAlert) GetPortfolioId() string {
	if x != nil {
		return x.PortfolioId
	}
	return ""
}

func (x *TelegramAlert) GetCondition() AlertCondition {
	if x != nil {
		return x.Condition
	}
	return AlertCondition_ALERT_CONDITION_UNSPECIFIED
}

func (x *TelegramAlert) GetThresholdValue() float64 {
	if x != nil {
		return x.ThresholdValue
	}
	return 0
}

func (x *TelegramAlert) GetCustomMessage() string {
	if x != nil {
		return x.CustomMessage
	}
	return ""
}

func (x *TelegramAlert) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *TelegramAlert) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TelegramAlert) GetLastTriggered() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTriggered
	}
	return nil
}

func (x *TelegramAlert) GetTriggerCount() int32 {
	if x != nil {
		return x.TriggerCount
	}
	return 0
}

var File_api_models_telegram_proto protoreflect.FileDescriptor

const file_api_models_telegram_proto_rawDesc = "" +
	"\n" +
	"\x19api/models/telegram.proto\x12\x06models\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x03\n" +
	"\fTelegramUser\x12\x1f\n" +
	"\vtelegram_id\x18\x01 \x01(\tR\n" +
	"telegramId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12#\n" +
	"\rlanguage_code\x18\x06 \x01(\tR\flanguageCode\x123\n" +
	"\x15notifications_enabled\x18\a \x01(\bR\x14notificationsEnabled\x12+\n" +
	"\x11subscribed_alerts\x18\b \x03(\tR\x10subscribedAlerts\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vlast_active\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastActive\"\xee\x02\n" +
	"\x0eSessionContext\x12\x1f\n" +
	"\vtelegram_id\x18\x01 \x01(\tR\n" +
	"telegramId\x12+\n" +
	"\x11current_operation\x18\x02 \x01(\tR\x10currentOperation\x12J\n" +
	"\fcontext_data\x18\x03 \x03(\v2'.models.SessionContext.ContextDataEntryR\vcontextData\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x121\n" +
	"\x14conversation_history\x18\x05 \x03(\tR\x13conversationHistory\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x1a>\n" +
	"\x10ContextDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xed\x02\n" +
	"\x0fTelegramMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1f\n" +
	"\vtelegram_id\x18\x02 \x01(\tR\n" +
	"telegramId\x12'\n" +
	"\x04type\x18\x03 \x01(\x0e2\x13.models.MessageTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x12;\n" +
	"\vreceived_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\x12A\n" +
	"\bmetadata\x18\a \x03(\v2%.models.TelegramMessage.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x02\n" +
	"\x10TelegramResponse\x12\x1f\n" +
	"\vtelegram_id\x18\x01 \x01(\tR\n" +
	"telegramId\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.models.ResponseTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12.\n" +
	"\x06format\x18\x04 \x01(\x0e2\x16.models.ResponseFormatR\x06format\x12.\n" +
	"\abuttons\x18\x05 \x03(\v2\x14.models.InlineButtonR\abuttons\x122\n" +
	"\x15enable_voice_response\x18\x06 \x01(\bR\x13enableVoiceResponse\"Y\n" +
	"\fInlineButton\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12#\n" +
	"\rcallback_data\x18\x02 \x01(\tR\fcallbackData\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\xc0\x02\n" +
	"\x14TelegramNotification\x12\x1f\n" +
	"\vtelegram_id\x18\x01 \x01(\tR\n" +
	"telegramId\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.models.NotificationTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12!\n" +
	"\fasset_symbol\x18\x05 \x01(\tR\vassetSymbol\x12!\n" +
	"\fportfolio_id\x18\x06 \x01(\tR\vportfolioId\x12\x14\n" +
	"\x05value\x18\a \x01(\x01R\x05value\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x12\n" +
	"\x04sent\x18\t \x01(\bR\x04sent\"\xfb\x03\n" +
	"\rTelegramAlert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vtelegram_id\x18\x02 \x01(\tR\n" +
	"telegramId\x120\n" +
	"\n" +
	"alert_type\x18\x03 \x01(\x0e2\x11.models.AlertTypeR\talertType\x12!\n" +
	"\fasset_symbol\x18\x04 \x01(\tR\vassetSymbol\x12!\n" +
	"\fportfolio_id\x18\x05 \x01(\tR\vportfolioId\x124\n" +
	"\tcondition\x18\x06 \x01(\x0e2\x16.models.AlertConditionR\tcondition\x12'\n" +
	"\x0fthreshold_value\x18\a \x01(\x01R\x0ethresholdValue\x12%\n" +
	"\x0ecustom_message\x18\b \x01(\tR\rcustomMessage\x12\x18\n" +
	"\aenabled\x18\t \x01(\bR\aenabled\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12A\n" +
	"\x0elast_triggered\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\rlastTriggered\x12#\n" +
	"\rtrigger_count\x18\f \x01(\x05R\ftriggerCount*\x8f\x01\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MESSAGE_TYPE_TEXT\x10\x01\x12\x16\n" +
	"\x12MESSAGE_TYPE_VOICE\x10\x02\x12\x18\n" +
	"\x14MESSAGE_TYPE_COMMAND\x10\x03\x12\x19\n" +
	"\x15MESSAGE_TYPE_CALLBACK\x10\x04*\x93\x01\n" +
	"\fResponseType\x12\x1d\n" +
	"\x19RESPONSE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12RESPONSE_TYPE_TEXT\x10\x01\x12\x17\n" +
	"\x13RESPONSE_TYPE_VOICE\x10\x02\x12\x17\n" +
	"\x13RESPONSE_TYPE_PHOTO\x10\x03\x12\x1a\n" +
	"\x16RESPONSE_TYPE_DOCUMENT\x10\x04*\x84\x01\n" +
	"\x0eResponseFormat\x12\x1f\n" +
	"\x1bRESPONSE_FORMAT_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15RESPONSE_FORMAT_PLAIN\x10\x01\x12\x1c\n" +
	"\x18RESPONSE_FORMAT_MARKDOWN\x10\x02\x12\x18\n" +
	"\x14RESPONSE_FORMAT_HTML\x10\x03*\x95\x02\n" +
	"\x10NotificationType\x12!\n" +
	"\x1dNOTIFICATION_TYPE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dNOTIFICATION_TYPE_PRICE_ALERT\x10\x01\x12&\n" +
	"\"NOTIFICATION_TYPE_PORTFOLIO_CHANGE\x10\x02\x12$\n" +
	" NOTIFICATION_TYPE_TRADE_EXECUTED\x10\x03\x12$\n" +
	" NOTIFICATION_TYPE_SYNC_COMPLETED\x10\x04\x12\"\n" +
	"\x1eNOTIFICATION_TYPE_SYSTEM_ALERT\x10\x05\x12#\n" +
	"\x1fNOTIFICATION_TYPE_WEEKLY_REPORT\x10\x06*\xd9\x01\n" +
	"\tAlertType\x12\x1a\n" +
	"\x16ALERT_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ALERT_TYPE_PRICE_ABOVE\x10\x01\x12\x1a\n" +
	"\x16ALERT_TYPE_PRICE_BELOW\x10\x02\x12\x1b\n" +
	"\x17ALERT_TYPE_PRICE_CHANGE\x10\x03\x12\x1e\n" +
	"\x1aALERT_TYPE_PORTFOLIO_VALUE\x10\x04\x12\x1f\n" +
	"\x1bALERT_TYPE_PORTFOLIO_CHANGE\x10\x05\x12\x1a\n" +
	"\x16ALERT_TYPE_BALANCE_LOW\x10\x06*\xd6\x01\n" +
	"\x0eAlertCondition\x12\x1f\n" +
	"\x1bALERT_CONDITION_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cALERT_CONDITION_GREATER_THAN\x10\x01\x12\x1d\n" +
	"\x19ALERT_CONDITION_LESS_THAN\x10\x02\x12\x19\n" +
	"\x15ALERT_CONDITION_EQUAL\x10\x03\x12\"\n" +
	"\x1eALERT_CONDITION_CHANGE_PERCENT\x10\x04\x12#\n" +
	"\x1fALERT_CONDITION_CHANGE_ABSOLUTE\x10\x05B\x86\x01\n" +
	"\n" +
	"com.modelsB\rTelegramProtoP\x01Z1github.com/foxcool/greedy-eye/internal/api/models\xa2\x02\x03MXX\xaa\x02\x06Models\xca\x02\x06Models\xe2\x02\x12Models\\GPBMetadata\xea\x02\x06Modelsb\x06proto3"

var (
	file_api_models_telegram_proto_rawDescOnce sync.Once
	file_api_models_telegram_proto_rawDescData []byte
)

func file_api_models_telegram_proto_rawDescGZIP() []byte {
	file_api_models_telegram_proto_rawDescOnce.Do(func() {
		file_api_models_telegram_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_models_telegram_proto_rawDesc), len(file_api_models_telegram_proto_rawDesc)))
	})
	return file_api_models_telegram_proto_rawDescData
}

var file_api_models_telegram_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_api_models_telegram_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_models_telegram_proto_goTypes = []any{
	(MessageType)(0),              // 0: models.MessageType
	(ResponseType)(0),             // 1: models.ResponseType
	(ResponseFormat)(0),           // 2: models.ResponseFormat
	(NotificationType)(0),         // 3: models.NotificationType
	(AlertType)(0),                // 4: models.AlertType
	(AlertCondition)(0),           // 5: models.AlertCondition
	(*TelegramUser)(nil),          // 6: models.TelegramUser
	(*SessionContext)(nil),        // 7: models.SessionContext
	(*TelegramMessage)(nil),       // 8: models.TelegramMessage
	(*TelegramResponse)(nil),      // 9: models.TelegramResponse
	(*InlineButton)(nil),          // 10: models.InlineButton
	(*TelegramNotification)(nil),  // 11: models.TelegramNotification
	(*TelegramAlert)(nil),         // 12: models.TelegramAlert
	nil,                           // 13: models.SessionContext.ContextDataEntry
	nil,                           // 14: models.TelegramMessage.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_api_models_telegram_proto_depIdxs = []int32{
	15, // 0: models.TelegramUser.created_at:type_name -> google.protobuf.Timestamp
	15, // 1: models.TelegramUser.last_active:type_name -> google.protobuf.Timestamp
	13, // 2: models.SessionContext.context_data:type_name -> models.SessionContext.ContextDataEntry
	15, // 3: models.SessionContext.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 4: models.TelegramMessage.type:type_name -> models.MessageType
	15, // 5: models.TelegramMessage.received_at:type_name -> google.protobuf.Timestamp
	14, // 6: models.TelegramMessage.metadata:type_name -> models.TelegramMessage.MetadataEntry
	1,  // 7: models.TelegramResponse.type:type_name -> models.ResponseType
	2,  // 8: models.TelegramResponse.format:type_name -> models.ResponseFormat
	10, // 9: models.TelegramResponse.buttons:type_name -> models.InlineButton
	3,  // 10: models.TelegramNotification.type:type_name -> models.NotificationType
	15, // 11: models.TelegramNotification.created_at:type_name -> google.protobuf.Timestamp
	4,  // 12: models.TelegramAlert.alert_type:type_name -> models.AlertType
	5,  // 13: models.TelegramAlert.condition:type_name -> models.AlertCondition
	15, // 14: models.TelegramAlert.created_at:type_name -> google.protobuf.Timestamp
	15, // 15: models.TelegramAlert.last_triggered:type_name -> google.protobuf.Timestamp
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_models_telegram_proto_init() }
func file_api_models_telegram_proto_init() {
	if File_api_models_telegram_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_models_telegram_proto_rawDesc), len(file_api_models_telegram_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_models_telegram_proto_goTypes,
		DependencyIndexes: file_api_models_telegram_proto_depIdxs,
		EnumInfos:         file_api_models_telegram_proto_enumTypes,
		MessageInfos:      file_api_models_telegram_proto_msgTypes,
	}.Build()
	File_api_models_telegram_proto = out.File
	file_api_models_telegram_proto_goTypes = nil
	file_api_models_telegram_proto_depIdxs = nil
}
