---
- name: Cleanup
  hosts: all
  gather_facts: false
  ignore_unreachable: true
  tasks:
    - name: Stop and remove containers
      ansible.builtin.command:
        cmd: docker compose down -v
        chdir: "/opt/molecule-greedy-eye"
      ignore_errors: true
      changed_when: true

    - name: Remove test directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /opt/molecule-greedy-eye
        - /opt/molecule-greedy-eye-backups
