// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/models/rule.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RuleStatus indicates the current status of a rule
type RuleStatus int32

const (
	RuleStatus_RULE_STATUS_UNKNOWN  RuleStatus = 0
	RuleStatus_RULE_STATUS_ACTIVE   RuleStatus = 1
	RuleStatus_RULE_STATUS_PAUSED   RuleStatus = 2
	RuleStatus_RULE_STATUS_DISABLED RuleStatus = 3
	RuleStatus_RULE_STATUS_ERROR    RuleStatus = 4
)

// Enum value maps for RuleStatus.
var (
	RuleStatus_name = map[int32]string{
		0: "RULE_STATUS_UNKNOWN",
		1: "RULE_STATUS_ACTIVE",
		2: "RULE_STATUS_PAUSED",
		3: "RULE_STATUS_DISABLED",
		4: "RULE_STATUS_ERROR",
	}
	RuleStatus_value = map[string]int32{
		"RULE_STATUS_UNKNOWN":  0,
		"RULE_STATUS_ACTIVE":   1,
		"RULE_STATUS_PAUSED":   2,
		"RULE_STATUS_DISABLED": 3,
		"RULE_STATUS_ERROR":    4,
	}
)

func (x RuleStatus) Enum() *RuleStatus {
	p := new(RuleStatus)
	*p = x
	return p
}

func (x RuleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_models_rule_proto_enumTypes[0].Descriptor()
}

func (RuleStatus) Type() protoreflect.EnumType {
	return &file_api_models_rule_proto_enumTypes[0]
}

func (x RuleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuleStatus.Descriptor instead.
func (RuleStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_models_rule_proto_rawDescGZIP(), []int{0}
}

// Rule defines a business rule that can be applied to portfolios
type Rule struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	RuleType        string                 `protobuf:"bytes,4,opt,name=rule_type,json=ruleType,proto3" json:"rule_type,omitempty"` // e.g., "target_allocation", "monthly_withdrawal", "stop_loss", "dca"
	PortfolioId     string                 `protobuf:"bytes,5,opt,name=portfolio_id,json=portfolioId,proto3" json:"portfolio_id,omitempty"`
	UserId          string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Enabled         bool                   `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Configuration   *structpb.Struct       `protobuf:"bytes,8,opt,name=configuration,proto3" json:"configuration,omitempty"` // Flexible configuration for any rule type
	Schedule        *RuleSchedule          `protobuf:"bytes,9,opt,name=schedule,proto3" json:"schedule,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastExecutedAt  *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=last_executed_at,json=lastExecutedAt,proto3" json:"last_executed_at,omitempty"`
	LastExecutionId string                 `protobuf:"bytes,13,opt,name=last_execution_id,json=lastExecutionId,proto3" json:"last_execution_id,omitempty"`
	Status          RuleStatus             `protobuf:"varint,14,opt,name=status,proto3,enum=models.RuleStatus" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_api_models_rule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_api_models_rule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_api_models_rule_proto_rawDescGZIP(), []int{0}
}

func (x *Rule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Rule) GetRuleType() string {
	if x != nil {
		return x.RuleType
	}
	return ""
}

func (x *Rule) GetPortfolioId() string {
	if x != nil {
		return x.PortfolioId
	}
	return ""
}

func (x *Rule) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Rule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Rule) GetConfiguration() *structpb.Struct {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *Rule) GetSchedule() *RuleSchedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *Rule) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Rule) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Rule) GetLastExecutedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastExecutedAt
	}
	return nil
}

func (x *Rule) GetLastExecutionId() string {
	if x != nil {
		return x.LastExecutionId
	}
	return ""
}

func (x *Rule) GetStatus() RuleStatus {
	if x != nil {
		return x.Status
	}
	return RuleStatus_RULE_STATUS_UNKNOWN
}

// RuleSchedule defines when a rule should be executed
type RuleSchedule struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CronExpression string                 `protobuf:"bytes,1,opt,name=cron_expression,json=cronExpression,proto3" json:"cron_expression,omitempty"` // Cron expression for scheduling
	Timezone       string                 `protobuf:"bytes,2,opt,name=timezone,proto3" json:"timezone,omitempty"`                                   // Timezone for execution
	OneTime        bool                   `protobuf:"varint,3,opt,name=one_time,json=oneTime,proto3" json:"one_time,omitempty"`                     // If true, rule executes only once
	ExecuteAfter   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=execute_after,json=executeAfter,proto3" json:"execute_after,omitempty"`       // For delayed execution
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RuleSchedule) Reset() {
	*x = RuleSchedule{}
	mi := &file_api_models_rule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleSchedule) ProtoMessage() {}

func (x *RuleSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_api_models_rule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleSchedule.ProtoReflect.Descriptor instead.
func (*RuleSchedule) Descriptor() ([]byte, []int) {
	return file_api_models_rule_proto_rawDescGZIP(), []int{1}
}

func (x *RuleSchedule) GetCronExpression() string {
	if x != nil {
		return x.CronExpression
	}
	return ""
}

func (x *RuleSchedule) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *RuleSchedule) GetOneTime() bool {
	if x != nil {
		return x.OneTime
	}
	return false
}

func (x *RuleSchedule) GetExecuteAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecuteAfter
	}
	return nil
}

// Common rule configuration types
type TargetAllocationConfig struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Targets                 []*AssetTarget         `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	RebalanceThreshold      float64                `protobuf:"fixed64,2,opt,name=rebalance_threshold,json=rebalanceThreshold,proto3" json:"rebalance_threshold,omitempty"` // Percentage deviation before rebalancing
	AllowPartialRebalancing bool                   `protobuf:"varint,3,opt,name=allow_partial_rebalancing,json=allowPartialRebalancing,proto3" json:"allow_partial_rebalancing,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TargetAllocationConfig) Reset() {
	*x = TargetAllocationConfig{}
	mi := &file_api_models_rule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetAllocationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetAllocationConfig) ProtoMessage() {}

func (x *TargetAllocationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_models_rule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetAllocationConfig.ProtoReflect.Descriptor instead.
func (*TargetAllocationConfig) Descriptor() ([]byte, []int) {
	return file_api_models_rule_proto_rawDescGZIP(), []int{2}
}

func (x *TargetAllocationConfig) GetTargets() []*AssetTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *TargetAllocationConfig) GetRebalanceThreshold() float64 {
	if x != nil {
		return x.RebalanceThreshold
	}
	return 0
}

func (x *TargetAllocationConfig) GetAllowPartialRebalancing() bool {
	if x != nil {
		return x.AllowPartialRebalancing
	}
	return false
}

type AssetTarget struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AssetId          string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	TargetPercentage float64                `protobuf:"fixed64,2,opt,name=target_percentage,json=targetPercentage,proto3" json:"target_percentage,omitempty"` // Target percentage of portfolio
	MinPercentage    float64                `protobuf:"fixed64,3,opt,name=min_percentage,json=minPercentage,proto3" json:"min_percentage,omitempty"`          // Minimum allowed percentage
	MaxPercentage    float64                `protobuf:"fixed64,4,opt,name=max_percentage,json=maxPercentage,proto3" json:"max_percentage,omitempty"`          // Maximum allowed percentage
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AssetTarget) Reset() {
	*x = AssetTarget{}
	mi := &file_api_models_rule_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetTarget) ProtoMessage() {}

func (x *AssetTarget) ProtoReflect() protoreflect.Message {
	mi := &file_api_models_rule_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetTarget.ProtoReflect.Descriptor instead.
func (*AssetTarget) Descriptor() ([]byte, []int) {
	return file_api_models_rule_proto_rawDescGZIP(), []int{3}
}

func (x *AssetTarget) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *AssetTarget) GetTargetPercentage() float64 {
	if x != nil {
		return x.TargetPercentage
	}
	return 0
}

func (x *AssetTarget) GetMinPercentage() float64 {
	if x != nil {
		return x.MinPercentage
	}
	return 0
}

func (x *AssetTarget) GetMaxPercentage() float64 {
	if x != nil {
		return x.MaxPercentage
	}
	return 0
}

type MonthlyWithdrawalConfig struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Amount               float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	DestinationAccountId string                 `protobuf:"bytes,3,opt,name=destination_account_id,json=destinationAccountId,proto3" json:"destination_account_id,omitempty"`
	DayOfMonth           int32                  `protobuf:"varint,4,opt,name=day_of_month,json=dayOfMonth,proto3" json:"day_of_month,omitempty"`            // Day of month for withdrawal (1-31)
	SourceAssetIds       []string               `protobuf:"bytes,5,rep,name=source_asset_ids,json=sourceAssetIds,proto3" json:"source_asset_ids,omitempty"` // Assets to withdraw from, in order of preference
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MonthlyWithdrawalConfig) Reset() {
	*x = MonthlyWithdrawalConfig{}
	mi := &file_api_models_rule_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyWithdrawalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyWithdrawalConfig) ProtoMessage() {}

func (x *MonthlyWithdrawalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_models_rule_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyWithdrawalConfig.ProtoReflect.Descriptor instead.
func (*MonthlyWithdrawalConfig) Descriptor() ([]byte, []int) {
	return file_api_models_rule_proto_rawDescGZIP(), []int{4}
}

func (x *MonthlyWithdrawalConfig) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *MonthlyWithdrawalConfig) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *MonthlyWithdrawalConfig) GetDestinationAccountId() string {
	if x != nil {
		return x.DestinationAccountId
	}
	return ""
}

func (x *MonthlyWithdrawalConfig) GetDayOfMonth() int32 {
	if x != nil {
		return x.DayOfMonth
	}
	return 0
}

func (x *MonthlyWithdrawalConfig) GetSourceAssetIds() []string {
	if x != nil {
		return x.SourceAssetIds
	}
	return nil
}

type StopLossConfig struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	StopLossPercentage   float64                `protobuf:"fixed64,1,opt,name=stop_loss_percentage,json=stopLossPercentage,proto3" json:"stop_loss_percentage,omitempty"`   // Percentage loss before triggering
	Action               string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`                                                         // "sell_all", "sell_percentage", "notify_only"
	SellPercentage       float64                `protobuf:"fixed64,3,opt,name=sell_percentage,json=sellPercentage,proto3" json:"sell_percentage,omitempty"`                 // If action is "sell_percentage"
	NotificationChannels []string               `protobuf:"bytes,4,rep,name=notification_channels,json=notificationChannels,proto3" json:"notification_channels,omitempty"` // "email", "telegram", "webhook"
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StopLossConfig) Reset() {
	*x = StopLossConfig{}
	mi := &file_api_models_rule_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopLossConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopLossConfig) ProtoMessage() {}

func (x *StopLossConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_models_rule_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopLossConfig.ProtoReflect.Descriptor instead.
func (*StopLossConfig) Descriptor() ([]byte, []int) {
	return file_api_models_rule_proto_rawDescGZIP(), []int{5}
}

func (x *StopLossConfig) GetStopLossPercentage() float64 {
	if x != nil {
		return x.StopLossPercentage
	}
	return 0
}

func (x *StopLossConfig) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *StopLossConfig) GetSellPercentage() float64 {
	if x != nil {
		return x.SellPercentage
	}
	return 0
}

func (x *StopLossConfig) GetNotificationChannels() []string {
	if x != nil {
		return x.NotificationChannels
	}
	return nil
}

type DCAConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Amount          float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	TargetAssetId   string                 `protobuf:"bytes,3,opt,name=target_asset_id,json=targetAssetId,proto3" json:"target_asset_id,omitempty"`
	SourceAccountId string                 `protobuf:"bytes,4,opt,name=source_account_id,json=sourceAccountId,proto3" json:"source_account_id,omitempty"`
	Frequency       string                 `protobuf:"bytes,5,opt,name=frequency,proto3" json:"frequency,omitempty"` // "daily", "weekly", "monthly"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DCAConfig) Reset() {
	*x = DCAConfig{}
	mi := &file_api_models_rule_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DCAConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DCAConfig) ProtoMessage() {}

func (x *DCAConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_models_rule_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DCAConfig.ProtoReflect.Descriptor instead.
func (*DCAConfig) Descriptor() ([]byte, []int) {
	return file_api_models_rule_proto_rawDescGZIP(), []int{6}
}

func (x *DCAConfig) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DCAConfig) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *DCAConfig) GetTargetAssetId() string {
	if x != nil {
		return x.TargetAssetId
	}
	return ""
}

func (x *DCAConfig) GetSourceAccountId() string {
	if x != nil {
		return x.SourceAccountId
	}
	return ""
}

func (x *DCAConfig) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

var File_api_models_rule_proto protoreflect.FileDescriptor

const file_api_models_rule_proto_rawDesc = "" +
	"\n" +
	"\x15api/models/rule.proto\x12\x06models\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc4\x04\n" +
	"\x04Rule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\trule_type\x18\x04 \x01(\tR\bruleType\x12!\n" +
	"\fportfolio_id\x18\x05 \x01(\tR\vportfolioId\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\x12=\n" +
	"\rconfiguration\x18\b \x01(\v2\x17.google.protobuf.StructR\rconfiguration\x120\n" +
	"\bschedule\x18\t \x01(\v2\x14.models.RuleScheduleR\bschedule\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12D\n" +
	"\x10last_executed_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x0elastExecutedAt\x12*\n" +
	"\x11last_execution_id\x18\r \x01(\tR\x0flastExecutionId\x12*\n" +
	"\x06status\x18\x0e \x01(\x0e2\x12.models.RuleStatusR\x06status\"\xaf\x01\n" +
	"\fRuleSchedule\x12'\n" +
	"\x0fcron_expression\x18\x01 \x01(\tR\x0ecronExpression\x12\x1a\n" +
	"\btimezone\x18\x02 \x01(\tR\btimezone\x12\x19\n" +
	"\bone_time\x18\x03 \x01(\bR\aoneTime\x12?\n" +
	"\rexecute_after\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fexecuteAfter\"\xb4\x01\n" +
	"\x16TargetAllocationConfig\x12-\n" +
	"\atargets\x18\x01 \x03(\v2\x13.models.AssetTargetR\atargets\x12/\n" +
	"\x13rebalance_threshold\x18\x02 \x01(\x01R\x12rebalanceThreshold\x12:\n" +
	"\x19allow_partial_rebalancing\x18\x03 \x01(\bR\x17allowPartialRebalancing\"\xa3\x01\n" +
	"\vAssetTarget\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12+\n" +
	"\x11target_percentage\x18\x02 \x01(\x01R\x10targetPercentage\x12%\n" +
	"\x0emin_percentage\x18\x03 \x01(\x01R\rminPercentage\x12%\n" +
	"\x0emax_percentage\x18\x04 \x01(\x01R\rmaxPercentage\"\xcf\x01\n" +
	"\x17MonthlyWithdrawalConfig\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x124\n" +
	"\x16destination_account_id\x18\x03 \x01(\tR\x14destinationAccountId\x12 \n" +
	"\fday_of_month\x18\x04 \x01(\x05R\n" +
	"dayOfMonth\x12(\n" +
	"\x10source_asset_ids\x18\x05 \x03(\tR\x0esourceAssetIds\"\xb8\x01\n" +
	"\x0eStopLossConfig\x120\n" +
	"\x14stop_loss_percentage\x18\x01 \x01(\x01R\x12stopLossPercentage\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12'\n" +
	"\x0fsell_percentage\x18\x03 \x01(\x01R\x0esellPercentage\x123\n" +
	"\x15notification_channels\x18\x04 \x03(\tR\x14notificationChannels\"\xb1\x01\n" +
	"\tDCAConfig\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12&\n" +
	"\x0ftarget_asset_id\x18\x03 \x01(\tR\rtargetAssetId\x12*\n" +
	"\x11source_account_id\x18\x04 \x01(\tR\x0fsourceAccountId\x12\x1c\n" +
	"\tfrequency\x18\x05 \x01(\tR\tfrequency*\x86\x01\n" +
	"\n" +
	"RuleStatus\x12\x17\n" +
	"\x13RULE_STATUS_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12RULE_STATUS_ACTIVE\x10\x01\x12\x16\n" +
	"\x12RULE_STATUS_PAUSED\x10\x02\x12\x18\n" +
	"\x14RULE_STATUS_DISABLED\x10\x03\x12\x15\n" +
	"\x11RULE_STATUS_ERROR\x10\x04By\n" +
	"\n" +
	"com.modelsB\tRuleProtoP\x01Z(github.com/foxcool/greedy-eye/api/models\xa2\x02\x03MXX\xaa\x02\x06Models\xca\x02\x06Models\xe2\x02\x12Models\\GPBMetadata\xea\x02\x06Modelsb\x06proto3"

var (
	file_api_models_rule_proto_rawDescOnce sync.Once
	file_api_models_rule_proto_rawDescData []byte
)

func file_api_models_rule_proto_rawDescGZIP() []byte {
	file_api_models_rule_proto_rawDescOnce.Do(func() {
		file_api_models_rule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_models_rule_proto_rawDesc), len(file_api_models_rule_proto_rawDesc)))
	})
	return file_api_models_rule_proto_rawDescData
}

var file_api_models_rule_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_models_rule_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_models_rule_proto_goTypes = []any{
	(RuleStatus)(0),                 // 0: models.RuleStatus
	(*Rule)(nil),                    // 1: models.Rule
	(*RuleSchedule)(nil),            // 2: models.RuleSchedule
	(*TargetAllocationConfig)(nil),  // 3: models.TargetAllocationConfig
	(*AssetTarget)(nil),             // 4: models.AssetTarget
	(*MonthlyWithdrawalConfig)(nil), // 5: models.MonthlyWithdrawalConfig
	(*StopLossConfig)(nil),          // 6: models.StopLossConfig
	(*DCAConfig)(nil),               // 7: models.DCAConfig
	(*structpb.Struct)(nil),         // 8: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),   // 9: google.protobuf.Timestamp
}
var file_api_models_rule_proto_depIdxs = []int32{
	8, // 0: models.Rule.configuration:type_name -> google.protobuf.Struct
	2, // 1: models.Rule.schedule:type_name -> models.RuleSchedule
	9, // 2: models.Rule.created_at:type_name -> google.protobuf.Timestamp
	9, // 3: models.Rule.updated_at:type_name -> google.protobuf.Timestamp
	9, // 4: models.Rule.last_executed_at:type_name -> google.protobuf.Timestamp
	0, // 5: models.Rule.status:type_name -> models.RuleStatus
	9, // 6: models.RuleSchedule.execute_after:type_name -> google.protobuf.Timestamp
	4, // 7: models.TargetAllocationConfig.targets:type_name -> models.AssetTarget
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_api_models_rule_proto_init() }
func file_api_models_rule_proto_init() {
	if File_api_models_rule_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_models_rule_proto_rawDesc), len(file_api_models_rule_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_models_rule_proto_goTypes,
		DependencyIndexes: file_api_models_rule_proto_depIdxs,
		EnumInfos:         file_api_models_rule_proto_enumTypes,
		MessageInfos:      file_api_models_rule_proto_msgTypes,
	}.Build()
	File_api_models_rule_proto = out.File
	file_api_models_rule_proto_goTypes = nil
	file_api_models_rule_proto_depIdxs = nil
}
