// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/foxcool/greedy-eye/internal/services/storage/ent/account"
	"github.com/foxcool/greedy-eye/internal/services/storage/ent/asset"
	"github.com/foxcool/greedy-eye/internal/services/storage/ent/holding"
	"github.com/foxcool/greedy-eye/internal/services/storage/ent/portfolio"
	"github.com/foxcool/greedy-eye/internal/services/storage/ent/predicate"
)

// HoldingQuery is the builder for querying Holding entities.
type HoldingQuery struct {
	config
	ctx           *QueryContext
	order         []holding.OrderOption
	inters        []Interceptor
	predicates    []predicate.Holding
	withAsset     *AssetQuery
	withPortfolio *PortfolioQuery
	withAccount   *AccountQuery
	withFKs       bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the HoldingQuery builder.
func (hq *HoldingQuery) Where(ps ...predicate.Holding) *HoldingQuery {
	hq.predicates = append(hq.predicates, ps...)
	return hq
}

// Limit the number of records to be returned by this query.
func (hq *HoldingQuery) Limit(limit int) *HoldingQuery {
	hq.ctx.Limit = &limit
	return hq
}

// Offset to start from.
func (hq *HoldingQuery) Offset(offset int) *HoldingQuery {
	hq.ctx.Offset = &offset
	return hq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (hq *HoldingQuery) Unique(unique bool) *HoldingQuery {
	hq.ctx.Unique = &unique
	return hq
}

// Order specifies how the records should be ordered.
func (hq *HoldingQuery) Order(o ...holding.OrderOption) *HoldingQuery {
	hq.order = append(hq.order, o...)
	return hq
}

// QueryAsset chains the current query on the "asset" edge.
func (hq *HoldingQuery) QueryAsset() *AssetQuery {
	query := (&AssetClient{config: hq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := hq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := hq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(holding.Table, holding.FieldID, selector),
			sqlgraph.To(asset.Table, asset.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, holding.AssetTable, holding.AssetColumn),
		)
		fromU = sqlgraph.SetNeighbors(hq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPortfolio chains the current query on the "portfolio" edge.
func (hq *HoldingQuery) QueryPortfolio() *PortfolioQuery {
	query := (&PortfolioClient{config: hq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := hq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := hq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(holding.Table, holding.FieldID, selector),
			sqlgraph.To(portfolio.Table, portfolio.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, holding.PortfolioTable, holding.PortfolioColumn),
		)
		fromU = sqlgraph.SetNeighbors(hq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAccount chains the current query on the "account" edge.
func (hq *HoldingQuery) QueryAccount() *AccountQuery {
	query := (&AccountClient{config: hq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := hq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := hq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(holding.Table, holding.FieldID, selector),
			sqlgraph.To(account.Table, account.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, holding.AccountTable, holding.AccountColumn),
		)
		fromU = sqlgraph.SetNeighbors(hq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Holding entity from the query.
// Returns a *NotFoundError when no Holding was found.
func (hq *HoldingQuery) First(ctx context.Context) (*Holding, error) {
	nodes, err := hq.Limit(1).All(setContextOp(ctx, hq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{holding.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (hq *HoldingQuery) FirstX(ctx context.Context) *Holding {
	node, err := hq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Holding ID from the query.
// Returns a *NotFoundError when no Holding ID was found.
func (hq *HoldingQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = hq.Limit(1).IDs(setContextOp(ctx, hq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{holding.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (hq *HoldingQuery) FirstIDX(ctx context.Context) int {
	id, err := hq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Holding entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Holding entity is found.
// Returns a *NotFoundError when no Holding entities are found.
func (hq *HoldingQuery) Only(ctx context.Context) (*Holding, error) {
	nodes, err := hq.Limit(2).All(setContextOp(ctx, hq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{holding.Label}
	default:
		return nil, &NotSingularError{holding.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (hq *HoldingQuery) OnlyX(ctx context.Context) *Holding {
	node, err := hq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Holding ID in the query.
// Returns a *NotSingularError when more than one Holding ID is found.
// Returns a *NotFoundError when no entities are found.
func (hq *HoldingQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = hq.Limit(2).IDs(setContextOp(ctx, hq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{holding.Label}
	default:
		err = &NotSingularError{holding.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (hq *HoldingQuery) OnlyIDX(ctx context.Context) int {
	id, err := hq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Holdings.
func (hq *HoldingQuery) All(ctx context.Context) ([]*Holding, error) {
	ctx = setContextOp(ctx, hq.ctx, ent.OpQueryAll)
	if err := hq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Holding, *HoldingQuery]()
	return withInterceptors[[]*Holding](ctx, hq, qr, hq.inters)
}

// AllX is like All, but panics if an error occurs.
func (hq *HoldingQuery) AllX(ctx context.Context) []*Holding {
	nodes, err := hq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Holding IDs.
func (hq *HoldingQuery) IDs(ctx context.Context) (ids []int, err error) {
	if hq.ctx.Unique == nil && hq.path != nil {
		hq.Unique(true)
	}
	ctx = setContextOp(ctx, hq.ctx, ent.OpQueryIDs)
	if err = hq.Select(holding.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (hq *HoldingQuery) IDsX(ctx context.Context) []int {
	ids, err := hq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (hq *HoldingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, hq.ctx, ent.OpQueryCount)
	if err := hq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, hq, querierCount[*HoldingQuery](), hq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (hq *HoldingQuery) CountX(ctx context.Context) int {
	count, err := hq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (hq *HoldingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, hq.ctx, ent.OpQueryExist)
	switch _, err := hq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (hq *HoldingQuery) ExistX(ctx context.Context) bool {
	exist, err := hq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the HoldingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (hq *HoldingQuery) Clone() *HoldingQuery {
	if hq == nil {
		return nil
	}
	return &HoldingQuery{
		config:        hq.config,
		ctx:           hq.ctx.Clone(),
		order:         append([]holding.OrderOption{}, hq.order...),
		inters:        append([]Interceptor{}, hq.inters...),
		predicates:    append([]predicate.Holding{}, hq.predicates...),
		withAsset:     hq.withAsset.Clone(),
		withPortfolio: hq.withPortfolio.Clone(),
		withAccount:   hq.withAccount.Clone(),
		// clone intermediate query.
		sql:  hq.sql.Clone(),
		path: hq.path,
	}
}

// WithAsset tells the query-builder to eager-load the nodes that are connected to
// the "asset" edge. The optional arguments are used to configure the query builder of the edge.
func (hq *HoldingQuery) WithAsset(opts ...func(*AssetQuery)) *HoldingQuery {
	query := (&AssetClient{config: hq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	hq.withAsset = query
	return hq
}

// WithPortfolio tells the query-builder to eager-load the nodes that are connected to
// the "portfolio" edge. The optional arguments are used to configure the query builder of the edge.
func (hq *HoldingQuery) WithPortfolio(opts ...func(*PortfolioQuery)) *HoldingQuery {
	query := (&PortfolioClient{config: hq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	hq.withPortfolio = query
	return hq
}

// WithAccount tells the query-builder to eager-load the nodes that are connected to
// the "account" edge. The optional arguments are used to configure the query builder of the edge.
func (hq *HoldingQuery) WithAccount(opts ...func(*AccountQuery)) *HoldingQuery {
	query := (&AccountClient{config: hq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	hq.withAccount = query
	return hq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UUID uuid.UUID `json:"uuid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Holding.Query().
//		GroupBy(holding.FieldUUID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (hq *HoldingQuery) GroupBy(field string, fields ...string) *HoldingGroupBy {
	hq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &HoldingGroupBy{build: hq}
	grbuild.flds = &hq.ctx.Fields
	grbuild.label = holding.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UUID uuid.UUID `json:"uuid,omitempty"`
//	}
//
//	client.Holding.Query().
//		Select(holding.FieldUUID).
//		Scan(ctx, &v)
func (hq *HoldingQuery) Select(fields ...string) *HoldingSelect {
	hq.ctx.Fields = append(hq.ctx.Fields, fields...)
	sbuild := &HoldingSelect{HoldingQuery: hq}
	sbuild.label = holding.Label
	sbuild.flds, sbuild.scan = &hq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a HoldingSelect configured with the given aggregations.
func (hq *HoldingQuery) Aggregate(fns ...AggregateFunc) *HoldingSelect {
	return hq.Select().Aggregate(fns...)
}

func (hq *HoldingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range hq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, hq); err != nil {
				return err
			}
		}
	}
	for _, f := range hq.ctx.Fields {
		if !holding.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if hq.path != nil {
		prev, err := hq.path(ctx)
		if err != nil {
			return err
		}
		hq.sql = prev
	}
	return nil
}

func (hq *HoldingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Holding, error) {
	var (
		nodes       = []*Holding{}
		withFKs     = hq.withFKs
		_spec       = hq.querySpec()
		loadedTypes = [3]bool{
			hq.withAsset != nil,
			hq.withPortfolio != nil,
			hq.withAccount != nil,
		}
	)
	if hq.withAsset != nil || hq.withPortfolio != nil || hq.withAccount != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, holding.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Holding).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Holding{config: hq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, hq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := hq.withAsset; query != nil {
		if err := hq.loadAsset(ctx, query, nodes, nil,
			func(n *Holding, e *Asset) { n.Edges.Asset = e }); err != nil {
			return nil, err
		}
	}
	if query := hq.withPortfolio; query != nil {
		if err := hq.loadPortfolio(ctx, query, nodes, nil,
			func(n *Holding, e *Portfolio) { n.Edges.Portfolio = e }); err != nil {
			return nil, err
		}
	}
	if query := hq.withAccount; query != nil {
		if err := hq.loadAccount(ctx, query, nodes, nil,
			func(n *Holding, e *Account) { n.Edges.Account = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (hq *HoldingQuery) loadAsset(ctx context.Context, query *AssetQuery, nodes []*Holding, init func(*Holding), assign func(*Holding, *Asset)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Holding)
	for i := range nodes {
		if nodes[i].asset_holdings == nil {
			continue
		}
		fk := *nodes[i].asset_holdings
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(asset.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "asset_holdings" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (hq *HoldingQuery) loadPortfolio(ctx context.Context, query *PortfolioQuery, nodes []*Holding, init func(*Holding), assign func(*Holding, *Portfolio)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Holding)
	for i := range nodes {
		if nodes[i].portfolio_holdings == nil {
			continue
		}
		fk := *nodes[i].portfolio_holdings
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(portfolio.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "portfolio_holdings" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (hq *HoldingQuery) loadAccount(ctx context.Context, query *AccountQuery, nodes []*Holding, init func(*Holding), assign func(*Holding, *Account)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Holding)
	for i := range nodes {
		if nodes[i].account_holdings == nil {
			continue
		}
		fk := *nodes[i].account_holdings
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(account.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "account_holdings" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (hq *HoldingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := hq.querySpec()
	_spec.Node.Columns = hq.ctx.Fields
	if len(hq.ctx.Fields) > 0 {
		_spec.Unique = hq.ctx.Unique != nil && *hq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, hq.driver, _spec)
}

func (hq *HoldingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(holding.Table, holding.Columns, sqlgraph.NewFieldSpec(holding.FieldID, field.TypeInt))
	_spec.From = hq.sql
	if unique := hq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if hq.path != nil {
		_spec.Unique = true
	}
	if fields := hq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, holding.FieldID)
		for i := range fields {
			if fields[i] != holding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := hq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := hq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := hq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := hq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (hq *HoldingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(hq.driver.Dialect())
	t1 := builder.Table(holding.Table)
	columns := hq.ctx.Fields
	if len(columns) == 0 {
		columns = holding.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if hq.sql != nil {
		selector = hq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if hq.ctx.Unique != nil && *hq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range hq.predicates {
		p(selector)
	}
	for _, p := range hq.order {
		p(selector)
	}
	if offset := hq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := hq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// HoldingGroupBy is the group-by builder for Holding entities.
type HoldingGroupBy struct {
	selector
	build *HoldingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (hgb *HoldingGroupBy) Aggregate(fns ...AggregateFunc) *HoldingGroupBy {
	hgb.fns = append(hgb.fns, fns...)
	return hgb
}

// Scan applies the selector query and scans the result into the given value.
func (hgb *HoldingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hgb.build.ctx, ent.OpQueryGroupBy)
	if err := hgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HoldingQuery, *HoldingGroupBy](ctx, hgb.build, hgb, hgb.build.inters, v)
}

func (hgb *HoldingGroupBy) sqlScan(ctx context.Context, root *HoldingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(hgb.fns))
	for _, fn := range hgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*hgb.flds)+len(hgb.fns))
		for _, f := range *hgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*hgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// HoldingSelect is the builder for selecting fields of Holding entities.
type HoldingSelect struct {
	*HoldingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (hs *HoldingSelect) Aggregate(fns ...AggregateFunc) *HoldingSelect {
	hs.fns = append(hs.fns, fns...)
	return hs
}

// Scan applies the selector query and scans the result into the given value.
func (hs *HoldingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hs.ctx, ent.OpQuerySelect)
	if err := hs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HoldingQuery, *HoldingSelect](ctx, hs.HoldingQuery, hs, hs.inters, v)
}

func (hs *HoldingSelect) sqlScan(ctx context.Context, root *HoldingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(hs.fns))
	for _, fn := range hs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*hs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
