// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/foxcool/greedy-eye/internal/services/storage/ent/account"
	"github.com/foxcool/greedy-eye/internal/services/storage/ent/asset"
	"github.com/foxcool/greedy-eye/internal/services/storage/ent/holding"
	"github.com/foxcool/greedy-eye/internal/services/storage/ent/portfolio"
	"github.com/google/uuid"
)

// Holding is the model entity for the Holding schema.
type Holding struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UUID holds the value of the "uuid" field.
	UUID uuid.UUID `json:"uuid,omitempty"`
	// AssetID holds the value of the "asset_id" field.
	AssetID int `json:"asset_id,omitempty"`
	// PortfolioID holds the value of the "portfolio_id" field.
	PortfolioID int `json:"portfolio_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int `json:"account_id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount int64 `json:"amount,omitempty"`
	// Precision holds the value of the "precision" field.
	Precision uint32 `json:"precision,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the HoldingQuery when eager-loading is set.
	Edges        HoldingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// HoldingEdges holds the relations/edges for other nodes in the graph.
type HoldingEdges struct {
	// Asset holds the value of the asset edge.
	Asset *Asset `json:"asset,omitempty"`
	// Portfolio holds the value of the portfolio edge.
	Portfolio *Portfolio `json:"portfolio,omitempty"`
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// AssetOrErr returns the Asset value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e HoldingEdges) AssetOrErr() (*Asset, error) {
	if e.Asset != nil {
		return e.Asset, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: asset.Label}
	}
	return nil, &NotLoadedError{edge: "asset"}
}

// PortfolioOrErr returns the Portfolio value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e HoldingEdges) PortfolioOrErr() (*Portfolio, error) {
	if e.Portfolio != nil {
		return e.Portfolio, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: portfolio.Label}
	}
	return nil, &NotLoadedError{edge: "portfolio"}
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e HoldingEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Holding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case holding.FieldID, holding.FieldAssetID, holding.FieldPortfolioID, holding.FieldAccountID, holding.FieldAmount, holding.FieldPrecision:
			values[i] = new(sql.NullInt64)
		case holding.FieldCreatedAt, holding.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case holding.FieldUUID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Holding fields.
func (h *Holding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case holding.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			h.ID = int(value.Int64)
		case holding.FieldUUID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field uuid", values[i])
			} else if value != nil {
				h.UUID = *value
			}
		case holding.FieldAssetID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field asset_id", values[i])
			} else if value.Valid {
				h.AssetID = int(value.Int64)
			}
		case holding.FieldPortfolioID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field portfolio_id", values[i])
			} else if value.Valid {
				h.PortfolioID = int(value.Int64)
			}
		case holding.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				h.AccountID = int(value.Int64)
			}
		case holding.FieldAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				h.Amount = value.Int64
			}
		case holding.FieldPrecision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field precision", values[i])
			} else if value.Valid {
				h.Precision = uint32(value.Int64)
			}
		case holding.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				h.CreatedAt = value.Time
			}
		case holding.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				h.UpdatedAt = value.Time
			}
		default:
			h.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Holding.
// This includes values selected through modifiers, order, etc.
func (h *Holding) Value(name string) (ent.Value, error) {
	return h.selectValues.Get(name)
}

// QueryAsset queries the "asset" edge of the Holding entity.
func (h *Holding) QueryAsset() *AssetQuery {
	return NewHoldingClient(h.config).QueryAsset(h)
}

// QueryPortfolio queries the "portfolio" edge of the Holding entity.
func (h *Holding) QueryPortfolio() *PortfolioQuery {
	return NewHoldingClient(h.config).QueryPortfolio(h)
}

// QueryAccount queries the "account" edge of the Holding entity.
func (h *Holding) QueryAccount() *AccountQuery {
	return NewHoldingClient(h.config).QueryAccount(h)
}

// Update returns a builder for updating this Holding.
// Note that you need to call Holding.Unwrap() before calling this method if this Holding
// was returned from a transaction, and the transaction was committed or rolled back.
func (h *Holding) Update() *HoldingUpdateOne {
	return NewHoldingClient(h.config).UpdateOne(h)
}

// Unwrap unwraps the Holding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (h *Holding) Unwrap() *Holding {
	_tx, ok := h.config.driver.(*txDriver)
	if !ok {
		panic("ent: Holding is not a transactional entity")
	}
	h.config.driver = _tx.drv
	return h
}

// String implements the fmt.Stringer.
func (h *Holding) String() string {
	var builder strings.Builder
	builder.WriteString("Holding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", h.ID))
	builder.WriteString("uuid=")
	builder.WriteString(fmt.Sprintf("%v", h.UUID))
	builder.WriteString(", ")
	builder.WriteString("asset_id=")
	builder.WriteString(fmt.Sprintf("%v", h.AssetID))
	builder.WriteString(", ")
	builder.WriteString("portfolio_id=")
	builder.WriteString(fmt.Sprintf("%v", h.PortfolioID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", h.AccountID))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", h.Amount))
	builder.WriteString(", ")
	builder.WriteString("precision=")
	builder.WriteString(fmt.Sprintf("%v", h.Precision))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(h.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(h.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Holdings is a parsable slice of Holding.
type Holdings []*Holding
