// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/foxcool/greedy-eye/pkg/ent/holding"
	"github.com/foxcool/greedy-eye/pkg/ent/portfolio"
	"github.com/foxcool/greedy-eye/pkg/ent/predicate"
	"github.com/foxcool/greedy-eye/pkg/ent/tag"
	"github.com/foxcool/greedy-eye/pkg/ent/user"
)

// PortfolioQuery is the builder for querying Portfolio entities.
type PortfolioQuery struct {
	config
	ctx          *QueryContext
	order        []portfolio.OrderOption
	inters       []Interceptor
	predicates   []predicate.Portfolio
	withOwners   *UserQuery
	withHoldings *HoldingQuery
	withTags     *TagQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PortfolioQuery builder.
func (pq *PortfolioQuery) Where(ps ...predicate.Portfolio) *PortfolioQuery {
	pq.predicates = append(pq.predicates, ps...)
	return pq
}

// Limit the number of records to be returned by this query.
func (pq *PortfolioQuery) Limit(limit int) *PortfolioQuery {
	pq.ctx.Limit = &limit
	return pq
}

// Offset to start from.
func (pq *PortfolioQuery) Offset(offset int) *PortfolioQuery {
	pq.ctx.Offset = &offset
	return pq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pq *PortfolioQuery) Unique(unique bool) *PortfolioQuery {
	pq.ctx.Unique = &unique
	return pq
}

// Order specifies how the records should be ordered.
func (pq *PortfolioQuery) Order(o ...portfolio.OrderOption) *PortfolioQuery {
	pq.order = append(pq.order, o...)
	return pq
}

// QueryOwners chains the current query on the "owners" edge.
func (pq *PortfolioQuery) QueryOwners() *UserQuery {
	query := (&UserClient{config: pq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(portfolio.Table, portfolio.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, portfolio.OwnersTable, portfolio.OwnersPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryHoldings chains the current query on the "holdings" edge.
func (pq *PortfolioQuery) QueryHoldings() *HoldingQuery {
	query := (&HoldingClient{config: pq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(portfolio.Table, portfolio.FieldID, selector),
			sqlgraph.To(holding.Table, holding.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, portfolio.HoldingsTable, portfolio.HoldingsColumn),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTags chains the current query on the "tags" edge.
func (pq *PortfolioQuery) QueryTags() *TagQuery {
	query := (&TagClient{config: pq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(portfolio.Table, portfolio.FieldID, selector),
			sqlgraph.To(tag.Table, tag.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, portfolio.TagsTable, portfolio.TagsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Portfolio entity from the query.
// Returns a *NotFoundError when no Portfolio was found.
func (pq *PortfolioQuery) First(ctx context.Context) (*Portfolio, error) {
	nodes, err := pq.Limit(1).All(setContextOp(ctx, pq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{portfolio.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pq *PortfolioQuery) FirstX(ctx context.Context) *Portfolio {
	node, err := pq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Portfolio ID from the query.
// Returns a *NotFoundError when no Portfolio ID was found.
func (pq *PortfolioQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pq.Limit(1).IDs(setContextOp(ctx, pq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{portfolio.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pq *PortfolioQuery) FirstIDX(ctx context.Context) int {
	id, err := pq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Portfolio entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Portfolio entity is found.
// Returns a *NotFoundError when no Portfolio entities are found.
func (pq *PortfolioQuery) Only(ctx context.Context) (*Portfolio, error) {
	nodes, err := pq.Limit(2).All(setContextOp(ctx, pq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{portfolio.Label}
	default:
		return nil, &NotSingularError{portfolio.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pq *PortfolioQuery) OnlyX(ctx context.Context) *Portfolio {
	node, err := pq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Portfolio ID in the query.
// Returns a *NotSingularError when more than one Portfolio ID is found.
// Returns a *NotFoundError when no entities are found.
func (pq *PortfolioQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pq.Limit(2).IDs(setContextOp(ctx, pq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{portfolio.Label}
	default:
		err = &NotSingularError{portfolio.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pq *PortfolioQuery) OnlyIDX(ctx context.Context) int {
	id, err := pq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Portfolios.
func (pq *PortfolioQuery) All(ctx context.Context) ([]*Portfolio, error) {
	ctx = setContextOp(ctx, pq.ctx, ent.OpQueryAll)
	if err := pq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Portfolio, *PortfolioQuery]()
	return withInterceptors[[]*Portfolio](ctx, pq, qr, pq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pq *PortfolioQuery) AllX(ctx context.Context) []*Portfolio {
	nodes, err := pq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Portfolio IDs.
func (pq *PortfolioQuery) IDs(ctx context.Context) (ids []int, err error) {
	if pq.ctx.Unique == nil && pq.path != nil {
		pq.Unique(true)
	}
	ctx = setContextOp(ctx, pq.ctx, ent.OpQueryIDs)
	if err = pq.Select(portfolio.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pq *PortfolioQuery) IDsX(ctx context.Context) []int {
	ids, err := pq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pq *PortfolioQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pq.ctx, ent.OpQueryCount)
	if err := pq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pq, querierCount[*PortfolioQuery](), pq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pq *PortfolioQuery) CountX(ctx context.Context) int {
	count, err := pq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pq *PortfolioQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pq.ctx, ent.OpQueryExist)
	switch _, err := pq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pq *PortfolioQuery) ExistX(ctx context.Context) bool {
	exist, err := pq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PortfolioQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pq *PortfolioQuery) Clone() *PortfolioQuery {
	if pq == nil {
		return nil
	}
	return &PortfolioQuery{
		config:       pq.config,
		ctx:          pq.ctx.Clone(),
		order:        append([]portfolio.OrderOption{}, pq.order...),
		inters:       append([]Interceptor{}, pq.inters...),
		predicates:   append([]predicate.Portfolio{}, pq.predicates...),
		withOwners:   pq.withOwners.Clone(),
		withHoldings: pq.withHoldings.Clone(),
		withTags:     pq.withTags.Clone(),
		// clone intermediate query.
		sql:  pq.sql.Clone(),
		path: pq.path,
	}
}

// WithOwners tells the query-builder to eager-load the nodes that are connected to
// the "owners" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *PortfolioQuery) WithOwners(opts ...func(*UserQuery)) *PortfolioQuery {
	query := (&UserClient{config: pq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pq.withOwners = query
	return pq
}

// WithHoldings tells the query-builder to eager-load the nodes that are connected to
// the "holdings" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *PortfolioQuery) WithHoldings(opts ...func(*HoldingQuery)) *PortfolioQuery {
	query := (&HoldingClient{config: pq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pq.withHoldings = query
	return pq
}

// WithTags tells the query-builder to eager-load the nodes that are connected to
// the "tags" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *PortfolioQuery) WithTags(opts ...func(*TagQuery)) *PortfolioQuery {
	query := (&TagClient{config: pq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pq.withTags = query
	return pq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (pq *PortfolioQuery) GroupBy(field string, fields ...string) *PortfolioGroupBy {
	pq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PortfolioGroupBy{build: pq}
	grbuild.flds = &pq.ctx.Fields
	grbuild.label = portfolio.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (pq *PortfolioQuery) Select(fields ...string) *PortfolioSelect {
	pq.ctx.Fields = append(pq.ctx.Fields, fields...)
	sbuild := &PortfolioSelect{PortfolioQuery: pq}
	sbuild.label = portfolio.Label
	sbuild.flds, sbuild.scan = &pq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PortfolioSelect configured with the given aggregations.
func (pq *PortfolioQuery) Aggregate(fns ...AggregateFunc) *PortfolioSelect {
	return pq.Select().Aggregate(fns...)
}

func (pq *PortfolioQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pq); err != nil {
				return err
			}
		}
	}
	for _, f := range pq.ctx.Fields {
		if !portfolio.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pq.path != nil {
		prev, err := pq.path(ctx)
		if err != nil {
			return err
		}
		pq.sql = prev
	}
	return nil
}

func (pq *PortfolioQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Portfolio, error) {
	var (
		nodes       = []*Portfolio{}
		_spec       = pq.querySpec()
		loadedTypes = [3]bool{
			pq.withOwners != nil,
			pq.withHoldings != nil,
			pq.withTags != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Portfolio).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Portfolio{config: pq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := pq.withOwners; query != nil {
		if err := pq.loadOwners(ctx, query, nodes,
			func(n *Portfolio) { n.Edges.Owners = []*User{} },
			func(n *Portfolio, e *User) { n.Edges.Owners = append(n.Edges.Owners, e) }); err != nil {
			return nil, err
		}
	}
	if query := pq.withHoldings; query != nil {
		if err := pq.loadHoldings(ctx, query, nodes,
			func(n *Portfolio) { n.Edges.Holdings = []*Holding{} },
			func(n *Portfolio, e *Holding) { n.Edges.Holdings = append(n.Edges.Holdings, e) }); err != nil {
			return nil, err
		}
	}
	if query := pq.withTags; query != nil {
		if err := pq.loadTags(ctx, query, nodes,
			func(n *Portfolio) { n.Edges.Tags = []*Tag{} },
			func(n *Portfolio, e *Tag) { n.Edges.Tags = append(n.Edges.Tags, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pq *PortfolioQuery) loadOwners(ctx context.Context, query *UserQuery, nodes []*Portfolio, init func(*Portfolio), assign func(*Portfolio, *User)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Portfolio)
	nids := make(map[int]map[*Portfolio]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(portfolio.OwnersTable)
		s.Join(joinT).On(s.C(user.FieldID), joinT.C(portfolio.OwnersPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(portfolio.OwnersPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(portfolio.OwnersPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Portfolio]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*User](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "owners" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (pq *PortfolioQuery) loadHoldings(ctx context.Context, query *HoldingQuery, nodes []*Portfolio, init func(*Portfolio), assign func(*Portfolio, *Holding)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Portfolio)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Holding(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(portfolio.HoldingsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.portfolio_holdings
		if fk == nil {
			return fmt.Errorf(`foreign-key "portfolio_holdings" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "portfolio_holdings" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (pq *PortfolioQuery) loadTags(ctx context.Context, query *TagQuery, nodes []*Portfolio, init func(*Portfolio), assign func(*Portfolio, *Tag)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Portfolio)
	nids := make(map[int]map[*Portfolio]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(portfolio.TagsTable)
		s.Join(joinT).On(s.C(tag.FieldID), joinT.C(portfolio.TagsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(portfolio.TagsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(portfolio.TagsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Portfolio]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Tag](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "tags" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (pq *PortfolioQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pq.querySpec()
	_spec.Node.Columns = pq.ctx.Fields
	if len(pq.ctx.Fields) > 0 {
		_spec.Unique = pq.ctx.Unique != nil && *pq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pq.driver, _spec)
}

func (pq *PortfolioQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(portfolio.Table, portfolio.Columns, sqlgraph.NewFieldSpec(portfolio.FieldID, field.TypeInt))
	_spec.From = pq.sql
	if unique := pq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pq.path != nil {
		_spec.Unique = true
	}
	if fields := pq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, portfolio.FieldID)
		for i := range fields {
			if fields[i] != portfolio.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pq *PortfolioQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pq.driver.Dialect())
	t1 := builder.Table(portfolio.Table)
	columns := pq.ctx.Fields
	if len(columns) == 0 {
		columns = portfolio.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pq.sql != nil {
		selector = pq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pq.ctx.Unique != nil && *pq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pq.predicates {
		p(selector)
	}
	for _, p := range pq.order {
		p(selector)
	}
	if offset := pq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PortfolioGroupBy is the group-by builder for Portfolio entities.
type PortfolioGroupBy struct {
	selector
	build *PortfolioQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pgb *PortfolioGroupBy) Aggregate(fns ...AggregateFunc) *PortfolioGroupBy {
	pgb.fns = append(pgb.fns, fns...)
	return pgb
}

// Scan applies the selector query and scans the result into the given value.
func (pgb *PortfolioGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pgb.build.ctx, ent.OpQueryGroupBy)
	if err := pgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PortfolioQuery, *PortfolioGroupBy](ctx, pgb.build, pgb, pgb.build.inters, v)
}

func (pgb *PortfolioGroupBy) sqlScan(ctx context.Context, root *PortfolioQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pgb.fns))
	for _, fn := range pgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pgb.flds)+len(pgb.fns))
		for _, f := range *pgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PortfolioSelect is the builder for selecting fields of Portfolio entities.
type PortfolioSelect struct {
	*PortfolioQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ps *PortfolioSelect) Aggregate(fns ...AggregateFunc) *PortfolioSelect {
	ps.fns = append(ps.fns, fns...)
	return ps
}

// Scan applies the selector query and scans the result into the given value.
func (ps *PortfolioSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ps.ctx, ent.OpQuerySelect)
	if err := ps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PortfolioQuery, *PortfolioSelect](ctx, ps.PortfolioQuery, ps, ps.inters, v)
}

func (ps *PortfolioSelect) sqlScan(ctx context.Context, root *PortfolioQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ps.fns))
	for _, fn := range ps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
