// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/foxcool/greedy-eye/internal/services/storage/ent/asset"
	"github.com/foxcool/greedy-eye/internal/services/storage/ent/price"
	"github.com/google/uuid"
)

// Price is the model entity for the Price schema.
type Price struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UUID holds the value of the "uuid" field.
	UUID uuid.UUID `json:"uuid,omitempty"`
	// SourceID holds the value of the "source_id" field.
	SourceID string `json:"source_id,omitempty"`
	// AssetID holds the value of the "asset_id" field.
	AssetID int `json:"asset_id,omitempty"`
	// BaseAssetID holds the value of the "base_asset_id" field.
	BaseAssetID int `json:"base_asset_id,omitempty"`
	// Interval holds the value of the "interval" field.
	Interval string `json:"interval,omitempty"`
	// Decimals holds the value of the "decimals" field.
	Decimals uint32 `json:"decimals,omitempty"`
	// Last holds the value of the "last" field.
	Last int64 `json:"last,omitempty"`
	// Open holds the value of the "open" field.
	Open int64 `json:"open,omitempty"`
	// High holds the value of the "high" field.
	High int64 `json:"high,omitempty"`
	// Low holds the value of the "low" field.
	Low int64 `json:"low,omitempty"`
	// Close holds the value of the "close" field.
	Close int64 `json:"close,omitempty"`
	// Volume holds the value of the "volume" field.
	Volume int64 `json:"volume,omitempty"`
	// Timestamp holds the value of the "timestamp" field.
	Timestamp time.Time `json:"timestamp,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PriceQuery when eager-loading is set.
	Edges        PriceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PriceEdges holds the relations/edges for other nodes in the graph.
type PriceEdges struct {
	// Asset holds the value of the asset edge.
	Asset *Asset `json:"asset,omitempty"`
	// BaseAsset holds the value of the base_asset edge.
	BaseAsset *Asset `json:"base_asset,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AssetOrErr returns the Asset value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PriceEdges) AssetOrErr() (*Asset, error) {
	if e.Asset != nil {
		return e.Asset, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: asset.Label}
	}
	return nil, &NotLoadedError{edge: "asset"}
}

// BaseAssetOrErr returns the BaseAsset value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PriceEdges) BaseAssetOrErr() (*Asset, error) {
	if e.BaseAsset != nil {
		return e.BaseAsset, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: asset.Label}
	}
	return nil, &NotLoadedError{edge: "base_asset"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Price) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case price.FieldID, price.FieldAssetID, price.FieldBaseAssetID, price.FieldDecimals, price.FieldLast, price.FieldOpen, price.FieldHigh, price.FieldLow, price.FieldClose, price.FieldVolume:
			values[i] = new(sql.NullInt64)
		case price.FieldSourceID, price.FieldInterval:
			values[i] = new(sql.NullString)
		case price.FieldTimestamp:
			values[i] = new(sql.NullTime)
		case price.FieldUUID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Price fields.
func (pr *Price) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case price.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pr.ID = int(value.Int64)
		case price.FieldUUID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field uuid", values[i])
			} else if value != nil {
				pr.UUID = *value
			}
		case price.FieldSourceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_id", values[i])
			} else if value.Valid {
				pr.SourceID = value.String
			}
		case price.FieldAssetID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field asset_id", values[i])
			} else if value.Valid {
				pr.AssetID = int(value.Int64)
			}
		case price.FieldBaseAssetID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field base_asset_id", values[i])
			} else if value.Valid {
				pr.BaseAssetID = int(value.Int64)
			}
		case price.FieldInterval:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field interval", values[i])
			} else if value.Valid {
				pr.Interval = value.String
			}
		case price.FieldDecimals:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field decimals", values[i])
			} else if value.Valid {
				pr.Decimals = uint32(value.Int64)
			}
		case price.FieldLast:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last", values[i])
			} else if value.Valid {
				pr.Last = value.Int64
			}
		case price.FieldOpen:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field open", values[i])
			} else if value.Valid {
				pr.Open = value.Int64
			}
		case price.FieldHigh:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field high", values[i])
			} else if value.Valid {
				pr.High = value.Int64
			}
		case price.FieldLow:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field low", values[i])
			} else if value.Valid {
				pr.Low = value.Int64
			}
		case price.FieldClose:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field close", values[i])
			} else if value.Valid {
				pr.Close = value.Int64
			}
		case price.FieldVolume:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field volume", values[i])
			} else if value.Valid {
				pr.Volume = value.Int64
			}
		case price.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field timestamp", values[i])
			} else if value.Valid {
				pr.Timestamp = value.Time
			}
		default:
			pr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Price.
// This includes values selected through modifiers, order, etc.
func (pr *Price) Value(name string) (ent.Value, error) {
	return pr.selectValues.Get(name)
}

// QueryAsset queries the "asset" edge of the Price entity.
func (pr *Price) QueryAsset() *AssetQuery {
	return NewPriceClient(pr.config).QueryAsset(pr)
}

// QueryBaseAsset queries the "base_asset" edge of the Price entity.
func (pr *Price) QueryBaseAsset() *AssetQuery {
	return NewPriceClient(pr.config).QueryBaseAsset(pr)
}

// Update returns a builder for updating this Price.
// Note that you need to call Price.Unwrap() before calling this method if this Price
// was returned from a transaction, and the transaction was committed or rolled back.
func (pr *Price) Update() *PriceUpdateOne {
	return NewPriceClient(pr.config).UpdateOne(pr)
}

// Unwrap unwraps the Price entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pr *Price) Unwrap() *Price {
	_tx, ok := pr.config.driver.(*txDriver)
	if !ok {
		panic("ent: Price is not a transactional entity")
	}
	pr.config.driver = _tx.drv
	return pr
}

// String implements the fmt.Stringer.
func (pr *Price) String() string {
	var builder strings.Builder
	builder.WriteString("Price(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pr.ID))
	builder.WriteString("uuid=")
	builder.WriteString(fmt.Sprintf("%v", pr.UUID))
	builder.WriteString(", ")
	builder.WriteString("source_id=")
	builder.WriteString(pr.SourceID)
	builder.WriteString(", ")
	builder.WriteString("asset_id=")
	builder.WriteString(fmt.Sprintf("%v", pr.AssetID))
	builder.WriteString(", ")
	builder.WriteString("base_asset_id=")
	builder.WriteString(fmt.Sprintf("%v", pr.BaseAssetID))
	builder.WriteString(", ")
	builder.WriteString("interval=")
	builder.WriteString(pr.Interval)
	builder.WriteString(", ")
	builder.WriteString("decimals=")
	builder.WriteString(fmt.Sprintf("%v", pr.Decimals))
	builder.WriteString(", ")
	builder.WriteString("last=")
	builder.WriteString(fmt.Sprintf("%v", pr.Last))
	builder.WriteString(", ")
	builder.WriteString("open=")
	builder.WriteString(fmt.Sprintf("%v", pr.Open))
	builder.WriteString(", ")
	builder.WriteString("high=")
	builder.WriteString(fmt.Sprintf("%v", pr.High))
	builder.WriteString(", ")
	builder.WriteString("low=")
	builder.WriteString(fmt.Sprintf("%v", pr.Low))
	builder.WriteString(", ")
	builder.WriteString("close=")
	builder.WriteString(fmt.Sprintf("%v", pr.Close))
	builder.WriteString(", ")
	builder.WriteString("volume=")
	builder.WriteString(fmt.Sprintf("%v", pr.Volume))
	builder.WriteString(", ")
	builder.WriteString("timestamp=")
	builder.WriteString(pr.Timestamp.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Prices is a parsable slice of Price.
type Prices []*Price
