// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/foxcool/greedy-eye/pkg/ent/asset"
	"github.com/foxcool/greedy-eye/pkg/ent/price"
	"github.com/shopspring/decimal"
)

// Price is the model entity for the Price schema.
type Price struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// LastPrice holds the value of the "last_price" field.
	LastPrice decimal.Decimal `json:"last_price,omitempty"`
	// Ask holds the value of the "ask" field.
	Ask decimal.Decimal `json:"ask,omitempty"`
	// Bid holds the value of the "bid" field.
	Bid decimal.Decimal `json:"bid,omitempty"`
	// Time holds the value of the "time" field.
	Time time.Time `json:"time,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PriceQuery when eager-loading is set.
	Edges             PriceEdges `json:"edges"`
	price_base_asset  *int
	price_quote_asset *int
	selectValues      sql.SelectValues
}

// PriceEdges holds the relations/edges for other nodes in the graph.
type PriceEdges struct {
	// BaseAsset holds the value of the base_asset edge.
	BaseAsset *Asset `json:"base_asset,omitempty"`
	// QuoteAsset holds the value of the quote_asset edge.
	QuoteAsset *Asset `json:"quote_asset,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// BaseAssetOrErr returns the BaseAsset value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PriceEdges) BaseAssetOrErr() (*Asset, error) {
	if e.BaseAsset != nil {
		return e.BaseAsset, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: asset.Label}
	}
	return nil, &NotLoadedError{edge: "base_asset"}
}

// QuoteAssetOrErr returns the QuoteAsset value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PriceEdges) QuoteAssetOrErr() (*Asset, error) {
	if e.QuoteAsset != nil {
		return e.QuoteAsset, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: asset.Label}
	}
	return nil, &NotLoadedError{edge: "quote_asset"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Price) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case price.FieldLastPrice, price.FieldAsk, price.FieldBid:
			values[i] = new(decimal.Decimal)
		case price.FieldID:
			values[i] = new(sql.NullInt64)
		case price.FieldSource:
			values[i] = new(sql.NullString)
		case price.FieldTime:
			values[i] = new(sql.NullTime)
		case price.ForeignKeys[0]: // price_base_asset
			values[i] = new(sql.NullInt64)
		case price.ForeignKeys[1]: // price_quote_asset
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Price fields.
func (pr *Price) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case price.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pr.ID = int(value.Int64)
		case price.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				pr.Source = value.String
			}
		case price.FieldLastPrice:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field last_price", values[i])
			} else if value != nil {
				pr.LastPrice = *value
			}
		case price.FieldAsk:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field ask", values[i])
			} else if value != nil {
				pr.Ask = *value
			}
		case price.FieldBid:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field bid", values[i])
			} else if value != nil {
				pr.Bid = *value
			}
		case price.FieldTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field time", values[i])
			} else if value.Valid {
				pr.Time = value.Time
			}
		case price.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field price_base_asset", value)
			} else if value.Valid {
				pr.price_base_asset = new(int)
				*pr.price_base_asset = int(value.Int64)
			}
		case price.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field price_quote_asset", value)
			} else if value.Valid {
				pr.price_quote_asset = new(int)
				*pr.price_quote_asset = int(value.Int64)
			}
		default:
			pr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Price.
// This includes values selected through modifiers, order, etc.
func (pr *Price) Value(name string) (ent.Value, error) {
	return pr.selectValues.Get(name)
}

// QueryBaseAsset queries the "base_asset" edge of the Price entity.
func (pr *Price) QueryBaseAsset() *AssetQuery {
	return NewPriceClient(pr.config).QueryBaseAsset(pr)
}

// QueryQuoteAsset queries the "quote_asset" edge of the Price entity.
func (pr *Price) QueryQuoteAsset() *AssetQuery {
	return NewPriceClient(pr.config).QueryQuoteAsset(pr)
}

// Update returns a builder for updating this Price.
// Note that you need to call Price.Unwrap() before calling this method if this Price
// was returned from a transaction, and the transaction was committed or rolled back.
func (pr *Price) Update() *PriceUpdateOne {
	return NewPriceClient(pr.config).UpdateOne(pr)
}

// Unwrap unwraps the Price entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pr *Price) Unwrap() *Price {
	_tx, ok := pr.config.driver.(*txDriver)
	if !ok {
		panic("ent: Price is not a transactional entity")
	}
	pr.config.driver = _tx.drv
	return pr
}

// String implements the fmt.Stringer.
func (pr *Price) String() string {
	var builder strings.Builder
	builder.WriteString("Price(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pr.ID))
	builder.WriteString("source=")
	builder.WriteString(pr.Source)
	builder.WriteString(", ")
	builder.WriteString("last_price=")
	builder.WriteString(fmt.Sprintf("%v", pr.LastPrice))
	builder.WriteString(", ")
	builder.WriteString("ask=")
	builder.WriteString(fmt.Sprintf("%v", pr.Ask))
	builder.WriteString(", ")
	builder.WriteString("bid=")
	builder.WriteString(fmt.Sprintf("%v", pr.Bid))
	builder.WriteString(", ")
	builder.WriteString("time=")
	builder.WriteString(pr.Time.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Prices is a parsable slice of Price.
type Prices []*Price
