// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/portfolio.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/foxcool/greedy-eye/api/v1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PortfolioServiceName is the fully-qualified name of the PortfolioService service.
	PortfolioServiceName = "eye.v1.PortfolioService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PortfolioServiceCreatePortfolioProcedure is the fully-qualified name of the PortfolioService's
	// CreatePortfolio RPC.
	PortfolioServiceCreatePortfolioProcedure = "/eye.v1.PortfolioService/CreatePortfolio"
	// PortfolioServiceGetPortfolioProcedure is the fully-qualified name of the PortfolioService's
	// GetPortfolio RPC.
	PortfolioServiceGetPortfolioProcedure = "/eye.v1.PortfolioService/GetPortfolio"
	// PortfolioServiceUpdatePortfolioProcedure is the fully-qualified name of the PortfolioService's
	// UpdatePortfolio RPC.
	PortfolioServiceUpdatePortfolioProcedure = "/eye.v1.PortfolioService/UpdatePortfolio"
	// PortfolioServiceDeletePortfolioProcedure is the fully-qualified name of the PortfolioService's
	// DeletePortfolio RPC.
	PortfolioServiceDeletePortfolioProcedure = "/eye.v1.PortfolioService/DeletePortfolio"
	// PortfolioServiceListPortfoliosProcedure is the fully-qualified name of the PortfolioService's
	// ListPortfolios RPC.
	PortfolioServiceListPortfoliosProcedure = "/eye.v1.PortfolioService/ListPortfolios"
	// PortfolioServiceCalculatePortfolioValueProcedure is the fully-qualified name of the
	// PortfolioService's CalculatePortfolioValue RPC.
	PortfolioServiceCalculatePortfolioValueProcedure = "/eye.v1.PortfolioService/CalculatePortfolioValue"
	// PortfolioServiceListUnpricedHoldingsProcedure is the fully-qualified name of the
	// PortfolioService's ListUnpricedHoldings RPC.
	PortfolioServiceListUnpricedHoldingsProcedure = "/eye.v1.PortfolioService/ListUnpricedHoldings"
	// PortfolioServiceGetPortfolioPerformanceProcedure is the fully-qualified name of the
	// PortfolioService's GetPortfolioPerformance RPC.
	PortfolioServiceGetPortfolioPerformanceProcedure = "/eye.v1.PortfolioService/GetPortfolioPerformance"
	// PortfolioServiceCreateHoldingProcedure is the fully-qualified name of the PortfolioService's
	// CreateHolding RPC.
	PortfolioServiceCreateHoldingProcedure = "/eye.v1.PortfolioService/CreateHolding"
	// PortfolioServiceGetHoldingProcedure is the fully-qualified name of the PortfolioService's
	// GetHolding RPC.
	PortfolioServiceGetHoldingProcedure = "/eye.v1.PortfolioService/GetHolding"
	// PortfolioServiceUpdateHoldingProcedure is the fully-qualified name of the PortfolioService's
	// UpdateHolding RPC.
	PortfolioServiceUpdateHoldingProcedure = "/eye.v1.PortfolioService/UpdateHolding"
	// PortfolioServiceDeleteHoldingProcedure is the fully-qualified name of the PortfolioService's
	// DeleteHolding RPC.
	PortfolioServiceDeleteHoldingProcedure = "/eye.v1.PortfolioService/DeleteHolding"
	// PortfolioServiceImportPositionsProcedure is the fully-qualified name of the PortfolioService's
	// ImportPositions RPC.
	PortfolioServiceImportPositionsProcedure = "/eye.v1.PortfolioService/ImportPositions"
	// PortfolioServiceImportTransactionsProcedure is the fully-qualified name of the PortfolioService's
	// ImportTransactions RPC.
	PortfolioServiceImportTransactionsProcedure = "/eye.v1.PortfolioService/ImportTransactions"
	// PortfolioServiceListHoldingsProcedure is the fully-qualified name of the PortfolioService's
	// ListHoldings RPC.
	PortfolioServiceListHoldingsProcedure = "/eye.v1.PortfolioService/ListHoldings"
	// PortfolioServiceCreateAccountProcedure is the fully-qualified name of the PortfolioService's
	// CreateAccount RPC.
	PortfolioServiceCreateAccountProcedure = "/eye.v1.PortfolioService/CreateAccount"
	// PortfolioServiceGetAccountProcedure is the fully-qualified name of the PortfolioService's
	// GetAccount RPC.
	PortfolioServiceGetAccountProcedure = "/eye.v1.PortfolioService/GetAccount"
	// PortfolioServiceUpdateAccountProcedure is the fully-qualified name of the PortfolioService's
	// UpdateAccount RPC.
	PortfolioServiceUpdateAccountProcedure = "/eye.v1.PortfolioService/UpdateAccount"
	// PortfolioServiceDeleteAccountProcedure is the fully-qualified name of the PortfolioService's
	// DeleteAccount RPC.
	PortfolioServiceDeleteAccountProcedure = "/eye.v1.PortfolioService/DeleteAccount"
	// PortfolioServiceListAccountsProcedure is the fully-qualified name of the PortfolioService's
	// ListAccounts RPC.
	PortfolioServiceListAccountsProcedure = "/eye.v1.PortfolioService/ListAccounts"
	// PortfolioServiceListProvidersProcedure is the fully-qualified name of the PortfolioService's
	// ListProviders RPC.
	PortfolioServiceListProvidersProcedure = "/eye.v1.PortfolioService/ListProviders"
	// PortfolioServiceCreateTransactionProcedure is the fully-qualified name of the PortfolioService's
	// CreateTransaction RPC.
	PortfolioServiceCreateTransactionProcedure = "/eye.v1.PortfolioService/CreateTransaction"
	// PortfolioServiceGetTransactionProcedure is the fully-qualified name of the PortfolioService's
	// GetTransaction RPC.
	PortfolioServiceGetTransactionProcedure = "/eye.v1.PortfolioService/GetTransaction"
	// PortfolioServiceUpdateTransactionProcedure is the fully-qualified name of the PortfolioService's
	// UpdateTransaction RPC.
	PortfolioServiceUpdateTransactionProcedure = "/eye.v1.PortfolioService/UpdateTransaction"
	// PortfolioServiceListTransactionsProcedure is the fully-qualified name of the PortfolioService's
	// ListTransactions RPC.
	PortfolioServiceListTransactionsProcedure = "/eye.v1.PortfolioService/ListTransactions"
	// PortfolioServiceSyncAccountProcedure is the fully-qualified name of the PortfolioService's
	// SyncAccount RPC.
	PortfolioServiceSyncAccountProcedure = "/eye.v1.PortfolioService/SyncAccount"
	// PortfolioServiceGetAccountSweepScheduleProcedure is the fully-qualified name of the
	// PortfolioService's GetAccountSweepSchedule RPC.
	PortfolioServiceGetAccountSweepScheduleProcedure = "/eye.v1.PortfolioService/GetAccountSweepSchedule"
	// PortfolioServiceResetAccountSweepScheduleProcedure is the fully-qualified name of the
	// PortfolioService's ResetAccountSweepSchedule RPC.
	PortfolioServiceResetAccountSweepScheduleProcedure = "/eye.v1.PortfolioService/ResetAccountSweepSchedule"
)

// PortfolioServiceClient is a client for the eye.v1.PortfolioService service.
type PortfolioServiceClient interface {
	// --- Portfolio CRUD ---
	CreatePortfolio(context.Context, *connect.Request[v1.CreatePortfolioRequest]) (*connect.Response[v1.Portfolio], error)
	GetPortfolio(context.Context, *connect.Request[v1.GetPortfolioRequest]) (*connect.Response[v1.Portfolio], error)
	UpdatePortfolio(context.Context, *connect.Request[v1.UpdatePortfolioRequest]) (*connect.Response[v1.Portfolio], error)
	DeletePortfolio(context.Context, *connect.Request[v1.DeletePortfolioRequest]) (*connect.Response[emptypb.Empty], error)
	ListPortfolios(context.Context, *connect.Request[v1.ListPortfoliosRequest]) (*connect.Response[v1.ListPortfoliosResponse], error)
	// --- Portfolio business logic ---
	CalculatePortfolioValue(context.Context, *connect.Request[v1.CalculatePortfolioValueRequest]) (*connect.Response[v1.PortfolioValueResponse], error)
	// ListUnpricedHoldings walks the positions a valuation left out of the total.
	//
	// `ValuationCoverage.unpriced` is a sample: it stops at a cap while the count
	// stays exact, because that block travels in every valuation response. This
	// is the same information as a query, so the tail has somewhere to be asked
	// for. The sample belongs to the summary; the list belongs here.
	//
	// The result is computed the same way the total is, on the spot. Nothing
	// stores "unpriced" — it is what the pricing path concludes — so this cannot
	// disagree with the valuation it explains.
	ListUnpricedHoldings(context.Context, *connect.Request[v1.ListUnpricedHoldingsRequest]) (*connect.Response[v1.ListUnpricedHoldingsResponse], error)
	GetPortfolioPerformance(context.Context, *connect.Request[v1.GetPortfolioPerformanceRequest]) (*connect.Response[v1.PortfolioPerformanceResponse], error)
	// --- Holding CRUD ---
	CreateHolding(context.Context, *connect.Request[v1.CreateHoldingRequest]) (*connect.Response[v1.Holding], error)
	GetHolding(context.Context, *connect.Request[v1.GetHoldingRequest]) (*connect.Response[v1.Holding], error)
	UpdateHolding(context.Context, *connect.Request[v1.UpdateHoldingRequest]) (*connect.Response[v1.Holding], error)
	DeleteHolding(context.Context, *connect.Request[v1.DeleteHoldingRequest]) (*connect.Response[emptypb.Empty], error)
	// --- Batch import (manual accounts) ---
	// Simulation-first: call with dry_run=true to get the plan without writes,
	// confirm, then repeat with dry_run=false to commit under one import_id.
	ImportPositions(context.Context, *connect.Request[v1.ImportPositionsRequest]) (*connect.Response[v1.ImportPositionsResponse], error)
	ImportTransactions(context.Context, *connect.Request[v1.ImportTransactionsRequest]) (*connect.Response[v1.ImportTransactionsResponse], error)
	ListHoldings(context.Context, *connect.Request[v1.ListHoldingsRequest]) (*connect.Response[v1.ListHoldingsResponse], error)
	// --- Account CRUD ---
	CreateAccount(context.Context, *connect.Request[v1.CreateAccountRequest]) (*connect.Response[v1.Account], error)
	GetAccount(context.Context, *connect.Request[v1.GetAccountRequest]) (*connect.Response[v1.Account], error)
	UpdateAccount(context.Context, *connect.Request[v1.UpdateAccountRequest]) (*connect.Response[v1.Account], error)
	DeleteAccount(context.Context, *connect.Request[v1.DeleteAccountRequest]) (*connect.Response[emptypb.Empty], error)
	ListAccounts(context.Context, *connect.Request[v1.ListAccountsRequest]) (*connect.Response[v1.ListAccountsResponse], error)
	// ListProviders returns the external providers this build can talk to and
	// what each of them needs in accounts.data.
	//
	// Read-only and secret-free: it describes the shape of a credential, never a
	// credential. It exists so an account form stops guessing — the slugs, the
	// chains, the plans and the extra fields are the ones the resolver and the
	// rate limiter actually use, rather than a second copy that drifts.
	ListProviders(context.Context, *connect.Request[v1.ListProvidersRequest]) (*connect.Response[v1.ListProvidersResponse], error)
	// --- Transaction CRUD ---
	CreateTransaction(context.Context, *connect.Request[v1.CreateTransactionRequest]) (*connect.Response[v1.Transaction], error)
	GetTransaction(context.Context, *connect.Request[v1.GetTransactionRequest]) (*connect.Response[v1.Transaction], error)
	UpdateTransaction(context.Context, *connect.Request[v1.UpdateTransactionRequest]) (*connect.Response[v1.Transaction], error)
	ListTransactions(context.Context, *connect.Request[v1.ListTransactionsRequest]) (*connect.Response[v1.ListTransactionsResponse], error)
	// --- Account sync ---
	SyncAccount(context.Context, *connect.Request[v1.SyncAccountRequest]) (*connect.Response[v1.SyncAccountResponse], error)
	// GetAccountSweepSchedule reports which accounts the balance sweep is holding
	// back, why, and until when.
	//
	// The sweep takes the two stalest accounts an hour, and staleness is read off
	// the account's own holdings — so an account whose source answers and returns
	// nothing stays the stalest and takes a slot every hour, forever. Four of them
	// did exactly that between 31.08 and 03.09.2026 and every other wallet went
	// two days without a sync while the totals showed hourly prices on two-day-old
	// quantities. Standing such an account down fixes the queue and creates a new
	// thing nobody can see, which is why this exists in the same change.
	GetAccountSweepSchedule(context.Context, *connect.Request[v1.GetAccountSweepScheduleRequest]) (*connect.Response[v1.GetAccountSweepScheduleResponse], error)
	// ResetAccountSweepSchedule forgives the back-off accrued against accounts, so
	// they are eligible again instead of waiting out a deferral earned under
	// conditions that no longer hold.
	//
	// The same statement as its price-path twin, one entity over: a credential
	// repaired at 10:00 should not wait until 22:00 because the account spent the
	// night failing. The service cannot tell a repaired account from a broken one
	// — that is what the next sweep is for — so this withdraws the conclusion and
	// asserts nothing about whether the account will answer.
	//
	// A successful sync clears the same state on its own, including a hand-run
	// one. This RPC is for the case where an operator wants the SWEEP to try
	// again without syncing every account by hand.
	ResetAccountSweepSchedule(context.Context, *connect.Request[v1.ResetAccountSweepScheduleRequest]) (*connect.Response[v1.ResetAccountSweepScheduleResponse], error)
}

// NewPortfolioServiceClient constructs a client for the eye.v1.PortfolioService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPortfolioServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PortfolioServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	portfolioServiceMethods := v1.File_v1_portfolio_proto.Services().ByName("PortfolioService").Methods()
	return &portfolioServiceClient{
		createPortfolio: connect.NewClient[v1.CreatePortfolioRequest, v1.Portfolio](
			httpClient,
			baseURL+PortfolioServiceCreatePortfolioProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("CreatePortfolio")),
			connect.WithClientOptions(opts...),
		),
		getPortfolio: connect.NewClient[v1.GetPortfolioRequest, v1.Portfolio](
			httpClient,
			baseURL+PortfolioServiceGetPortfolioProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("GetPortfolio")),
			connect.WithClientOptions(opts...),
		),
		updatePortfolio: connect.NewClient[v1.UpdatePortfolioRequest, v1.Portfolio](
			httpClient,
			baseURL+PortfolioServiceUpdatePortfolioProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("UpdatePortfolio")),
			connect.WithClientOptions(opts...),
		),
		deletePortfolio: connect.NewClient[v1.DeletePortfolioRequest, emptypb.Empty](
			httpClient,
			baseURL+PortfolioServiceDeletePortfolioProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("DeletePortfolio")),
			connect.WithClientOptions(opts...),
		),
		listPortfolios: connect.NewClient[v1.ListPortfoliosRequest, v1.ListPortfoliosResponse](
			httpClient,
			baseURL+PortfolioServiceListPortfoliosProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("ListPortfolios")),
			connect.WithClientOptions(opts...),
		),
		calculatePortfolioValue: connect.NewClient[v1.CalculatePortfolioValueRequest, v1.PortfolioValueResponse](
			httpClient,
			baseURL+PortfolioServiceCalculatePortfolioValueProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("CalculatePortfolioValue")),
			connect.WithClientOptions(opts...),
		),
		listUnpricedHoldings: connect.NewClient[v1.ListUnpricedHoldingsRequest, v1.ListUnpricedHoldingsResponse](
			httpClient,
			baseURL+PortfolioServiceListUnpricedHoldingsProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("ListUnpricedHoldings")),
			connect.WithClientOptions(opts...),
		),
		getPortfolioPerformance: connect.NewClient[v1.GetPortfolioPerformanceRequest, v1.PortfolioPerformanceResponse](
			httpClient,
			baseURL+PortfolioServiceGetPortfolioPerformanceProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("GetPortfolioPerformance")),
			connect.WithClientOptions(opts...),
		),
		createHolding: connect.NewClient[v1.CreateHoldingRequest, v1.Holding](
			httpClient,
			baseURL+PortfolioServiceCreateHoldingProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("CreateHolding")),
			connect.WithClientOptions(opts...),
		),
		getHolding: connect.NewClient[v1.GetHoldingRequest, v1.Holding](
			httpClient,
			baseURL+PortfolioServiceGetHoldingProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("GetHolding")),
			connect.WithClientOptions(opts...),
		),
		updateHolding: connect.NewClient[v1.UpdateHoldingRequest, v1.Holding](
			httpClient,
			baseURL+PortfolioServiceUpdateHoldingProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("UpdateHolding")),
			connect.WithClientOptions(opts...),
		),
		deleteHolding: connect.NewClient[v1.DeleteHoldingRequest, emptypb.Empty](
			httpClient,
			baseURL+PortfolioServiceDeleteHoldingProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("DeleteHolding")),
			connect.WithClientOptions(opts...),
		),
		importPositions: connect.NewClient[v1.ImportPositionsRequest, v1.ImportPositionsResponse](
			httpClient,
			baseURL+PortfolioServiceImportPositionsProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("ImportPositions")),
			connect.WithClientOptions(opts...),
		),
		importTransactions: connect.NewClient[v1.ImportTransactionsRequest, v1.ImportTransactionsResponse](
			httpClient,
			baseURL+PortfolioServiceImportTransactionsProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("ImportTransactions")),
			connect.WithClientOptions(opts...),
		),
		listHoldings: connect.NewClient[v1.ListHoldingsRequest, v1.ListHoldingsResponse](
			httpClient,
			baseURL+PortfolioServiceListHoldingsProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("ListHoldings")),
			connect.WithClientOptions(opts...),
		),
		createAccount: connect.NewClient[v1.CreateAccountRequest, v1.Account](
			httpClient,
			baseURL+PortfolioServiceCreateAccountProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("CreateAccount")),
			connect.WithClientOptions(opts...),
		),
		getAccount: connect.NewClient[v1.GetAccountRequest, v1.Account](
			httpClient,
			baseURL+PortfolioServiceGetAccountProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("GetAccount")),
			connect.WithClientOptions(opts...),
		),
		updateAccount: connect.NewClient[v1.UpdateAccountRequest, v1.Account](
			httpClient,
			baseURL+PortfolioServiceUpdateAccountProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("UpdateAccount")),
			connect.WithClientOptions(opts...),
		),
		deleteAccount: connect.NewClient[v1.DeleteAccountRequest, emptypb.Empty](
			httpClient,
			baseURL+PortfolioServiceDeleteAccountProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("DeleteAccount")),
			connect.WithClientOptions(opts...),
		),
		listAccounts: connect.NewClient[v1.ListAccountsRequest, v1.ListAccountsResponse](
			httpClient,
			baseURL+PortfolioServiceListAccountsProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("ListAccounts")),
			connect.WithClientOptions(opts...),
		),
		listProviders: connect.NewClient[v1.ListProvidersRequest, v1.ListProvidersResponse](
			httpClient,
			baseURL+PortfolioServiceListProvidersProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("ListProviders")),
			connect.WithClientOptions(opts...),
		),
		createTransaction: connect.NewClient[v1.CreateTransactionRequest, v1.Transaction](
			httpClient,
			baseURL+PortfolioServiceCreateTransactionProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("CreateTransaction")),
			connect.WithClientOptions(opts...),
		),
		getTransaction: connect.NewClient[v1.GetTransactionRequest, v1.Transaction](
			httpClient,
			baseURL+PortfolioServiceGetTransactionProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("GetTransaction")),
			connect.WithClientOptions(opts...),
		),
		updateTransaction: connect.NewClient[v1.UpdateTransactionRequest, v1.Transaction](
			httpClient,
			baseURL+PortfolioServiceUpdateTransactionProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("UpdateTransaction")),
			connect.WithClientOptions(opts...),
		),
		listTransactions: connect.NewClient[v1.ListTransactionsRequest, v1.ListTransactionsResponse](
			httpClient,
			baseURL+PortfolioServiceListTransactionsProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("ListTransactions")),
			connect.WithClientOptions(opts...),
		),
		syncAccount: connect.NewClient[v1.SyncAccountRequest, v1.SyncAccountResponse](
			httpClient,
			baseURL+PortfolioServiceSyncAccountProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("SyncAccount")),
			connect.WithClientOptions(opts...),
		),
		getAccountSweepSchedule: connect.NewClient[v1.GetAccountSweepScheduleRequest, v1.GetAccountSweepScheduleResponse](
			httpClient,
			baseURL+PortfolioServiceGetAccountSweepScheduleProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("GetAccountSweepSchedule")),
			connect.WithClientOptions(opts...),
		),
		resetAccountSweepSchedule: connect.NewClient[v1.ResetAccountSweepScheduleRequest, v1.ResetAccountSweepScheduleResponse](
			httpClient,
			baseURL+PortfolioServiceResetAccountSweepScheduleProcedure,
			connect.WithSchema(portfolioServiceMethods.ByName("ResetAccountSweepSchedule")),
			connect.WithClientOptions(opts...),
		),
	}
}

// portfolioServiceClient implements PortfolioServiceClient.
type portfolioServiceClient struct {
	createPortfolio           *connect.Client[v1.CreatePortfolioRequest, v1.Portfolio]
	getPortfolio              *connect.Client[v1.GetPortfolioRequest, v1.Portfolio]
	updatePortfolio           *connect.Client[v1.UpdatePortfolioRequest, v1.Portfolio]
	deletePortfolio           *connect.Client[v1.DeletePortfolioRequest, emptypb.Empty]
	listPortfolios            *connect.Client[v1.ListPortfoliosRequest, v1.ListPortfoliosResponse]
	calculatePortfolioValue   *connect.Client[v1.CalculatePortfolioValueRequest, v1.PortfolioValueResponse]
	listUnpricedHoldings      *connect.Client[v1.ListUnpricedHoldingsRequest, v1.ListUnpricedHoldingsResponse]
	getPortfolioPerformance   *connect.Client[v1.GetPortfolioPerformanceRequest, v1.PortfolioPerformanceResponse]
	createHolding             *connect.Client[v1.CreateHoldingRequest, v1.Holding]
	getHolding                *connect.Client[v1.GetHoldingRequest, v1.Holding]
	updateHolding             *connect.Client[v1.UpdateHoldingRequest, v1.Holding]
	deleteHolding             *connect.Client[v1.DeleteHoldingRequest, emptypb.Empty]
	importPositions           *connect.Client[v1.ImportPositionsRequest, v1.ImportPositionsResponse]
	importTransactions        *connect.Client[v1.ImportTransactionsRequest, v1.ImportTransactionsResponse]
	listHoldings              *connect.Client[v1.ListHoldingsRequest, v1.ListHoldingsResponse]
	createAccount             *connect.Client[v1.CreateAccountRequest, v1.Account]
	getAccount                *connect.Client[v1.GetAccountRequest, v1.Account]
	updateAccount             *connect.Client[v1.UpdateAccountRequest, v1.Account]
	deleteAccount             *connect.Client[v1.DeleteAccountRequest, emptypb.Empty]
	listAccounts              *connect.Client[v1.ListAccountsRequest, v1.ListAccountsResponse]
	listProviders             *connect.Client[v1.ListProvidersRequest, v1.ListProvidersResponse]
	createTransaction         *connect.Client[v1.CreateTransactionRequest, v1.Transaction]
	getTransaction            *connect.Client[v1.GetTransactionRequest, v1.Transaction]
	updateTransaction         *connect.Client[v1.UpdateTransactionRequest, v1.Transaction]
	listTransactions          *connect.Client[v1.ListTransactionsRequest, v1.ListTransactionsResponse]
	syncAccount               *connect.Client[v1.SyncAccountRequest, v1.SyncAccountResponse]
	getAccountSweepSchedule   *connect.Client[v1.GetAccountSweepScheduleRequest, v1.GetAccountSweepScheduleResponse]
	resetAccountSweepSchedule *connect.Client[v1.ResetAccountSweepScheduleRequest, v1.ResetAccountSweepScheduleResponse]
}

// CreatePortfolio calls eye.v1.PortfolioService.CreatePortfolio.
func (c *portfolioServiceClient) CreatePortfolio(ctx context.Context, req *connect.Request[v1.CreatePortfolioRequest]) (*connect.Response[v1.Portfolio], error) {
	return c.createPortfolio.CallUnary(ctx, req)
}

// GetPortfolio calls eye.v1.PortfolioService.GetPortfolio.
func (c *portfolioServiceClient) GetPortfolio(ctx context.Context, req *connect.Request[v1.GetPortfolioRequest]) (*connect.Response[v1.Portfolio], error) {
	return c.getPortfolio.CallUnary(ctx, req)
}

// UpdatePortfolio calls eye.v1.PortfolioService.UpdatePortfolio.
func (c *portfolioServiceClient) UpdatePortfolio(ctx context.Context, req *connect.Request[v1.UpdatePortfolioRequest]) (*connect.Response[v1.Portfolio], error) {
	return c.updatePortfolio.CallUnary(ctx, req)
}

// DeletePortfolio calls eye.v1.PortfolioService.DeletePortfolio.
func (c *portfolioServiceClient) DeletePortfolio(ctx context.Context, req *connect.Request[v1.DeletePortfolioRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deletePortfolio.CallUnary(ctx, req)
}

// ListPortfolios calls eye.v1.PortfolioService.ListPortfolios.
func (c *portfolioServiceClient) ListPortfolios(ctx context.Context, req *connect.Request[v1.ListPortfoliosRequest]) (*connect.Response[v1.ListPortfoliosResponse], error) {
	return c.listPortfolios.CallUnary(ctx, req)
}

// CalculatePortfolioValue calls eye.v1.PortfolioService.CalculatePortfolioValue.
func (c *portfolioServiceClient) CalculatePortfolioValue(ctx context.Context, req *connect.Request[v1.CalculatePortfolioValueRequest]) (*connect.Response[v1.PortfolioValueResponse], error) {
	return c.calculatePortfolioValue.CallUnary(ctx, req)
}

// ListUnpricedHoldings calls eye.v1.PortfolioService.ListUnpricedHoldings.
func (c *portfolioServiceClient) ListUnpricedHoldings(ctx context.Context, req *connect.Request[v1.ListUnpricedHoldingsRequest]) (*connect.Response[v1.ListUnpricedHoldingsResponse], error) {
	return c.listUnpricedHoldings.CallUnary(ctx, req)
}

// GetPortfolioPerformance calls eye.v1.PortfolioService.GetPortfolioPerformance.
func (c *portfolioServiceClient) GetPortfolioPerformance(ctx context.Context, req *connect.Request[v1.GetPortfolioPerformanceRequest]) (*connect.Response[v1.PortfolioPerformanceResponse], error) {
	return c.getPortfolioPerformance.CallUnary(ctx, req)
}

// CreateHolding calls eye.v1.PortfolioService.CreateHolding.
func (c *portfolioServiceClient) CreateHolding(ctx context.Context, req *connect.Request[v1.CreateHoldingRequest]) (*connect.Response[v1.Holding], error) {
	return c.createHolding.CallUnary(ctx, req)
}

// GetHolding calls eye.v1.PortfolioService.GetHolding.
func (c *portfolioServiceClient) GetHolding(ctx context.Context, req *connect.Request[v1.GetHoldingRequest]) (*connect.Response[v1.Holding], error) {
	return c.getHolding.CallUnary(ctx, req)
}

// UpdateHolding calls eye.v1.PortfolioService.UpdateHolding.
func (c *portfolioServiceClient) UpdateHolding(ctx context.Context, req *connect.Request[v1.UpdateHoldingRequest]) (*connect.Response[v1.Holding], error) {
	return c.updateHolding.CallUnary(ctx, req)
}

// DeleteHolding calls eye.v1.PortfolioService.DeleteHolding.
func (c *portfolioServiceClient) DeleteHolding(ctx context.Context, req *connect.Request[v1.DeleteHoldingRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteHolding.CallUnary(ctx, req)
}

// ImportPositions calls eye.v1.PortfolioService.ImportPositions.
func (c *portfolioServiceClient) ImportPositions(ctx context.Context, req *connect.Request[v1.ImportPositionsRequest]) (*connect.Response[v1.ImportPositionsResponse], error) {
	return c.importPositions.CallUnary(ctx, req)
}

// ImportTransactions calls eye.v1.PortfolioService.ImportTransactions.
func (c *portfolioServiceClient) ImportTransactions(ctx context.Context, req *connect.Request[v1.ImportTransactionsRequest]) (*connect.Response[v1.ImportTransactionsResponse], error) {
	return c.importTransactions.CallUnary(ctx, req)
}

// ListHoldings calls eye.v1.PortfolioService.ListHoldings.
func (c *portfolioServiceClient) ListHoldings(ctx context.Context, req *connect.Request[v1.ListHoldingsRequest]) (*connect.Response[v1.ListHoldingsResponse], error) {
	return c.listHoldings.CallUnary(ctx, req)
}

// CreateAccount calls eye.v1.PortfolioService.CreateAccount.
func (c *portfolioServiceClient) CreateAccount(ctx context.Context, req *connect.Request[v1.CreateAccountRequest]) (*connect.Response[v1.Account], error) {
	return c.createAccount.CallUnary(ctx, req)
}

// GetAccount calls eye.v1.PortfolioService.GetAccount.
func (c *portfolioServiceClient) GetAccount(ctx context.Context, req *connect.Request[v1.GetAccountRequest]) (*connect.Response[v1.Account], error) {
	return c.getAccount.CallUnary(ctx, req)
}

// UpdateAccount calls eye.v1.PortfolioService.UpdateAccount.
func (c *portfolioServiceClient) UpdateAccount(ctx context.Context, req *connect.Request[v1.UpdateAccountRequest]) (*connect.Response[v1.Account], error) {
	return c.updateAccount.CallUnary(ctx, req)
}

// DeleteAccount calls eye.v1.PortfolioService.DeleteAccount.
func (c *portfolioServiceClient) DeleteAccount(ctx context.Context, req *connect.Request[v1.DeleteAccountRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteAccount.CallUnary(ctx, req)
}

// ListAccounts calls eye.v1.PortfolioService.ListAccounts.
func (c *portfolioServiceClient) ListAccounts(ctx context.Context, req *connect.Request[v1.ListAccountsRequest]) (*connect.Response[v1.ListAccountsResponse], error) {
	return c.listAccounts.CallUnary(ctx, req)
}

// ListProviders calls eye.v1.PortfolioService.ListProviders.
func (c *portfolioServiceClient) ListProviders(ctx context.Context, req *connect.Request[v1.ListProvidersRequest]) (*connect.Response[v1.ListProvidersResponse], error) {
	return c.listProviders.CallUnary(ctx, req)
}

// CreateTransaction calls eye.v1.PortfolioService.CreateTransaction.
func (c *portfolioServiceClient) CreateTransaction(ctx context.Context, req *connect.Request[v1.CreateTransactionRequest]) (*connect.Response[v1.Transaction], error) {
	return c.createTransaction.CallUnary(ctx, req)
}

// GetTransaction calls eye.v1.PortfolioService.GetTransaction.
func (c *portfolioServiceClient) GetTransaction(ctx context.Context, req *connect.Request[v1.GetTransactionRequest]) (*connect.Response[v1.Transaction], error) {
	return c.getTransaction.CallUnary(ctx, req)
}

// UpdateTransaction calls eye.v1.PortfolioService.UpdateTransaction.
func (c *portfolioServiceClient) UpdateTransaction(ctx context.Context, req *connect.Request[v1.UpdateTransactionRequest]) (*connect.Response[v1.Transaction], error) {
	return c.updateTransaction.CallUnary(ctx, req)
}

// ListTransactions calls eye.v1.PortfolioService.ListTransactions.
func (c *portfolioServiceClient) ListTransactions(ctx context.Context, req *connect.Request[v1.ListTransactionsRequest]) (*connect.Response[v1.ListTransactionsResponse], error) {
	return c.listTransactions.CallUnary(ctx, req)
}

// SyncAccount calls eye.v1.PortfolioService.SyncAccount.
func (c *portfolioServiceClient) SyncAccount(ctx context.Context, req *connect.Request[v1.SyncAccountRequest]) (*connect.Response[v1.SyncAccountResponse], error) {
	return c.syncAccount.CallUnary(ctx, req)
}

// GetAccountSweepSchedule calls eye.v1.PortfolioService.GetAccountSweepSchedule.
func (c *portfolioServiceClient) GetAccountSweepSchedule(ctx context.Context, req *connect.Request[v1.GetAccountSweepScheduleRequest]) (*connect.Response[v1.GetAccountSweepScheduleResponse], error) {
	return c.getAccountSweepSchedule.CallUnary(ctx, req)
}

// ResetAccountSweepSchedule calls eye.v1.PortfolioService.ResetAccountSweepSchedule.
func (c *portfolioServiceClient) ResetAccountSweepSchedule(ctx context.Context, req *connect.Request[v1.ResetAccountSweepScheduleRequest]) (*connect.Response[v1.ResetAccountSweepScheduleResponse], error) {
	return c.resetAccountSweepSchedule.CallUnary(ctx, req)
}

// PortfolioServiceHandler is an implementation of the eye.v1.PortfolioService service.
type PortfolioServiceHandler interface {
	// --- Portfolio CRUD ---
	CreatePortfolio(context.Context, *connect.Request[v1.CreatePortfolioRequest]) (*connect.Response[v1.Portfolio], error)
	GetPortfolio(context.Context, *connect.Request[v1.GetPortfolioRequest]) (*connect.Response[v1.Portfolio], error)
	UpdatePortfolio(context.Context, *connect.Request[v1.UpdatePortfolioRequest]) (*connect.Response[v1.Portfolio], error)
	DeletePortfolio(context.Context, *connect.Request[v1.DeletePortfolioRequest]) (*connect.Response[emptypb.Empty], error)
	ListPortfolios(context.Context, *connect.Request[v1.ListPortfoliosRequest]) (*connect.Response[v1.ListPortfoliosResponse], error)
	// --- Portfolio business logic ---
	CalculatePortfolioValue(context.Context, *connect.Request[v1.CalculatePortfolioValueRequest]) (*connect.Response[v1.PortfolioValueResponse], error)
	// ListUnpricedHoldings walks the positions a valuation left out of the total.
	//
	// `ValuationCoverage.unpriced` is a sample: it stops at a cap while the count
	// stays exact, because that block travels in every valuation response. This
	// is the same information as a query, so the tail has somewhere to be asked
	// for. The sample belongs to the summary; the list belongs here.
	//
	// The result is computed the same way the total is, on the spot. Nothing
	// stores "unpriced" — it is what the pricing path concludes — so this cannot
	// disagree with the valuation it explains.
	ListUnpricedHoldings(context.Context, *connect.Request[v1.ListUnpricedHoldingsRequest]) (*connect.Response[v1.ListUnpricedHoldingsResponse], error)
	GetPortfolioPerformance(context.Context, *connect.Request[v1.GetPortfolioPerformanceRequest]) (*connect.Response[v1.PortfolioPerformanceResponse], error)
	// --- Holding CRUD ---
	CreateHolding(context.Context, *connect.Request[v1.CreateHoldingRequest]) (*connect.Response[v1.Holding], error)
	GetHolding(context.Context, *connect.Request[v1.GetHoldingRequest]) (*connect.Response[v1.Holding], error)
	UpdateHolding(context.Context, *connect.Request[v1.UpdateHoldingRequest]) (*connect.Response[v1.Holding], error)
	DeleteHolding(context.Context, *connect.Request[v1.DeleteHoldingRequest]) (*connect.Response[emptypb.Empty], error)
	// --- Batch import (manual accounts) ---
	// Simulation-first: call with dry_run=true to get the plan without writes,
	// confirm, then repeat with dry_run=false to commit under one import_id.
	ImportPositions(context.Context, *connect.Request[v1.ImportPositionsRequest]) (*connect.Response[v1.ImportPositionsResponse], error)
	ImportTransactions(context.Context, *connect.Request[v1.ImportTransactionsRequest]) (*connect.Response[v1.ImportTransactionsResponse], error)
	ListHoldings(context.Context, *connect.Request[v1.ListHoldingsRequest]) (*connect.Response[v1.ListHoldingsResponse], error)
	// --- Account CRUD ---
	CreateAccount(context.Context, *connect.Request[v1.CreateAccountRequest]) (*connect.Response[v1.Account], error)
	GetAccount(context.Context, *connect.Request[v1.GetAccountRequest]) (*connect.Response[v1.Account], error)
	UpdateAccount(context.Context, *connect.Request[v1.UpdateAccountRequest]) (*connect.Response[v1.Account], error)
	DeleteAccount(context.Context, *connect.Request[v1.DeleteAccountRequest]) (*connect.Response[emptypb.Empty], error)
	ListAccounts(context.Context, *connect.Request[v1.ListAccountsRequest]) (*connect.Response[v1.ListAccountsResponse], error)
	// ListProviders returns the external providers this build can talk to and
	// what each of them needs in accounts.data.
	//
	// Read-only and secret-free: it describes the shape of a credential, never a
	// credential. It exists so an account form stops guessing — the slugs, the
	// chains, the plans and the extra fields are the ones the resolver and the
	// rate limiter actually use, rather than a second copy that drifts.
	ListProviders(context.Context, *connect.Request[v1.ListProvidersRequest]) (*connect.Response[v1.ListProvidersResponse], error)
	// --- Transaction CRUD ---
	CreateTransaction(context.Context, *connect.Request[v1.CreateTransactionRequest]) (*connect.Response[v1.Transaction], error)
	GetTransaction(context.Context, *connect.Request[v1.GetTransactionRequest]) (*connect.Response[v1.Transaction], error)
	UpdateTransaction(context.Context, *connect.Request[v1.UpdateTransactionRequest]) (*connect.Response[v1.Transaction], error)
	ListTransactions(context.Context, *connect.Request[v1.ListTransactionsRequest]) (*connect.Response[v1.ListTransactionsResponse], error)
	// --- Account sync ---
	SyncAccount(context.Context, *connect.Request[v1.SyncAccountRequest]) (*connect.Response[v1.SyncAccountResponse], error)
	// GetAccountSweepSchedule reports which accounts the balance sweep is holding
	// back, why, and until when.
	//
	// The sweep takes the two stalest accounts an hour, and staleness is read off
	// the account's own holdings — so an account whose source answers and returns
	// nothing stays the stalest and takes a slot every hour, forever. Four of them
	// did exactly that between 31.08 and 03.09.2026 and every other wallet went
	// two days without a sync while the totals showed hourly prices on two-day-old
	// quantities. Standing such an account down fixes the queue and creates a new
	// thing nobody can see, which is why this exists in the same change.
	GetAccountSweepSchedule(context.Context, *connect.Request[v1.GetAccountSweepScheduleRequest]) (*connect.Response[v1.GetAccountSweepScheduleResponse], error)
	// ResetAccountSweepSchedule forgives the back-off accrued against accounts, so
	// they are eligible again instead of waiting out a deferral earned under
	// conditions that no longer hold.
	//
	// The same statement as its price-path twin, one entity over: a credential
	// repaired at 10:00 should not wait until 22:00 because the account spent the
	// night failing. The service cannot tell a repaired account from a broken one
	// — that is what the next sweep is for — so this withdraws the conclusion and
	// asserts nothing about whether the account will answer.
	//
	// A successful sync clears the same state on its own, including a hand-run
	// one. This RPC is for the case where an operator wants the SWEEP to try
	// again without syncing every account by hand.
	ResetAccountSweepSchedule(context.Context, *connect.Request[v1.ResetAccountSweepScheduleRequest]) (*connect.Response[v1.ResetAccountSweepScheduleResponse], error)
}

// NewPortfolioServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPortfolioServiceHandler(svc PortfolioServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	portfolioServiceMethods := v1.File_v1_portfolio_proto.Services().ByName("PortfolioService").Methods()
	portfolioServiceCreatePortfolioHandler := connect.NewUnaryHandler(
		PortfolioServiceCreatePortfolioProcedure,
		svc.CreatePortfolio,
		connect.WithSchema(portfolioServiceMethods.ByName("CreatePortfolio")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceGetPortfolioHandler := connect.NewUnaryHandler(
		PortfolioServiceGetPortfolioProcedure,
		svc.GetPortfolio,
		connect.WithSchema(portfolioServiceMethods.ByName("GetPortfolio")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceUpdatePortfolioHandler := connect.NewUnaryHandler(
		PortfolioServiceUpdatePortfolioProcedure,
		svc.UpdatePortfolio,
		connect.WithSchema(portfolioServiceMethods.ByName("UpdatePortfolio")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceDeletePortfolioHandler := connect.NewUnaryHandler(
		PortfolioServiceDeletePortfolioProcedure,
		svc.DeletePortfolio,
		connect.WithSchema(portfolioServiceMethods.ByName("DeletePortfolio")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceListPortfoliosHandler := connect.NewUnaryHandler(
		PortfolioServiceListPortfoliosProcedure,
		svc.ListPortfolios,
		connect.WithSchema(portfolioServiceMethods.ByName("ListPortfolios")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceCalculatePortfolioValueHandler := connect.NewUnaryHandler(
		PortfolioServiceCalculatePortfolioValueProcedure,
		svc.CalculatePortfolioValue,
		connect.WithSchema(portfolioServiceMethods.ByName("CalculatePortfolioValue")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceListUnpricedHoldingsHandler := connect.NewUnaryHandler(
		PortfolioServiceListUnpricedHoldingsProcedure,
		svc.ListUnpricedHoldings,
		connect.WithSchema(portfolioServiceMethods.ByName("ListUnpricedHoldings")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceGetPortfolioPerformanceHandler := connect.NewUnaryHandler(
		PortfolioServiceGetPortfolioPerformanceProcedure,
		svc.GetPortfolioPerformance,
		connect.WithSchema(portfolioServiceMethods.ByName("GetPortfolioPerformance")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceCreateHoldingHandler := connect.NewUnaryHandler(
		PortfolioServiceCreateHoldingProcedure,
		svc.CreateHolding,
		connect.WithSchema(portfolioServiceMethods.ByName("CreateHolding")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceGetHoldingHandler := connect.NewUnaryHandler(
		PortfolioServiceGetHoldingProcedure,
		svc.GetHolding,
		connect.WithSchema(portfolioServiceMethods.ByName("GetHolding")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceUpdateHoldingHandler := connect.NewUnaryHandler(
		PortfolioServiceUpdateHoldingProcedure,
		svc.UpdateHolding,
		connect.WithSchema(portfolioServiceMethods.ByName("UpdateHolding")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceDeleteHoldingHandler := connect.NewUnaryHandler(
		PortfolioServiceDeleteHoldingProcedure,
		svc.DeleteHolding,
		connect.WithSchema(portfolioServiceMethods.ByName("DeleteHolding")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceImportPositionsHandler := connect.NewUnaryHandler(
		PortfolioServiceImportPositionsProcedure,
		svc.ImportPositions,
		connect.WithSchema(portfolioServiceMethods.ByName("ImportPositions")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceImportTransactionsHandler := connect.NewUnaryHandler(
		PortfolioServiceImportTransactionsProcedure,
		svc.ImportTransactions,
		connect.WithSchema(portfolioServiceMethods.ByName("ImportTransactions")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceListHoldingsHandler := connect.NewUnaryHandler(
		PortfolioServiceListHoldingsProcedure,
		svc.ListHoldings,
		connect.WithSchema(portfolioServiceMethods.ByName("ListHoldings")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceCreateAccountHandler := connect.NewUnaryHandler(
		PortfolioServiceCreateAccountProcedure,
		svc.CreateAccount,
		connect.WithSchema(portfolioServiceMethods.ByName("CreateAccount")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceGetAccountHandler := connect.NewUnaryHandler(
		PortfolioServiceGetAccountProcedure,
		svc.GetAccount,
		connect.WithSchema(portfolioServiceMethods.ByName("GetAccount")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceUpdateAccountHandler := connect.NewUnaryHandler(
		PortfolioServiceUpdateAccountProcedure,
		svc.UpdateAccount,
		connect.WithSchema(portfolioServiceMethods.ByName("UpdateAccount")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceDeleteAccountHandler := connect.NewUnaryHandler(
		PortfolioServiceDeleteAccountProcedure,
		svc.DeleteAccount,
		connect.WithSchema(portfolioServiceMethods.ByName("DeleteAccount")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceListAccountsHandler := connect.NewUnaryHandler(
		PortfolioServiceListAccountsProcedure,
		svc.ListAccounts,
		connect.WithSchema(portfolioServiceMethods.ByName("ListAccounts")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceListProvidersHandler := connect.NewUnaryHandler(
		PortfolioServiceListProvidersProcedure,
		svc.ListProviders,
		connect.WithSchema(portfolioServiceMethods.ByName("ListProviders")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceCreateTransactionHandler := connect.NewUnaryHandler(
		PortfolioServiceCreateTransactionProcedure,
		svc.CreateTransaction,
		connect.WithSchema(portfolioServiceMethods.ByName("CreateTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceGetTransactionHandler := connect.NewUnaryHandler(
		PortfolioServiceGetTransactionProcedure,
		svc.GetTransaction,
		connect.WithSchema(portfolioServiceMethods.ByName("GetTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceUpdateTransactionHandler := connect.NewUnaryHandler(
		PortfolioServiceUpdateTransactionProcedure,
		svc.UpdateTransaction,
		connect.WithSchema(portfolioServiceMethods.ByName("UpdateTransaction")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceListTransactionsHandler := connect.NewUnaryHandler(
		PortfolioServiceListTransactionsProcedure,
		svc.ListTransactions,
		connect.WithSchema(portfolioServiceMethods.ByName("ListTransactions")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceSyncAccountHandler := connect.NewUnaryHandler(
		PortfolioServiceSyncAccountProcedure,
		svc.SyncAccount,
		connect.WithSchema(portfolioServiceMethods.ByName("SyncAccount")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceGetAccountSweepScheduleHandler := connect.NewUnaryHandler(
		PortfolioServiceGetAccountSweepScheduleProcedure,
		svc.GetAccountSweepSchedule,
		connect.WithSchema(portfolioServiceMethods.ByName("GetAccountSweepSchedule")),
		connect.WithHandlerOptions(opts...),
	)
	portfolioServiceResetAccountSweepScheduleHandler := connect.NewUnaryHandler(
		PortfolioServiceResetAccountSweepScheduleProcedure,
		svc.ResetAccountSweepSchedule,
		connect.WithSchema(portfolioServiceMethods.ByName("ResetAccountSweepSchedule")),
		connect.WithHandlerOptions(opts...),
	)
	return "/eye.v1.PortfolioService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PortfolioServiceCreatePortfolioProcedure:
			portfolioServiceCreatePortfolioHandler.ServeHTTP(w, r)
		case PortfolioServiceGetPortfolioProcedure:
			portfolioServiceGetPortfolioHandler.ServeHTTP(w, r)
		case PortfolioServiceUpdatePortfolioProcedure:
			portfolioServiceUpdatePortfolioHandler.ServeHTTP(w, r)
		case PortfolioServiceDeletePortfolioProcedure:
			portfolioServiceDeletePortfolioHandler.ServeHTTP(w, r)
		case PortfolioServiceListPortfoliosProcedure:
			portfolioServiceListPortfoliosHandler.ServeHTTP(w, r)
		case PortfolioServiceCalculatePortfolioValueProcedure:
			portfolioServiceCalculatePortfolioValueHandler.ServeHTTP(w, r)
		case PortfolioServiceListUnpricedHoldingsProcedure:
			portfolioServiceListUnpricedHoldingsHandler.ServeHTTP(w, r)
		case PortfolioServiceGetPortfolioPerformanceProcedure:
			portfolioServiceGetPortfolioPerformanceHandler.ServeHTTP(w, r)
		case PortfolioServiceCreateHoldingProcedure:
			portfolioServiceCreateHoldingHandler.ServeHTTP(w, r)
		case PortfolioServiceGetHoldingProcedure:
			portfolioServiceGetHoldingHandler.ServeHTTP(w, r)
		case PortfolioServiceUpdateHoldingProcedure:
			portfolioServiceUpdateHoldingHandler.ServeHTTP(w, r)
		case PortfolioServiceDeleteHoldingProcedure:
			portfolioServiceDeleteHoldingHandler.ServeHTTP(w, r)
		case PortfolioServiceImportPositionsProcedure:
			portfolioServiceImportPositionsHandler.ServeHTTP(w, r)
		case PortfolioServiceImportTransactionsProcedure:
			portfolioServiceImportTransactionsHandler.ServeHTTP(w, r)
		case PortfolioServiceListHoldingsProcedure:
			portfolioServiceListHoldingsHandler.ServeHTTP(w, r)
		case PortfolioServiceCreateAccountProcedure:
			portfolioServiceCreateAccountHandler.ServeHTTP(w, r)
		case PortfolioServiceGetAccountProcedure:
			portfolioServiceGetAccountHandler.ServeHTTP(w, r)
		case PortfolioServiceUpdateAccountProcedure:
			portfolioServiceUpdateAccountHandler.ServeHTTP(w, r)
		case PortfolioServiceDeleteAccountProcedure:
			portfolioServiceDeleteAccountHandler.ServeHTTP(w, r)
		case PortfolioServiceListAccountsProcedure:
			portfolioServiceListAccountsHandler.ServeHTTP(w, r)
		case PortfolioServiceListProvidersProcedure:
			portfolioServiceListProvidersHandler.ServeHTTP(w, r)
		case PortfolioServiceCreateTransactionProcedure:
			portfolioServiceCreateTransactionHandler.ServeHTTP(w, r)
		case PortfolioServiceGetTransactionProcedure:
			portfolioServiceGetTransactionHandler.ServeHTTP(w, r)
		case PortfolioServiceUpdateTransactionProcedure:
			portfolioServiceUpdateTransactionHandler.ServeHTTP(w, r)
		case PortfolioServiceListTransactionsProcedure:
			portfolioServiceListTransactionsHandler.ServeHTTP(w, r)
		case PortfolioServiceSyncAccountProcedure:
			portfolioServiceSyncAccountHandler.ServeHTTP(w, r)
		case PortfolioServiceGetAccountSweepScheduleProcedure:
			portfolioServiceGetAccountSweepScheduleHandler.ServeHTTP(w, r)
		case PortfolioServiceResetAccountSweepScheduleProcedure:
			portfolioServiceResetAccountSweepScheduleHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPortfolioServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPortfolioServiceHandler struct{}

func (UnimplementedPortfolioServiceHandler) CreatePortfolio(context.Context, *connect.Request[v1.CreatePortfolioRequest]) (*connect.Response[v1.Portfolio], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.CreatePortfolio is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) GetPortfolio(context.Context, *connect.Request[v1.GetPortfolioRequest]) (*connect.Response[v1.Portfolio], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.GetPortfolio is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) UpdatePortfolio(context.Context, *connect.Request[v1.UpdatePortfolioRequest]) (*connect.Response[v1.Portfolio], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.UpdatePortfolio is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) DeletePortfolio(context.Context, *connect.Request[v1.DeletePortfolioRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.DeletePortfolio is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) ListPortfolios(context.Context, *connect.Request[v1.ListPortfoliosRequest]) (*connect.Response[v1.ListPortfoliosResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.ListPortfolios is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) CalculatePortfolioValue(context.Context, *connect.Request[v1.CalculatePortfolioValueRequest]) (*connect.Response[v1.PortfolioValueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.CalculatePortfolioValue is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) ListUnpricedHoldings(context.Context, *connect.Request[v1.ListUnpricedHoldingsRequest]) (*connect.Response[v1.ListUnpricedHoldingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.ListUnpricedHoldings is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) GetPortfolioPerformance(context.Context, *connect.Request[v1.GetPortfolioPerformanceRequest]) (*connect.Response[v1.PortfolioPerformanceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.GetPortfolioPerformance is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) CreateHolding(context.Context, *connect.Request[v1.CreateHoldingRequest]) (*connect.Response[v1.Holding], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.CreateHolding is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) GetHolding(context.Context, *connect.Request[v1.GetHoldingRequest]) (*connect.Response[v1.Holding], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.GetHolding is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) UpdateHolding(context.Context, *connect.Request[v1.UpdateHoldingRequest]) (*connect.Response[v1.Holding], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.UpdateHolding is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) DeleteHolding(context.Context, *connect.Request[v1.DeleteHoldingRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.DeleteHolding is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) ImportPositions(context.Context, *connect.Request[v1.ImportPositionsRequest]) (*connect.Response[v1.ImportPositionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.ImportPositions is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) ImportTransactions(context.Context, *connect.Request[v1.ImportTransactionsRequest]) (*connect.Response[v1.ImportTransactionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.ImportTransactions is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) ListHoldings(context.Context, *connect.Request[v1.ListHoldingsRequest]) (*connect.Response[v1.ListHoldingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.ListHoldings is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) CreateAccount(context.Context, *connect.Request[v1.CreateAccountRequest]) (*connect.Response[v1.Account], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.CreateAccount is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) GetAccount(context.Context, *connect.Request[v1.GetAccountRequest]) (*connect.Response[v1.Account], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.GetAccount is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) UpdateAccount(context.Context, *connect.Request[v1.UpdateAccountRequest]) (*connect.Response[v1.Account], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.UpdateAccount is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) DeleteAccount(context.Context, *connect.Request[v1.DeleteAccountRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.DeleteAccount is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) ListAccounts(context.Context, *connect.Request[v1.ListAccountsRequest]) (*connect.Response[v1.ListAccountsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.ListAccounts is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) ListProviders(context.Context, *connect.Request[v1.ListProvidersRequest]) (*connect.Response[v1.ListProvidersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.ListProviders is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) CreateTransaction(context.Context, *connect.Request[v1.CreateTransactionRequest]) (*connect.Response[v1.Transaction], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.CreateTransaction is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) GetTransaction(context.Context, *connect.Request[v1.GetTransactionRequest]) (*connect.Response[v1.Transaction], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.GetTransaction is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) UpdateTransaction(context.Context, *connect.Request[v1.UpdateTransactionRequest]) (*connect.Response[v1.Transaction], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.UpdateTransaction is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) ListTransactions(context.Context, *connect.Request[v1.ListTransactionsRequest]) (*connect.Response[v1.ListTransactionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.ListTransactions is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) SyncAccount(context.Context, *connect.Request[v1.SyncAccountRequest]) (*connect.Response[v1.SyncAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.SyncAccount is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) GetAccountSweepSchedule(context.Context, *connect.Request[v1.GetAccountSweepScheduleRequest]) (*connect.Response[v1.GetAccountSweepScheduleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.GetAccountSweepSchedule is not implemented"))
}

func (UnimplementedPortfolioServiceHandler) ResetAccountSweepSchedule(context.Context, *connect.Request[v1.ResetAccountSweepScheduleRequest]) (*connect.Response[v1.ResetAccountSweepScheduleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("eye.v1.PortfolioService.ResetAccountSweepSchedule is not implemented"))
}
